### ISSUE TITLE
`andSet()` re-using properties between mock objects.

### ISSUE THREAD

**Issue by maccath** [mockery/mockery#1005]
I'm experiencing an issue with Mockery expectations with `andSet`.

**Mockery version:** 1.2.3
**PHPUnit version:** 8.3.4
**PHP version:** 7.3.9

Here is a simple example of the issue:

```
class MockeryTest extends MockeryTestCase
{
    public function testMockery()
    {
        $mockClass = \Mockery::mock('FakeClass');
        $mockClassTwo = \Mockery::mock('FakeClass');

        $mockClass->shouldReceive('setAttribute')
            ->with('name', 'Katy')
            ->andSet('name', 'Katy');

        $mockClassTwo->shouldReceive('setAttribute')
            ->with('name', 'Mike')
            ->andSet('name', 'Mike');

        $mockClass->setAttribute('name', 'Katy');
        $mockClassTwo->setAttribute('name', 'Mike');

        $this->assertEquals('Katy', $mockClass->name);
        $this->assertEquals('Mike', $mockClassTwo->name);
    }
}
```

The tests fail with:

```
Failed asserting that two strings are equal.
Expected :'Katy'
Actual   :'Mike'
```

It seems as though two mocks of the same class are treated as the same object, and properties set on them via `andSet` are shared.

If I set the properties on the mock objects directly (e.g. with `$mockClass->name = 'Katy'`), the tests pass. Similarly, if I use two different class names (e.g. `'FakeClass'` and `'FakeClassTwo`'), the tests pass. It also works if I use named mocks.

Is this intentional, or a bug? If it is intentional, is the only workaround to use named mocks?

**Comment by robertbasic** [comment]
Fixed with #1012, thank you @maccath!
