### ISSUE TITLE
Support PHPUnit Comparators

### ISSUE THREAD

**Issue by elnur** [mockery/mockery#1006]
We have a ton of custom comparators extending `\SebastianBergmann\Comparator\Comparator`. Without them, built-in PHP equality fails because our ORM models are pretty complicated. I've started migrating from PHPUnit's native mocking framework to Mockery, and turns out Mockery doesn't use those comparators. Hence mock expectations fail when they're not supposed to. It's a blocker for our further migration to Mockery.

I think the Mockery's PHPUnit integration should support using comparators. Some kind of a configuration setting to turn this on.

**Comment by robertbasic** [comment]
Mockery supports [Hamcrest matchers](https://github.com/hamcrest/hamcrest-php) officially, take a look at those, maybe those can help you.

Other than that, take a look at [complex argument matching](http://docs.mockery.io/en/latest/cookbook/mockery_on.html), you should be able to use phpunit comparators through that.

We probably wouldn't turn away a PR that adds support for phpunit comparators, but the core team is tight on time to add that support themselves.

**Comment by oprypkhantc** [comment]
@ghostwriter Now that Hamcrest support is not official, would a PR adding support for PHPUnit constraints be welcomed? Sure, Mockery has some built-in matchers, but PHPUnit has a lot more to offer: https://github.com/sebastianbergmann/phpunit/tree/main/src/Framework/Constraint

I anticipate this becoming increasingly more of a problem as more people migrate to Mockery 2.0.
