### ISSUE TITLE
documentation not updated on docs.mockery.io

### ISSUE THREAD

**Issue by robnagy** [mockery/mockery#1036]
I was looking to edit some confusing documentation only to find it had already been edited in this repo in 2018. 

Is there a chance of getting updates pushed to the official documentation site so everyone can benefit?

e.g. https://github.com/mockery/mockery/blob/master/docs/reference/creating_test_doubles.rst
is different from both http://docs.mockery.io/en/latest/reference/creating_test_doubles.html and http://docs.mockery.io/en/master/reference/creating_test_doubles.html

**Comment by davedevelopment** [comment]
Somehow we either forgot to set up a webhook, or the webhook disappeared... should be better now.
