### ISSUE TITLE
Arg matching with assoc arrays - order of elements

### ISSUE THREAD

**Issue by specialtactics** [mockery/mockery#1046]
Hi

I am mocking a method and comparing the args it receives - like this;

```php
        $this->mock('Class')
            ->shouldReceive('Method')
            ->once()
            ->withArgs([$entry]);
```
However I have an odd issue where the array elements (associative) are sometimes in a slightly different order in different computers (ie. bitbucket pipelines they are different to my home computer), and if they are not exactly in the same order, mockery throws an exception saying it cant find the given args - which is super annoying, especially because i really dont care about the ordering (since it's an assoc array).

Is there a way to compare arrays without a care for order of elements of they are associative? Any other recommendations?

Thanks!

**Comment by robertbasic** [comment]
Hey, you could use [Mockery::on](http://docs.mockery.io/en/latest/cookbook/mockery_on.html) to do this.

**Comment by specialtactics** [comment]
Thanks @robertbasic I think I figured out something that works, essentially using asset equals cannonicalising inside and then returning true achieves this effect.
