### ISSUE TITLE
Unable to partial mock manually-instantiated object / spy

### ISSUE THREAD

**Issue by jamesaspence** [mockery/mockery#1047]
Assume I have some code like the below:
```
class FooTest
{
    public function conditional()
    {
        //Assume more logic here
        return false;
    }

    public function doAThing()
    {
        if (!$this->conditional()) {
            return;
        }

        $this->callSecondThing();
    }

    public function callSecondThing()
    {

    }
}
```

I'm writing a test like this:
```
$instance = Mockery::mock(new FooTest());
$instance->shouldReceive('conditional')
    ->andReturnTrue();
$instance->shouldReceive('callSecondThing')
    ->once();

$instance->doAThing();
```

I'd expect that with the above, I'd be doing a few things:
- Mocking out the `conditional()` call with a mocked return value
- Mocking out the `doAThing()` call.

Instead, what happens is my mocks are not applied - the original `conditional()` is called instead and it completely ignores my stubs.

Am I misconfiguring? I'd like to be able to stub in this way because I have methods that will call other instance methods on the same class that I'm testing. I don't want to test the functionality for those other method calls again, so I'd prefer to mock out those calls while still calling `doAThing()`. I could also do a full mock of my `FooTest` but I'm trying to avoid that if possible as I'd have to do a lot more setup.

**Comment by davedevelopment** [comment]
The type of partial you are creating there is what we call a "Proxied Partial Mock" and would be our last resort, as you run in to problems like the one you have there. 

Could you use a runtime partial instead?

``` php
$mock = Mockery::mock(FooTest::class)->makePartial();
$mock->allows()->conditional()->andReturns(true);
$mock->expects()->callSecondThing();
$mock->doAThing();
Mockery::close();
```

**Comment by jamesaspence** [comment]
@davedevelopment I am relying on the constructor arguments I pass in as I end up passing those into the calls my method will make under the hood. A lot of my expectations are argument-based (which might be breaking the principle of black boxed tests a bit) - I run the code and ensure child calls are made correctly w/ correctly-formatted data, or that we short circuit when needed.

I ended up just mocking out the other method calls made inside of my class, which is just verbose but gets the job done. I was just hoping that I could do something to what is possible with Java's Mockito, where you can set up a `spy` and then mock entire method calls on it. They have a separate API for method assertions vs. setting up stubs, however (`Mockito.when` vs `Mockito.verify`)

**Comment by davedevelopment** [comment]
@jamesaspence ok, sounds like you got to where you needed to be, but just in case this might have helped, you can include constructor arguments in the call to `Mockery::mock`.

``` php
class Bar
{
    public function baz() {
        echo "baz";
    }
}
class FooTest
{
    function __construct(Bar $bar)
    {
        $this->bar = $bar;
    }

    public function conditional()
    {
        //Assume more logic here
        return false;
    }

    public function doAThing()
    {
        if (!$this->conditional()) {
            return;
        }

        $this->bar->baz();

        $this->callSecondThing();
    }

    public function callSecondThing()
    {

    }
}

$mock = Mockery::mock(FooTest::class, [new Bar])->makePartial();
$mock->allows()->conditional()->andReturns(true);
$mock->expects()->callSecondThing();
$mock->doAThing(); // "baz"
Mockery::close();
```

**Comment by jamesaspence** [comment]
Thanks! I'll have to give that a go when I revisit this testing.
In the meantime, gonna close this issue.
