### ISSUE TITLE
v1.3 Support

### ISSUE THREAD

**Issue by nobuf** [mockery/mockery#1065]
As 1.4 requires php7.3, some developers are probably being stuck on using 1.3.x for a while including myself. I was wondering if there's a plan on releasing 1.3.2. In particular, I'm hoping https://github.com/mockery/mockery/pull/1054 will be merged since the latest PHPStorm shows warnings on those parameters.

Thanks!

**Comment by davedevelopment** [comment]
I'm not against maintaining a 1.3 branch, but I'm not going to spend a lot of time on it. Merges like #1054 aren't the problem, but in the past people have requested more difficult back ports, then shied away when I asked for contributions etc.

I've just pushed a 1.3 branch, send PRs to that branch and we'll try and keep them going for a short while.

**Comment by nobuf** [comment]
Thanks a ton! My team has been using 1.1 for some time and pretty happy with it.

**Comment by GrahamCampbell** [comment]
Related: https://github.com/mockery/mockery/pull/1072.

**Comment by GrahamCampbell** [comment]
I think this can be closed now. :)

**Comment by nobuf** [comment]
https://github.com/mockery/mockery/releases/tag/1.3.2 👯
