### ISSUE TITLE
why -dev?

### ISSUE THREAD

**Issue by ftrotter** [mockery/mockery#1100]
If this is a project past its 1.0 mark, then why does the documentation ask for the -dev flag on composer install?

Shouldn't we be installing the latest stable version.. and not the latest version?

**Comment by GrahamCampbell** [comment]
The `--dev` flag does not refer to stability. It refers to adding mockery to the `require-dev` entries instead of `require`.

**Comment by ftrotter** [comment]
Thanks for the clarification!!
