### ISSUE TITLE
Union type like "array|string|null" or "string|int|null" crashes Mockery

### ISSUE THREAD

**Issue by LeSuisse** [mockery/mockery#1105]
The following code snippet crashes when the code generated by Mockery is evaluated.

```php
class Foo {
    public function bar(array|string|null $v) {}
}

Mockery::mock(Foo::class);
```

In this situation, the generated code looks like this:
```php
public function bar(array|string|null|null $v) {
    $argc = func_num_args();
    $argv = func_get_args();
    $ret = $this->_mockery_handleMethodCall(__FUNCTION__, $argv);
    return $ret;
}
```

I found this issue because of a mock of a class provided by a PHP extension, so I took a quick look at the other classes declared in my environment. At least the following classes are affected:
* `MultipleIterator::class`
* `DOMXPath::class`
* `IntlDateFormatter::class`
* `Phar::class`
* `PharData::class`
* `SoapFault::class`
* `SoapHeader::class`
* `XSLTProcessor::class`
* `ZipArchive::class`

It seems the support introduced by #1088 needs to be improved a bit to manage this case. I will try to take a look later this week.

**Comment by GrahamCampbell** [comment]
What version of mockery are you using?

**Comment by LeSuisse** [comment]
1.4.2.
The issue can also be reproduced on the current main branch, see https://github.com/LeSuisse/mockery/commit/d328ed672ff6b9fc5be01848371d6e7750ab1d32
