### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by LeSuisse** [mockery/mockery#1108]
Hi,

Would you like a contribution to move the existing Travis CI pipeline to GitHub Actions?
I should be able to dedicate some time later this month if you wish it.

Travis CI (at least for OSS projects) has often a important build backlog these days increasing the feedback loop for contributors. The [new pricing](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) is not as advantageous as it used to be and it seems the general trend for PHP packages hosted on GitHub is to use the GitHub Actions.

**Comment by davedevelopment** [comment]
I'm fairly neutral on this, will see what @robertbasic says. A balance between reliability and relevancy is what I would look for.

**Comment by GrahamCampbell** [comment]
This can be closed. This is already implemented, after Travis stopped running.
