### ISSUE TITLE
Problem with with() method's annotations

### ISSUE THREAD

**Issue by aruku** [mockery/mockery#1111]
I have the following mock working:
```
    public function setUp(): void
    {
        $this->loggerMock = Mockery::mock(LoggerInterface::class)->shouldIgnoreMissing();

        $dateCreateMock = PHPMockery::mock('AppBundle\Account', 'date_create_immutable');
        $dateCreateMock
            ->with($this->nowParamToMock)
            ->andReturn(new DateTimeImmutable($this->currentDateToMock));
        // For anything else, meaning the test data, just forward the call
        $dateCreateMock
            ->withAnyArgs()
            ->andReturnUsing('date_create_immutable');

        $this->subject = new Account2SVService(
            $this->loggerMock,
            $this->baseDateToMock,
            $this->expirationThreshold,
        );
    }
```
The parameter to `with()` (the string _now_) is flagged by PhpStorm as that method expects `mixed[]|\mixed[][]` (looking at the source I can see `mixed[]` in the docblock, so I don't know where the second one comes from).

But if I enclose my variable in an array, the test fails as the mock doesn't answer that call (I guess that is what is happening).

Is that annotation right? And should I be able to fix that inspection somehow?

**Comment by davedevelopment** [comment]
I'm afraid I don't know much about PHPStorm and how it responds to things. The `with` method essentially takes anything you throw at it.

**Comment by aruku** [comment]
Thank you for checking in!
