### ISSUE TITLE
PHP Fatal error:  Duplicate type null is redundant

### ISSUE THREAD

**Issue by foremtehan** [mockery/mockery#1116]
PHP 8.0
Mockery v1.4.2

I want to mock php built-in class `ZipArchive` : 

```php
$zip = Mockery::mock(ZipArchive::class);

$zip->shouldReceive('open')->andReturn(true);
```

But i get this error:

>PHP Fatal error:  Duplicate type null is redundant in \vendor\mockery\mockery\library\Mockery\Loader\EvalLoader.php(34) : eval()'d code on line 1176

>In EvalLoader.php(34) : eval()'d code line 1176:

**Comment by lukasyelle** [comment]
I am also having this issue when calling a Facade.

PHP 8.0
PHPUnit 9.5.1
Mockery 1.4.2

```php
/** @test */
public function itCanCreateOrdersThroughFacade()
{
    \Lukasyelle\AlpacaSdk\Facades\Orders\CreateOrder::shouldReceive('from')->once()->andReturn($this->expectedResult());

    \Lukasyelle\AlpacaSdk\Facades\Orders\CreateOrder::from($this->orderData);
}
```

Yields 
```bash
PHP Fatal error:  Duplicate type null is redundant in /vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code on line 957
```

**Comment by lukasyelle** [comment]
I was experiencing the same error for a custom class I am working on. It seems that my issue was related to how I had set up the following constructor that was attempting to be mocked:

```php
public function __construct(AlpacaTrading $tradingApi, Order|array $order = null)
{
    parent::__construct($tradingApi);

    return $order ? $this->from($order) : $this;
}
```

It didn't like having to mock the type-hinted nullable param $order. Changing the constructor to the following alleviated the issue for me. 

```php
public function __construct(AlpacaTrading $tradingApi, array $order = null)
{
    parent::__construct($tradingApi);

    return $order ? $this->from($order) : $this;
}
```

**Comment by downsider** [comment]
Reckon I'm hitting this one too, with PHP8.0 and Mockery 1.4.2

Trying to mock a class with this method cause the "Duplicate type" error:
```
public function add(ActionableInterface $component, array|string|null $definition, ?string $type = null): void
{
    //...
}
```

Changing the type hint for `$definition` to `mixed` resolves the error, but is obviously not desirable.

**Comment by downsider** [comment]
On investigation, this was fixed in #1106

Looks like it's just waiting for a new release

@davedevelopment any chance this could be released soon please?

**Comment by davedevelopment** [comment]
Sorry for the delay, will see if I can schedule some time this week to merge the branches and release.

**Comment by downsider** [comment]
Thanks for the release @davedevelopment
