### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Babwenbiber** [mockery/mockery#1124]
Hey guys,
great Lib!
I have seen your LICENSE file, but it had no category in it.
Is it an MIT License?

Cheers

**Comment by davedevelopment** [comment]
Hi there, I believe it is [BSD-3-Clause](https://opensource.org/licenses/BSD-3-Clause)

**Comment by GrahamCampbell** [comment]
See https://github.com/mockery/mockery/blob/master/composer.json#L20.

**Comment by Babwenbiber** [comment]
Thank you so much ;)
