### ISSUE TITLE
`stub` unable to mock in this scenario

### ISSUE THREAD

**Issue by bedwards-mango** [mockery/mockery#1150]
Hello

Thank you for this package - I work on a project that writes unit tests and mocking can be incredibly useful. We recently transitioned to **mockery** after `testthat::with_mock` was deprecated. We're struggling to adapt to **mockery** as we often encounter scenarios where it doesn't work - perhaps someone can offer some help?

Here is a reprex of a time where `mockery::stub` threw an error:

```
mockery::stub(
    where = wdman::phantomjs,
    what = "binman::app_dir",
    how = function(x) "binaries/binman_phantomjs/",
    depth = 2
)
```

This throws the error
```
Error in assign(where_name, func, parent_env) : 
  cannot change value of locked binding for '%+%'
```

Is this a bug, or is the function being used incorrectly? 

Thanks :) 
-Brandon

**Comment by davedevelopment** [comment]
@bedwards-mango I think you might have the wrong repository - https://github.com/r-lib/mockery

**Comment by bedwards-mango** [comment]
Ah indeed I do

My bad!
