### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by carloscz** [mockery/mockery#1152]
Hi, are you considering/have roadmap for PHP 8.1 support as it is GA now? :)

**Comment by davedevelopment** [comment]
Consider this the roadmap :+1:, comment here with anything and I'll try and triage.

- [ ] #1154

**Comment by keithbrink** [comment]
`getTypeInformation` in the Reflector class doesn't support ReflectionIntersectionType.

**Comment by ghostwriter** [comment]
Closed via: 
- #1130
- #1140
- #1160
- #1164
- #1184
