### ISSUE TITLE
Tag new release to support `static`

### ISSUE THREAD

**Issue by ruudk** [mockery/mockery#1161]
Symfony 6 added a lot of `static` return types. Currently our test suite breaks because Mockery 1.4.4 does not yet support it. 

This was fixed in https://github.com/mockery/mockery/pull/1157. 

It would be great to have a new tagged release so that everyone using Symfony 6 won't hit the same issue as we have.

Thanks 💙

**Comment by davedevelopment** [comment]
Hi there, I have this on my list for this week. I just wanted to take a quick look through the release notes for PHP 8.1, see if there is anything else Mockery might stumble upon and hopefully tentatively say we support 8.1 as well.

**Comment by davedevelopment** [comment]
Tagged 1.5.0
