### ISSUE TITLE
Mocking objects containing intersection type hints not working

### ISSUE THREAD

**Issue by programmador** [mockery/mockery#1172]
For example if You have an object
```
class MyClass {
  __construct(TypeA & TypeB $arg) {}
}
```
then while trying to mock it:
```
new \Mockery::mock(MyClass::class)
```
You will encounter an error:
```
Error: Call to undefined method ReflectionIntersectionType::getName()
```

As Mockery is a PHPUnit wrapper it should be actually possible.
Currently as a fallback I use native PHPUnit mocks and it works.
Probably PHPUnit 9.5 supports mocking such types starting from this https://github.com/sebastianbergmann/phpunit/issues/4932
In my case 9.5.20 is ok. I don't know into which exact version was the abovementioned support backported.

**Comment by ghostwriter** [comment]
resolved via #1164
