### ISSUE TITLE
Document how to expect multiple calls with different args and return values

### ISSUE THREAD

**Issue by mikehaertl** [mockery/mockery#1176]
I spent quite some time to figure out, how to use mockery if you expect multiple calls to the same function with different parameters and return values. It wasn't clear to me that this works:

```php
$mock
    // 1st call
    ->shouldReceive('send')
    ->once()
    ->with('some', 'values')
    ->andReturn('first')

    // 2nd call
    ->shouldReceive('send')
    ->once()
    ->with('some', 'other', 'values')
    ->andReturn('second')

    // seems to be required to prevent further calls:
    ->shouldReceive('send')
    ->never();
```

Found here: https://stackoverflow.com/a/26510303/767752

Before that I used a closure function with a `static $counter = 1` variable to count the calls to the method for both, the argument validation and the return values and expect/return depending on the current counter value. This felt very ugly.

I don't know, if the above is really valid - but it works. Maybe this should be added to the documentation somewhere.

**Comment by ghostwriter** [comment]
Based on the current docs: https://docs.mockery.io/en/latest/reference/expectations.html

``` php
$mock->shouldReceive('send')
     ->withArgs([['some', 'values'], ['some', 'other', 'values']])
     ->andReturn('first', 'second');
```

This expects `send` to be called twice; first with `'some', 'values'` which will return 'first', then `'some', 'other', 'values'` which will return 'second'.

**Comment by mikehaertl** [comment]
Hmm, maybe I'm blind but I can't find anything about argument validation for multiple calls on that page. It only mentions _return values_ for multiple calls but not _args_.

Also are you really sure, that your example works? To me the documentation says something different [here](https://docs.mockery.io/en/latest/reference/expectations.html#declaring-method-argument-expectations):

```php
$mock = \Mockery::mock('MyClass');
$mock->shouldReceive('name_of_method')
    ->with($arg1, $arg2, ...);
// or
$mock->shouldReceive('name_of_method')
    ->withArgs([$arg1, $arg2, ...]);
```
So your example should be equivalent to:

```php
// $arg1 = ['some', 'values']
// $arg2 = ['some', 'other', 'values']
$mock->with(['some', 'values'], ['some', 'other', 'values'])
```
How would `withArgs()`  know that the nested array is not a list of args for the first call in my case?

**Comment by mikehaertl** [comment]
@ghostwriter Can you confirm that mockery can be used this way?

**Comment by davedevelopment** [comment]
I think `withArgs` was added to allow the shorthand, but the example you gave in the initial post is the most clearest way to do things. That said, the last part is not necessary, mockery by default will throw an exception if it receives calls it is not expecting. 

``` php
<?php                                                                                      
                                                                                           
require "vendor/autoload.php";                                                             
                                                                                                                                                                                      
$mock = Mockery::mock();                                                                   
                                                                                           
$mock->shouldReceive('send')                                                               
    ->once()                                                                               
    ->with('some', 'values')                                                               
    ->andReturn('first');                                                                  
                                                                                           
$mock->shouldReceive('send')                                                               
    ->once()                                                                               
    ->with('some', 'other', 'values')                                                      
    ->andReturn('second');                                                                 
                                                                                           
var_dump($mock->send('some', 'values')); // string(5) "first"
var_dump($mock->send('some', 'other', 'values')); // string(6) "second"
var_dump($mock->send('other', 'other', 'values')); // throws NoMatchingExpectationException
```

As for the documentation, I guess it's not clear that you can set up as many expectation as you would like, happy to accept contributions on that front.

**Comment by mikehaertl** [comment]
@davedevelopment Ok, thanks for the clarification. Maybe I can provide a small PR.

> I think withArgs was added to allow the shorthand

I'm pretty sure that `withArgs()` is a for a different case: It can only check multiple args in **one** call, not different args in multiple calls. Please check my message above.

>  That said, the last part is not necessary, mockery by default will throw an exception if it receives calls it is not expecting.

Hmm, seems right. I can't reproduce this anymore.
