### ISSUE TITLE
Mockery spy doesn't seem to work with named arguments

### ISSUE THREAD

**Issue by ipontt** [mockery/mockery#1188]
I'm working on a PHP8.1 codebase and there's a simple test that is failing when I use named arguments. I couldn't find anything in the docs about this particular issue.  Is Mockery not compatible with named arguments?

**The test**
```php
$spy = Mockery::spy(SomeClass::class);
$param = ...

someFunction($spy, $param);

$spy->shouldHaveReceived(method: 'test', args: [$param]);
```
**The function**
```php
function someFunction(SomeClass $sc, $param) {
    ...
    $sc->test(a: $param);
    ...
}
```
**The spied class** 
```php
class SomeClass {
    public function test($a) { ... }
}
```
---

| test | function | result | error
|-|-|-|-|
|<pre>$spy->shouldHaveReceived(<br>&nbsp;&nbsp;&nbsp;&nbsp;method: 'test',<br>&nbsp;&nbsp;&nbsp;&nbsp;args: [$param]<br>);</pre>|`$sc->test($param)`|$$\textcolor{green}{\text{PASS}}$$||
|<pre>$spy->shouldHaveReceived(<br>&nbsp;&nbsp;&nbsp;&nbsp;method: 'test',<br>&nbsp;&nbsp;&nbsp;&nbsp;args: [$param]<br>);</pre>|`$sc->test(a: $param)`|$$\textcolor{red}{\text{FAIL}}$$|`InvalidCountException ... should be called at least 1  times but callled 0 times`|
|<pre>$spy->shouldHaveReceived(<br>&nbsp;&nbsp;&nbsp;&nbsp;method: 'test',<br>&nbsp;&nbsp;&nbsp;&nbsp;args: ['a' => $param]<br>);</pre>|`$sc->test($param)`|$$\textcolor{red}{\text{FAIL}}$$|`ErrorException Undefined array key 0`| 
|<pre>$spy->shouldHaveReceived(<br>&nbsp;&nbsp;&nbsp;&nbsp;method: 'test',<br>&nbsp;&nbsp;&nbsp;&nbsp;args: ['a' => $param]<br>);</pre>|`$sc->test(a: $param)`|$$\textcolor{red}{\text{FAIL}}$$|`ErrorException Undefined array key 0`|

**Comment by daverdalas** [comment]
Any update on this?

**Comment by nevmerzhitsky** [comment]
It's a huge inconvenience that all `with()/withArgs()` with closure- or static- syntax does not allow to match a call with named arguments unboxing (like `$sut->foo(...$params)` where `$params` is an associative array). I things it's related to this ticket.
