### ISSUE TITLE
Failed to mock method for the Proxied partial

### ISSUE THREAD

**Issue by yankewei** [mockery/mockery#1201]
```php
final class Foo
{
    public function foo() {
        return 123;
    }

    public function bar() {
        return $this->foo();
    }
}

// Tests
public function testFoo()
{
    $foo = new Foo();
    $mock = \Mockery::mock($foo);
    $mock->shouldReceive('foo')->andReturn(456);
    self::assertSame(456,$mock->bar());
}
```
I got an error message `Failed asserting that 123 is identical to 456.`

### version
- php: 8.1
- phpunit: 9.5.26
- mockery: 1.5.1

**Comment by swichers** [comment]
Old issue, but for anyone dealing with this:

Unfortunately, this behavior is expected. The mocked object will only intercept direct calls to `foo`. Anything that's calling it internally also has to be mocked.

#77

**Comment by yankewei** [comment]
> Old issue, but for anyone dealing with this:
> 
> Unfortunately, this behavior is expected. The mocked object will only intercept direct calls to `foo`. Anything that's calling it internally also has to be mocked.
> 
> #77

Thank you for the information. I believe this issue can be closed.
