### ISSUE TITLE
[Question] Mocks already loaded in coverage phpunit task.

### ISSUE THREAD

**Issue by ciltocruz** [mockery/mockery#1202]
I have a problem that I don't know if it's a problem or it's normal.

I have a PHP class with static methods that I want to mock with Mockery to check that the code executed when an exception is thrown works.

The test works fine and does what I ask of it (The code tests the handling of an exception).
` ✔ Should throw exception [90.20 ms]`

But when I want to pass the coverage with phpunit this happens:

```
Generating code coverage report in HTML format ...
Script phpunit --testdox --configuration ../phpunit.xml ../tests handling the test:coverage event returned with error code 255
Fatal error: Cannot declare class BackBase\Tools\Email\EmailManager, because the name is already in use in
```

I have seen in a thousand places that if I add
```
      * @runInSeparateProcess
      * @preserveGlobalState disable
```
in my test, everything is fixed.

But the times that each test takes increase a lot.
`✔ Should throw exception [3331.97 ms]`

I have many tests of this style and the test time increases exponentially.

Does this have a solution? I am doing something wrong?
If more information is needed, ask me.

Thank you!

**Comment by ghostwriter** [comment]
Hey @ciltocruz,

The documentation recommends that we use aliases for the purpose of mocking public static methods.

> ### [Mocking Public Static Methods](http://docs.mockery.io/en/latest/reference/public_static_properties.html)
> Static methods are not called on real objects, so normal mock objects can’t mock them. Mockery supports class aliased mocks, mocks representing a class name which would normally be loaded (via autoloading or a require statement) in the system under test. These aliases block that loading (unless via a require statement - so please use autoloading!) and allow Mockery to intercept static method calls and add expectations for them.

> ### [Aliasing](http://docs.mockery.io/en/latest/reference/creating_test_doubles.html#creating-test-doubles-aliasing) 
> Prefixing the valid name of a class (which is NOT currently loaded) with “alias:” will generate an “alias mock”. Alias mocks create a class alias with the given classname to stdClass and are generally used to enable the mocking of public static methods. Expectations set on the new mock object which refer to static methods will be used by all static calls to this class.

`$mock = \Mockery::mock('alias:' . EmailManager::class);`

**Comment by ciltocruz** [comment]
Yes. That's what I have in my code.

```
        ... 
        $emailManagerMock = Mockery::mock('alias:' . EmailManager::class);
        ...
```
But if I don't code:

```
  * @runInSeparateProcess
  * @preserveGlobalState disable
```

then, when phpunit tries to report coverage, it gives the above error.
`Fatal error: Cannot declare class BackBase\Tools\Email\EmailManager, because the name is already in use [...]`

I don't know if there is any way to create a mock of a class making the program believe that it is that class, but without being it, so that when phpunit passes the coverage it does not detect that that class has already been loaded.

Or if there is a way to remove a previously loaded class (and no, Mockery::close() doesn't seem to do this).

I don't know if it would work, but maybe if there was a way to tell the coverage: "Hey, friend, start from 0 to load the classes you need".
I don't know if that would make phpunit lose "the coverage that the tests have passed".

Thanks.

**Comment by ghostwriter** [comment]
After some research, I was able to find an article [Mocking static-methods with mockery](https://blog.gougousis.net/mocking-static-methods-with-mockery/) on how to get around this using `Stubs` with `named mocks`.

Outside of this article, there is a [stackoverflow question](https://stackoverflow.com/questions/66823418/mock-a-classs-constant-and-method-with-mockery-and-phpunit) with a similar example.

**Comment by ciltocruz** [comment]
Hello.

That doesn't seem to be a solution for me...
It seems focused on classes with constants.

As much as I read documentation... Mockery insists over and over again that it is impossible to have 2 instances of the same object loaded even with different names unless they are running in different processes.

```
Using alias/instance mocks across more than one test will generate a fatal error since we can’t have two classes of the same name. To avoid this, run each test of this kind in a separate PHP process (which is supported out of the box by both PHPUnit and PHPT).
```

```
We can only create a named mock once, any subsequent calls to namedMock, with different arguments are likely to cause exceptions.
```

I don't know what else I can try...

**Comment by jrfnl** [comment]
As you mention that the issue only happens when running code coverage, I'm wondering if warming the PHPUnit cache would help in your case (it did for one of the libraries I maintain).

Would you happen to be using PHPUnit 9.3+ ? If so, see if running the tests with code coverage like this makes a difference:
```bash
phpunit --coverage-cache ./build/phpunit-cache --warm-coverage-cache
phpunit --coverage-cache ./build/phpunit-cache
```

**Comment by ciltocruz** [comment]
> As you mention that the issue only happens when running code coverage, I'm wondering if warming the PHPUnit cache would help in your case (it did for one of the libraries I maintain).
> 
> Would you happen to be using PHPUnit 9.3.4+ ? If so, see if running the tests with code coverage like this makes a difference:
> 
> ```shell
> phpunit --coverage-cache ./build/phpunit-cache --warm-coverage-cache
> phpunit --coverage-cache ./build/phpunit-cache
> ```
> 
> (and yes, you need to run both commands in that case, the first warms the cache, the second runs the tests using the cache)

Right now I can't test this.

I've undone all my static methods so I can do more robust testing with better dependency management.
