### ISSUE TITLE
Broken code generated for intersection return type

### ISSUE THREAD

**Issue by derrabus** [mockery/mockery#1207]
I have an interface with a native intersection return type, e.g.

```php
interface Foo
{
    public function getCollection(): \Traversable&\Countable;
}
```

If I attempt to create a mock for it, Mockery generates code with a union return type (`\Traversable|\Countable`). Since that type is not covariant to the original return type, PHP exits with a fatal error.

```
Fatal error: Declaration of Mockery_0_Foo::getCollection(): Traversable|Countable must be compatible with Foo::getCollection(): Traversable&Countable
```

**Comment by tm1000** [comment]
Getting the same.
