### ISSUE TITLE
Mocking undefined methods with PHP 8.2 fails

### ISSUE THREAD

**Issue by rneudorf-godaddy** [mockery/mockery#1209]
PHP 8.2 deprecates dynamic properties: https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties

When Mockery creates a mock of an undefined method, the mock is empty, it does not have properties or methods. 

Under PHP 8.2 the following test will fail and throw an exception with the message "Creation of dynamic property Mockery_0__UndefinedClass::$foo is deprecated"

```php
namespace test\PHP82;

use Mockery\Adapter\Phpunit\MockeryTestCase;

class Php82LanguageFeaturesTest extends MockeryTestCase
{

    public function testCanMockUndefinedClasses()
    {
        $class = mock('UndefinedClass');

        $class->foo = 'bar';

        $this->assertSame('bar', $class->foo);
    }
}
```

The simplest fix for this issue would be to give undefined method mocks the `#[\AllowDynamicProperties]` attribute.

**Comment by ghostwriter** [comment]
Resolved via #1210
