### ISSUE TITLE
Performance issues with PHPUnit 10

### ISSUE THREAD

**Issue by usox** [mockery/mockery#1215]
Hi there :wave: 

PHPUnit 10 was recently released and brings a revised event system. Within this event system, among other things, meta information about used objects from expectations are kept, so that the test runner can evaluate them after completion of the tests.
Among other things, Mockery's mock objects are serialized and stored in memory. Due to the fact that a mock object can contain a lot of information, the amount of data grows quite fast, which makes the tests very slow and quickly hits the memory limit.

Trigger can be e.g. an `assertSame`, which uses the `IsIdentical` class in PHPUnit and serializes the data by means of `IsIdentical::toString` from `sebastianbergmann/exporter`. This also serializes the protected properties of the `Mock` class of Mockery, (`$_mockery_expectations`, ...) which could in part contain large structures/object graphs and ultimately lead to said problem.

An example from one of my projects:

PHPUnit 9 + Mockery
```
Time: 00:00.768, Memory: 56.00 MB

OK (440 tests, 1727 assertions)
```

PHPUnit 10 + Mockery
```
Time: 00:02.994, Memory: 183.57 MB

OK (440 tests, 1727 assertions)
```

I created a q+d repo which contains simple testcode, a stacktrace and the event payload within phpunit.
https://github.com/usox/mockery-performance-issue

See also:
- Recent related phpunit issue:  sebastianbergmann/phpunit/issues/5183
- Exporter which causes the serialization https://github.com/sebastianbergmann/exporter/blob/988f65481f95f3080d7b412d4fc863b7d09c36b2/src/Exporter.php#L63

**Comment by davedevelopment** [comment]
Thank you for the detail report, great work :+1: 

Really annoying find though! First thing I noticed was PHPUnit 10 seemed slower to me anyway. Changing your example test to:

``` php
<?php

use PHPUnit\Framework\TestCase;

class SomeClassTest extends TestCase
{
    private SomeOtherClass $some_other_class;

    private SomeClass $subject;

    protected function setUp(): void
    {
        $this->some_other_class = new SomeOtherClass;

        $this->subject = new SomeClass(
            $this->some_other_class
        );
    }

    public function numbers(): array
    {
        return array_fill(0, 1000, []);
    }

    /**
     * @dataProvider numbers
     */
    public function testDoSomethingDoes(): void
    {

        static::assertSame(0, 0);
    }
}
```

```
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.

<snip>

Time: 00:00.110, Memory: 6.00 MB

OK (1000 tests, 1000 assertions)
```

```
PHPUnit 10.0.11 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.0
Configuration: /home/davem/src/mockery-performance-issue/phpunit.xml.dist

<snip>

Time: 00:00.456, Memory: 10.00 MB

OK (1000 tests, 1000 assertions)
```

Quite a difference. Pretty sure we can do something about the memory, e.g. `Mockery\MockDefinition::$code` probably won't need to stay around unless you want to debug the generation, which in turn will help with the string comparison. We will struggle to shave off much of that execution time. If the exporter is serialising recursively, it will have to walk the tree every time and while we can look for unnecessary references, we'll still struggle to do anything meaningful.

**Comment by davedevelopment** [comment]
A quick look suggests that Mockery would 30x the number of calls to the exporter's serialise function.

**Comment by usox** [comment]
So for me, runtime is secondary to memory consumption - though the former is of course influenced by the latter in my observations.

Two things come to mind now:

1. We can ask Sebastian Bergmann if there is a way to signal the exporter not to serialize certain objects in this way. There is already a filter for SplFileObject and exceptions, maybe something like this could be made controllable via PHP attributes. But my gut feeling tells me that this doesn't have much chance of success.

2. Without having deeply studied the Mockery internals now: Is there perhaps a way to remove the properties from the mock object - e.g. into some kind of static registry?

I have a project here with about 25k tests and 110k assertions, which is almost entirely based on Mockery - so any change in performance is immediately noticeable, making it ideal for testing (phpunit9: Time: 00:46.101, Memory: 2.36 GB; phpunit10: Does not finish :smile:  ). If I can help you in that regard, let me know.

**Comment by usox** [comment]
> Really annoying find though! First thing I noticed was PHPUnit 10 seemed slower to me anyway.

For the record: I added this test to my testcase, although it's not mockery related.

**Comment by davedevelopment** [comment]
Agreed on (1), it would be a nice to have, but we can't rely on them changing anything. 

Option 2 sounds more plausible, we essentially have a static registry for the main global `Mockery\Container` that we use to handle things like `Mockery::close()`.  It's been a while, but it probably would spoil some of the mechanics to use that directly. I think `Mockery::$container` holds a static reference to a global `Mockery\Container`, but everything below that e.g the Mock Objects, acts nicely as though you can have as many instances of `Mockery\Container` as you need or see fit etc. Perhaps we keep the central global, but maintain a static registry as well, that should allow for some wiggle room. 

Another thought I had, perhaps we can do something with WeakReferences? I doubt they'd be serialised in the same way and it might give us a half way house, rather than offloading to a registry.

**Comment by davedevelopment** [comment]
Might be something in the WeakReferences, though I don't know if we're opening up a can of worms there. 

Current:

```
Time: 00:02.156, Memory: 14.00 MB
```

With `Mockery\Mock::$_mockery_container` held as a weak reference.

```
Time: 00:01.190, Memory: 14.00 MB
```

**Comment by usox** [comment]
> Another thought I had, perhaps we can do something with WeakReferences? I doubt they'd be serialised in the same way and it might give us a half way house, rather than offloading to a registry.

Ah interesting, I didn't think of WeakReference until now. That could be a way...

And if we open a can of worms, we'll just have to go fishing :)

**Comment by davedevelopment** [comment]
Now trying to see this as an opportunity...

We currently store all kinds of internal stuff on a Mock Object, using attributes like `Mockery\Mock::$_mockery_container`. Perhaps we bundle all of those up in to one `Mockery\MockInternals` class, then let the `Mockery\Mock` have a weak reference to that. Even if the `WeakReference` stuff turns out to be non feasible, at least we then have a tidier set of internals and only one reference to deal with via an alternative method. 

``` php

namespace Mockery;

class MockInternals
{
    private Container $container;
    private array $expectations;
    /** etc */
}

class Mock
{
    // protected $_mockery_container;
    // protected $_mockery_expectations;

    /** @var WeakReference<MockInternals> */
    protected WeakReference $_mockInternals;
}

**Comment by davedevelopment** [comment]
Started a branch to try things out 8bf50e9823

**Comment by usox** [comment]
> We currently store all kinds of internal stuff on a Mock Object, using attributes like `Mockery\Mock::$_mockery_container`. Perhaps we bundle all of those up in to one `Mockery\MockInternals` class, then let the `Mockery\Mock` have a weak reference to that. Even if the `WeakReference` stuff turns out to be non feasible, at least we then have a tidier set of internals and only one reference to deal with via an alternative method.

`_mockery_container` and `_mockery_expectations` are definitely the most interesting, especially `_mockery_container` as that one apparently contains the source code of generated mock objects.

**Comment by davedevelopment** [comment]
My experiments of making the `MockInternals` instance a weak reference have not been successful, it seems the garbage collection works remarkably well...

**Comment by davedevelopment** [comment]
As far as I can tell, the container is only used for globally ordered expectations (`shouldReceive()->foo()->ordered('foo')->globally()`) and instance mocks. I consider these both "bells and whistles" type features, where I'd probably be happy to compromise on the quality and use a few globals/static calls to facilitate. 

The expectations would be more difficult to avoid. 

There is an outstanding issue sebastianbergmann/exporter#18, where Sebastian says he would accept a PR to somehow ignore some properties etc. Not sure of a decent way of doing that.

**Comment by usox** [comment]
If the exporter would provide a generic way for blacklisting, that would be the best solution for everyone. Not only would future changes/adaptations to the exporter be tested on it, but third parties could also benefit from it.
I think I'll give it a try and build a PR - at the moment my favorite would be a class attribute provided by the exporter.
However, the current version of the exporter requires at least PHP 8.1 - so this could cause backwards compatibility problems.

**Comment by davedevelopment** [comment]
I think an attribute would be a very clean solution, but would probably slow the exporter down even further for every other type of object? I assume the only way to grab the attributes is with reflection. 

Like the way Prophecy do it in their [copy pasted version](https://github.com/phpspec/prophecy/blob/5c324f4951aca87a2de61b7903b75126516b6386/src/Prophecy/Util/ExportUtil.php#L184), it might need some sort of registry based solution for performance:

``` php
Exporter::registerTypeExporter(\Mockery\Container::class, fn($v) => " (** Mockery Container **)");
```

**Comment by usox** [comment]
I will try both variants and benchmark them. I'm afraid such a registry would not be accepted by the exporter and/or at worst create new problems...

**Comment by usox** [comment]
Ok, after some testing I have now suggested the solution with the registry. My large test suite works, the execution takes only minimally longer than with PHPUnit 9.

Interestingly, the performance difference between using one attribute+reflection and instanceOf checks was completely negligible

**Comment by davedevelopment** [comment]
My advice would be to work around the problem yourself. I think PHPUnit probably puts `final` on everything, so you might need to come up with your own names for things, but something like `CustomTestCase::assertSameQuick`   with a custom `Constraint` that doesn't use the exporter should get you back running a little quicker.

**Comment by davedevelopment** [comment]
Either that or fork the exporter, it's small enough to maintain your own fork etc.

**Comment by usox** [comment]
> I think PHPUnit probably puts `final` on everything
Yepp, that's already happening.

I'm not surprised by the result now, even though I still think that comparing object lists is a valid use case (And I'm talking about "real" objects, not test doubles).
Anyway, this should not be your problem. Thanks for your time and suggested solutions - I'll be fine. And thank you for maintaining Mockery.

**Comment by davedevelopment** [comment]
> I'm not surprised by the result now, even though I still think that comparing object lists is a valid use case (And I'm talking about "real" objects, not test doubles).

Agreed that it's valid and with the amount of tests and assertions you have, even relatively simple object graphs will see performance hits. 

I'll close this for now, but I might pursue moving all of the mockery internals in to a wrapper, it makes sense and should make for easier maintenance going forward.
