### ISSUE TITLE
Request for `2.0.x` branch

### ISSUE THREAD

**Issue by ghostwriter** [mockery/mockery#1223]
Hey @davedevelopment, (and contributors)

I'm reaching out to request the creation of a `2.0.x` branch. 

> (Semver Branch Name Format: `{major}.{minor}.x`  | eg. `0.1.x`, `1.0.x`)
 
As a contributor to the project, I believe that having a new branch would enable us to submit multiple concise Pull Requests and make improvements to the codebase without affecting the stability of the `master` branch.

> Also, I would like to suggest dropping the use of `"master"` terminology going forward.

If possible, could you please create the `2.0.x` branch at your earliest convenience?

Thank you.

**Comment by davedevelopment** [comment]
I can go one better I think, I've just given you the "Write" role, feel free to proceed with the new branch.

Happy to proceed on the "master" terminology as well, though I think that might need more privileges? Also not sure on the repercussions for packagist.org etc, I've not done it on any projects yet.

**Comment by ghostwriter** [comment]
Thank you for granting me the appropriate role.

I've created two new branches from the current default branch.

- [x] `1.5.x` (`1.5.*` tags created on this branch)
- [x] `2.0.x` (`2.0.*` tags created on this branch)

Regarding the "master" terminology for the default branch, I do not have the privilege to change that.

As for the implications on packagist.org, it should not have any impact as long as the package's configuration is set up to automatically updated to reflect the new branch name. We can also add branch aliases to the `composer.json` if needed.

I'll open a separate issue regarding `Changing and maintaining the default branch`, and `branch and tag protection` to help ensure that changes are properly reviewed and approved before being merged into the target branches, safeguarding the stability and security of the codebase.

Thank you again for your help.

**Comment by davedevelopment** [comment]
Just a note to say thank you for the work you've put in this week and sorry I've not got around to going through everything, I've pencilled in time for it all on Monday morning.
