### ISSUE TITLE
Enable and configure branch protection

### ISSUE THREAD

**Issue by ghostwriter** [mockery/mockery#1228]
This can help prevent accidental or unauthorized changes to important branches.

To set up [Branch protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule) on GitHub, follow these steps:

1. Navigate to https://github.com/mockery/mockery/settings/branch_protection_rules/new
2. Set the "`Branch name pattern`" using this pattern "`*.*.x`" and configure the options for the rule.
 - You can choose to require pull request reviews before merging, enforce CI status checks, and prevent force pushes.
 - You can also add additional rules such as requiring a certain number of approving reviews or specific team members to review changes.
3. Click "Create" to save the branch protection rule.

Once the branch and tag protection rules are in place, any attempts to merge changes into the protected branches will be subject to the configured requirements.

**Comment by ghostwriter** [comment]
Hey @davedevelopment, 

I do not have the permission required to complete this task.

I'll need your help with this and #1229, at your convenience. Thanks

**Comment by davedevelopment** [comment]
Done, with the most basic of options:

- Require a pull request before merging

We can tighten them up as we go along.

**Comment by ghostwriter** [comment]
Sounds good, Thanks.
