### ISSUE TITLE
Tag could not be created

### ISSUE THREAD

**Issue by ghostwriter** [mockery/mockery#1247]
Pre-receive hooks failed.
> protected tag '1.6.0' check failed:
>  You're not authorized to create a tag

Created a draft https://github.com/mockery/mockery/releases/edit/untagged-f99efa3de67d6c09736d

You can visit the draft URL and click `Publish release` after reviewing.

P.S. Please rename the default branch to `main`. (not authorized to rename default branch)

**Comment by ghostwriter** [comment]
After releasing `1.6.0`, the next step is to sync up the changes in the `1.6.x` branch into `2.0.x`.

- [ ] open a pull request & merge `1.6.x` into `2.0.x`

**Comment by davedevelopment** [comment]
Sorry for the delay...

**Comment by davedevelopment** [comment]
And I have renamed the master branch to main

**Comment by davedevelopment** [comment]
People will need to https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes

**Comment by ghostwriter** [comment]
No worries, and thank you.

Related: #1273
