### ISSUE TITLE
I need to mock a php function

### ISSUE THREAD

**Issue by MrEko** [mockery/mockery#1292]
have my class that inside it's method it uses php function:

`shell_exec($cmd)`
now I want to override it's implementations so I could mock and test my class, somebody here done something like this?

**Comment by ghostwriter** [comment]
Hey @MrEko, 

I would recommend using a wrapper class for mocking PHP functions.

Here's an example of a wrapper class for `shell_exec()` that allows for easy testing:

```php
class Shell{
  public function execute($command): string
  {
    return shell_exec($command);
  }
}
```

```php
$shell = new Shell();
$output = $shell->execute('echo "#BLM"');
echo $output;

```

```
class ShellTest extends TestCase
{
    public function testExecute()
    {
        $shell = new Shell();
        $command = 'echo "#BLM"';

        $result = $shell->execute($command);
        $this->assertSame('#BLM', $result);
    }
}
```

The 2nd option relies overwriting functions by creating functions with the same name and signature, **in the same namespace as the class calling the function**.

```

namespace My\Namespace;

function shell_exec(string $command): string|false|null
{
  return null; // eg. always return null
}

class NullShell{
  public function execute($command): null
  {
    return shell_exec($command);
  }
}

```

This functionality has been implemented by this library https://github.com/php-mock/php-mock-mockery

Let us know if that's helpful, 

Please be sure to mark this issue as "resolved" by closing it.
