### ISSUE TITLE
Bugfix release for breaking changes ???

### ISSUE THREAD

**Issue by ruester** [mockery/mockery#1306]
### Mockery Version

1.6.3

### PHP Version

PHP 8.2

### Issue Description

You (the maintainers of mockery) just released version 1.6.3 as a bugfix release for the 1.6 version. In this release you moved files to different locations (`src` directory instead of `library`). So how should that be a bugfix release if you are doing breaking changes???

This is a breaking change: https://github.com/mockery/mockery/pull/1290

### Expected Behavior

This should have been a major release (so version 2.x, but that seem to be released already) if you change the structure of the library.
Other libraries depend on the files that were moved in this release.
I would suggest to release another bugfix version which reverts this change as this is not the way semantic versioning is intended to be used.

**Comment by ghostwriter** [comment]
Hey @ruester,

It was indeed my mistake, and I apologize for any inconvenience caused.

I have taken immediate action to rectify the issue.

The necessary changes have been made as you suggested in #1307.

Thank you once again for bringing this to my attention.

**Comment by ruester** [comment]
Many thanks for fixing it :slightly_smiling_face: :+1:
