### ISSUE TITLE
Interpreting iterable|object as array|Traversable|object results in a runtime error.

### ISSUE THREAD

**Issue by fuwasegu** [mockery/mockery#1311]
# Mockery Version

1.6.4

# PHP Version

PHP 8.2

# Issue Description

## Introduction
This bug, as can be seen in the following php-src issue, is not solely a problem with Mockery but involves a bug in PHP itself. Therefore, if this project has made the decision to adhere to the PHP implementation, it may be acceptable to exclude this issue from being treated as a bug.

https://github.com/php/php-src/issues/11797

## Summary
In Mockery, the ReflectionClass is used to analyze the class to be mocked. When copying the methods of the class to be mocked to the Mock class, the type of the method's arguments are analyzed and outputted using ReflectionProperty. However, the output result of iterable changes depending on whether the version of PHP in the execution environment is 8.2 or not.

PHP 8.1 and below ... iterable
PHP 8.2 ... Traversable|array
This is because iterable, which was a built-in pseudo-type, has become a "type alias" that is converted to array|Traversable at compile time from PHP 8.2.

Reference: https://www.php.net/manual/en/language.types.iterable.php

While there is no problem with this fact itself, when Mockery analyzes the method using Reflection for a class method implemented with the argument type as iterable|object, the type of the method implemented on the mock class side becomes Traversable|object|array. This results in the following error because Traversable|object is redundant.

```
Type Traversable|object|array contains both object and a class type, which is redundant
```

Therefore, you cannot run the test with a Fatal Error when eval() in Mockery's EvalLoader.

If this bug is to be addressed in Mockery, I believe that when the argument type contains array|Traversable, it will need to be replaced with iterable or similar corrections."

# Steps to Reproduce

_No response_

# Expected Behavior

_No response_

# Actual Behavior

_No response_

# Exception or Error

_No response_

**Comment by ghostwriter** [comment]
Thank you for raising this issue, I appreciate your patience.

We will keep this issue open and monitor the progress of https://github.com/php/php-src/issues/11797.

Once there are any developments or results, we will provide an update here.

If you have any further questions or concerns, please let us know.

**Comment by fuwasegu** [comment]
Thank you for your replying!

it seems that It was closed as "not planned", wasn't it?

In this case, is it correctly to support this bug at library side ...?

**Comment by ghostwriter** [comment]
Yes, we can add a guard to `"sanitize"`  the types if it contains `iterable`.

Thanks for update 👍🏾
