### ISSUE TITLE
Factory methods for `IsEqual` and `IsSame` matchers

### ISSUE THREAD

**Issue by ghostwriter** [mockery/mockery#1335]
Would a PR adding a factory method for new `IsEqual` and `IsSame` matchers to `Mockery` be welcomed, similar to how `Mockery::any()` exist? i.e.
 
```php
class Mockery {
    public static function equal($other) {
        return new IsEqual($other);
    }
}
```

_Originally posted by @oprypkhantc in https://github.com/mockery/mockery/issues/1276#issuecomment-1806839656_

**Comment by oprypkhantc** [comment]
Awesome, thank you :)
