### ISSUE TITLE
support for PHPUnit constraints

### ISSUE THREAD

**Issue by ghostwriter** [mockery/mockery#1337]
Now that Hamcrest support is not official, would a PR adding support for PHPUnit constraints be welcomed? Sure, Mockery has some built-in matchers, but PHPUnit has a lot more to offer: https://github.com/sebastianbergmann/phpunit/tree/main/src/Framework/Constraint

_Originally posted by @oprypkhantc in https://github.com/mockery/mockery/issues/1006#issuecomment-1806840998_

**Comment by oprypkhantc** [comment]
Thank you. Do you want me to make a PR or will you take over?

**Comment by ghostwriter** [comment]
Sure, I would love to collaborate with you on this.

If you have something in mind, please send a pull request and we will review it together.

If you have any questions please feel free to ask.
