### ISSUE TITLE
[New feature] Running code after mock method was called

### ISSUE THREAD

**Issue by szymonmil** [mockery/mockery#1345]
Hi,
I have following case:
In functionality I am testing, there are 2 dependencies - repository and CQRS command. Repository has fake implementation for testing purpose (in memory repository), and CQRS command is mocked. Algorithm of program which is testing is following:
1. Fetch record from repository
2. If record doesn't exist - call CQRS Command which will add that record
3. Fetch record again (now record is present because we called CQRS Command)

And i want to test that case. So I need to add record to my fake repository, after CQRS Command was called. In my opinion, the best solution will be adding method to Mockery such as `afterCall(Callback)` which will run provided callback after mocked method was called. And in my scenario, I will provide there callback with adding record to fake repository.

What do you think about that solution? Is it generic enough to introduce such feature in Mockery?
Thanks

**Comment by ghostwriter** [comment]
Hey @szymonmil,

I believe we can do that with the `andReturnUsing()` method which accepts one or more closure:

```php
final class FakeRepository {
    private $records = [];
    public function get(int $id): ?string
    {
        return $this->records[$id] ?? null;
    }
    public function add(int $id, string $record) {
        $this->records[$id] = $record;
    }
}

final class CQRSCommandTest extends \PHPUnit\Framework\TestCase {
    use MockeryPHPUnitIntegration;

    public function testFetchRecord(): void
    {
        // Create a mock for the CQRS command
        $cqrsCommand = \Mockery::mock(CQRSCommandInterface::class);

        // Create an instance of the fake repository
        $repository = new FakeRepository();
        
        $id = 42;
        $returnValue = 'New record';

        // Set up the expectations for the mock CQRS command
        $cqrsCommand->shouldReceive('execute')->once()
            ->andReturnUsing(static function() use ($repository, $id, $returnValue) {               
                // Add a record to the repository when the CQRS command is called
                $repository->add($id, $returnValue);

                // return the desired value
                return $returnValue;
            });

        // Fetch record from the repository
        $record = $repository->get($id);

        // Assert that the record is initially not present
        self::assertNull($record);

        // Call the CQRS command, which should add the record to the repository
        $cqrsCommand->execute();

        // Fetch record again
        $record = $repository->get($id);

        // Assert that the record is now present
        self::assertSame($returnValue, $record);
    }
}

```

Let me know if this is enough for your requirements.

**Comment by szymonmil** [comment]
Thank you a lot, that's exactly what I was looking for :)
