### ISSUE TITLE
no usefull error message in case an excpetion occurs while generating a half usefull error message ;-)

### ISSUE THREAD

**Issue by mschirmacher** [mockery/mockery#153]
In case the tesed code calls a method on a mock without matching arguments this check fails: https://github.com/padraic/mockery/blob/master/library/Mockery/ExpectationDirector.php#L92 
so finally \Mockery::formatObjects($args) will be called in https://github.com/padraic/mockery/blob/master/library/Mockery/ExpectationDirector.php#L100

Our problem was, that the formatObjects resulted in an expection rendering the intended error handling useless. This situation should be handled properly

**Comment by robertbasic** [comment]
This shouldn't happen since #732 since the code that was responsible for this behaviour was removed, so I'm going to close this issue.

If you still have a problem with this, please open a new issue. Thank you!
