### ISSUE TITLE
Unable to mock constants of an instance mock

### ISSUE THREAD

**Issue by david0** [mockery/mockery#172]
Hi, 
i need instance mock to test some legacy code.
The class that I want to test has a hard-coded dependency and looks as follows:

```
class Temperature {
  function read() {
    $sensor = new MultiSensor();
    return $sensor->getValue(MultiSensor::PARA_TEMPERATURE);
  }
}
```

While it is possible to mock the call to `getValue`, it is not possible to mock the constant `PARA_TEMPERATURE`:

```
$mock=\Mockery::mock('overload:MultiSensor');
$mock->shouldReceive('getValue')->andReturn(15);

$temp = new Temperature();
$this->assertEquals(15,$temp->read());
```

leads to:

```
Fatal error: Undefined class constant 'PARA_TEMPERATURE'
```

Because of this, it think it would make sense to add a function or constructor parameter to set the constants of the generated instance mock.

**Comment by ramsey** [comment]
Just ran across this same issue myself. I'll try to refactor around it, but it would be nice to support partial mocks for overloaded classes (if that's possible).

**Comment by wanzirong** [comment]
is this feature added to Mockery ? It's now 2016...

**Comment by robertbasic** [comment]
I believe doing partials of instance mocks is not something we'll support in Mockery. Closing this one as noone provided a pull request for almost 4 years now.

If this is a feature you wish to have, please open a new issue and a pull request implementing the feature.

Thank you!
