### ISSUE TITLE
Test traits

### ISSUE THREAD

**Issue by ernestoalejo** [mockery/mockery#200]
There's currently no way to mock traits with Mockery.

[For reference]
http://sebastian-bergmann.de/archives/906-Testing-Traits.html

**Comment by BallisticPain** [comment]
Maybe even 2015?

**Comment by davedevelopment** [comment]
Pull requests welcome :)

**Comment by Bilge** [comment]
I think we could put this on the roadmap for 2025.

**Comment by BallisticPain** [comment]
LOL @Bilge 
Yes @davedevelopment I assumed so. Unfortunately at this time I don't have personal time to work on this and in my professional time I was able to find a satisfactory way to test a trait. This is where I got the idea on how I was going to do it: http://carlosbuenosvinos.com/php-trait-testing/

Thanks!

**Comment by Zizaco** [comment]
:+1:

**Comment by Bilge** [comment]
Friendly reminder that it is now 2016.

**Comment by agwidarsito** [comment]
+1

**Comment by vokke-daniel** [comment]
+1,000,000

**Comment by rewchelsea** [comment]
+1,000,001

**Comment by davedevelopment** [comment]
He all, looking for feedback on #685

**Comment by robertbasic** [comment]
As #685 was merged, I'm going to close this issue.
