### ISSUE TITLE
Methods that return by reference un-mockable.

### ISSUE THREAD

**Issue by MarcherTech** [mockery/mockery#207]
```
<?php

use \Mockery as m;

class MockeryReturnByRefMethodTest extends \PHPUnit_Framework_TestCase {

    public function tearDown() {
        m::close();
    }

    public function testMethodsReturningByReferenceDoesNotErrorOut() {
        $mock = m::mock('MockeryTest_ReturnByRefMethod');
        $mock->shouldReceive('get')->andReturn(array('foo' => 'bar'));
        $test =& $mock->get();
        $test = array();
        $this->assertSame($test, array());
    }

    public function testMethodsReturningByReferenceDoesNotErrorOutAgain() {
        $mock = m::mock('MockeryTest_ReturnByRefMethod');
        $args = array('foo' => 'bar');
        $test =& $args;
        $mock->shouldReceive('get')->andReturn($test);
        $_test =& $mock->get();
        $_test = array();
        $this->assertSame($_test, array());
    }

}
```

Similar to https://github.com/padraic/mockery/pull/135
Unit Test showing the issue.... I have fought for days with this, either there is a documentation issue or it is simply not possible to mock a dependency that does something like this:

```
class MockeryTest_ReturnByRefMethod {

    protected $data = array('foo' => 'bar');

    public function &get() {
        return $this->data;
    }

}
```

Due to a 'Only variables should be assigned by reference' error.
A shouldRecieveByReference method would work if the need to differentiate directly in the mocking is required. Using &get in shouldRecieve simply states the method 'get' is not defined on the mock object when called.
\Mockery::getConfiguration()->setInternalClassMethodParamMap refuses to recognize the call to the method with & in a method name as well.
 I would think if the method name is prefixed with & it should be recognized as by-reference method return, not to be confused with by-reference parameter return.
Changing the code itself doing this is not an option at this time, any solution to mock these kinds of methods welcome.

**Comment by robertbasic** [comment]
As it lingers for almost 4 years, I'm closing it as a won't fix.

If this is still something you have issue with, please open a new issue with a small, reproducible test case.

Thanks!
