### ISSUE TITLE
Assertion count should not include stubs

### ISSUE THREAD

**Issue by davedevelopment** [mockery/mockery#249]
Currently, stub expectations (zeroOrMoreTimes) are counted as assertions when using the PHPUnit plugin, I'd vote to exclude them and only count actual count expectations.

Thoughts?

**Comment by padraic** [comment]
Just checking - we all agreed to implement or has it been implemented?

**Comment by aik099** [comment]
This was imlemented in https://github.com/padraic/mockery/blob/master/library/Mockery/Adapter/Phpunit/MockeryTestCase.php because due PHPUnit test listener limitation assertion count updater code had no effect.

**Comment by davedevelopment** [comment]
@aik099 I don't think it was. This is specifically about not counting stubbed methods and only counting actual mock expectations. So

```
$first->shouldReceive("dave")->andReturn("foo");
$first->shouldReceive("dave1")->andReturn("foo");
$first->shouldReceive("dave2")->andReturn("foo");
$second->shouldReceive("doSomething")->once();
```

Would record one assertion.

@padraic I think we've all agreed, but not been implemented. Will try and get on to it this week.

**Comment by robertbasic** [comment]
@davedevelopment are we still interested in this? If so, I think I can make a PR for it.

**Comment by robertbasic** [comment]
Closing as there wasn't much feedback on it for quite some time.
