### ISSUE TITLE
Allow setting exception message for `InvalidCountException` exception

### ISSUE THREAD

**Issue by aik099** [mockery/mockery#264]
I like use `->once()`, `->twice()`, `->times()` and other methods that validate how much times a method should be called a lot.

The error I'm getting on failed expectation usually looks like this: `Method stop() from Mockery_2_Behat_Mink_Session should be called`. It looks good for a generic error, but it doesn't really explain what's wrong with calling code.

I'm proposing to develop a way to pass optional exception message to be used instead of generic one if an expectation fails. Like with `->assertEquals(..., ..., $message)` - you can pass a message if you wish, but when not passed the generic is used.

**Comment by padraic** [comment]
Anyone have any additional thoughts on this? If someone throws a PR at it, I wouldn't be against either API option.

**Comment by ianchadwick** [comment]
Something like this?
 https://github.com/ianchadwick/mockery/commit/9b8d4a3c0b96aef4a83086d07e39beb5c286d5c6

Seemed pretty easy to implement which from the above discussion makes me think maybe I'm missing something...

**Comment by davedevelopment** [comment]
@ianchadwick that looks alright to me, open a PR and we can discuss from there :+1:
