### ISSUE TITLE
Internal error when using --static-backup

### ISSUE THREAD

**Issue by david0** [mockery/mockery#268]
Currently its not possible to using ̀PHPUnit's `--static-backup`/`backupStaticAttributes="true"` with Mockery, since this will lead to some fatal errors:

```
$ phpunit --static-backup
PHPUnit 3.7.30 by Sebastian Bergmann.

Configuration read from ~\Downloads\mockery\phpunit.xml.dist

.......
Fatal error: ReflectionMethod::isPublic(): Internal error: Failed to retrieve the reflection object in ~\Downloads\library\Mockery\Loader\EvalLoader.php(16) : eval()'d code on line 178
PHP Fatal error:  ReflectionMethod::isPublic(): Internal error: Failed to retrieve the reflection object in ~\Downloads\library\Mockery\Loader\EvalLoader.php(16) : eval()'d code on line 178
```

Testet with mockery's testsuite (HEAD), PHP 5.3.14 on Linux

**Comment by malkusch** [comment]
Oh, I just wanted to create a bug report and pull request doing exactly as proposed but now discover this is an old and well known feature. Well I'm hitting that feature and would kindly ask where could I disabled that feature? Also is it documented?

**Comment by davedevelopment** [comment]
Sorry, I didn't ever get around to adding a configuration item for this. It's not really been bumped up the priority list for me as `backupStaticAttributes` isn't something I'd ever use.

**Comment by robertbasic** [comment]
As noone worked, nor requested this in 2 years, I'm going to close it.

If this is something you want in Mockery, please open a new issue and a pull request implementing the feature.

Thanks!

**Comment by malkusch** [comment]
Let me refresh my request, I want to get those mockery internals out of my test.
