### ISSUE TITLE
Unable to mock PDO

### ISSUE THREAD

**Issue by jasonlewis** [mockery/mockery#305]
When trying to mock PDO the following exception is thrown:

> PDOException: You cannot serialize or unserialize PDO instances

After searching Google it seems that if you stub out PDO and override the constructor PHPUnit's mocking can get around it.

```
class PDOStub extends PDO {
    public function __construct() {}
} 
```

Mockery, however, throws the same exception as above. I also tried to create a proxied partial mock:

```
$mock = m::mock(new PDOStub);
```

Same exception is thrown.

Any other suggestions for mocking PDO or is this a bug?

Cheers.

**Comment by robertbasic** [comment]
I think this is not an issue any more, I don't get any errors when trying to mock PDO. Please open a new issue if this is still a problem for you.
