### ISSUE TITLE
Integration with PHPUnit_Framework_Constraint

### ISSUE THREAD

**Issue by shigithub** [mockery/mockery#316]
Hi, I am new to Mockery and would like to ask you if you plan to add support for PHPUnit_Framework_Constraint matchers?

**Comment by robertbasic** [comment]
As this is something no one asked, nor worked on for almost 3 years, I'm going to close it.

If this is something you want in Mockery, please open a new issue with a pull request implementing the feature, with tests and documentation.

Thank you!
