### ISSUE TITLE
document the BC break about constructors being called

### ISSUE THREAD

**Issue by dbu** [mockery/mockery#317]
in #144 you changed the behaviour about constructors in mocks. i won't argue if this makes sense or not, but it would have been nice to have that documented in the CHANGELOG.md file. it puzzled me quite a bit, and then i don't know how i could have disabled the constructor being called.

the BC break happens when you mocked a class that has a mandatory constructor argument, like this: `$router = \Mockery::mock('\Symfony\Component\Routing\Router')`

in my case i was lucky because there is an interface for that which is the right thing to do anyways: `$router = \Mockery::mock('\Symfony\Component\Routing\RouterInterface')`

but that wont be possible in all cases.

**Comment by robertbasic** [comment]
This is now documented and on master, so I'm closing this issue.
