### ISSUE TITLE
Aliased, overloaded mocks of classes

### ISSUE THREAD

**Issue by evangelion1204** [mockery/mockery#336]
Hallo,

I would like to test a factory which returns an instance of a class like this.

``` php
class Factory {
    public function getInstance($param1, $param2) {
        return new namespace\AnotherClass($param1, $param2);
    }
}
```

To check if all params are correctly passed I do the same tests like testing the constructor of `AnotherClass` - duplicating my test cases. I use the getters of `AnotherClass` to check for the equality of the passed data.

``` php
$instance = $factory->getInstace($url, $params);
assertEquals($url, $instance->getUrl());
...
```

In the end I would like to create a mocked class `AnotherClass`, define with `shouldReceive` and `with` the parameters passed to the constructor and remove my assertions.

``` php
\Mockery::mock('aliased:namespace\AnotherClass');
???->shouldReceive('__construct')->with($url, $params);
???->shouldReceive('anotherFunction')->with('Hello')->andReturn('World')->once();
```

My factory would still be the same but return this mocked class, same would be nice for any other function, but `anotherFunction` should not be a static one, just a plain method of the class.

Thanks,

Michael

**Comment by fhinkel** [comment]
You can use an instance mock for hard-coded dependencies. 
```
$mock = Mockery::mock('overload:AnotherClass');
```
But you cannot set an expectation for the constructor. 

I would only test that the factory returns an instance of AnotherClass. To make sure that the parameters are passed in the right order, I would wrap them into value objects and use type hinting.  
```
public function anotherClass(Url $url, Param $param) {...}

**Comment by robertbasic** [comment]
As @fhinkel mentioned, this is something that's not supported by Mockery.

If you still have issue with this, please reopen it. I'm going to close it for now.

Thanks!
