### ISSUE TITLE
Expectation argument matching thinks json strings are regexes

### ISSUE THREAD

**Issue by theFreakus** [mockery/mockery#338]
I had a problem with expecting a json string as an argument today. It would match no matter what, because it thinks '{}' are delimiters of a regex.

Example:
expected: {"tempVar1":"content","tempVar2":"content","tempVar3":"content"}
actual: {"tempVar1":"content","tempVar2":"content","tempVar3":"content","muh":123}

matches just fine.

I know i could force a string comparison by using a hamcrest matcher, but the above was kinda unexpected.

**Comment by nicwortel** [comment]
I just ran into this issue... took me a while to figure out what was going on.

**Comment by robertbasic** [comment]
The mustBe matcher was deprecated for 1.0.0.

Labeling this issue for 1.0.0 because removing the regex matching would be a BC break.

**Comment by robertbasic** [comment]
See pull request #735
