### ISSUE TITLE
Static calls and global state

### ISSUE THREAD

**Issue by davedevelopment** [mockery/mockery#359]
This came up as someone was investigating the effects of calling or not calling `Mockery::close`

``` php
<?php

use Mockery as m;

require "vendor/autoload.php";

class News
{
    public static function getLatest() {}
}

$news1 = m::mock("News");
$news2 = m::mock("News");                          
$news2->shouldReceive("getLatest")->andReturn(123);
var_dump($news2->getLatest());

```

Static calls are proxied to the first known instance of the class, which makes sense for instance mocks, but probably not for regular mocks. It might be worth changing the container so that it can overrule the precedence.

**Comment by TiagoMaiaL** [comment]
I've tried to replicate this bug, and it seems to no longer happen. Guess it was corrected.

**Comment by robertbasic** [comment]
I've tried to replicate as well, reported behaviour is not happening.

Closing this issue, but if you still experience it, please reopen this issue with a small, reproducible test case.

Thanks!
