### ISSUE TITLE
Objects implements ArrayAccess, ArrayableInterface are not considered of type array 

### ISSUE THREAD

**Issue by paquettg** [mockery/mockery#363]
When you attempt to mock a method that type hints at an 'array' and instead you pass it a class as follows

``` php
class foo implements ArrayAccess, ArrayaInterface { ... }
```

If said class is also a mock (so I mocked foo) and attempted to pass the mocked foo into the method that hints at an array mockery will throw the following ErrorException

``` php
ErrorException: Argument 1 passed to Mockery_1_bar::save() must be of the type array, object given, ...
```

So, in this case I am testing the save() method of the bar mocked object and passing it a mocked foo that implements ArrayAccess and ArrayInterface (which does the rest of the standard array stuff). But I can't test this functionality as the error thrown is not correctly thrown in this case.

**Comment by robertbasic** [comment]
@paquettg could we get any update on this? A full code sample?

**Comment by downsider** [comment]
It isn't possible for an object using any interface to be passed to a function that typehints for an array. "array" is a primitive type and objects will always be objects; the interfaces merely define how they can be interacted with, not what type they are.

If you want to be able to pass an array or an array-like-object, you will have to remove the "array" typehint and check for type inside your method. Not ideal, I know, but what you are trying to do is not possible in PHP at this time.

For verification, I wrote the following test to make sure:

    class ArrayTest
    {
        public function __construct(array $a)
        {
        }
    }

    $arrayTest = new ArrayTest(new ArrayObject());

This throws the error:  

    Argument 1 passed to ArrayTest::__construct() must be of the type array, object given

_Note: ArrayObject implements the ArrayAccess interface. There is no ArrayableInterface in PHP_

**Comment by robertbasic** [comment]
Closing as there was no feedback for more than 2 years.

If this is something you still have issue with, please open a new issue with a small, but reproducible test case.

Thanks!
