### ISSUE TITLE
Readable way to call the parent class constructor

### ISSUE THREAD

**Issue by parhamdoustdar** [mockery/mockery#367]
I'm using Mockery to see if the methods on a dependency of my class are being called the expected number of times, and with the expected settings. However, since this is also an integration test, I'm calling `passthru()` at the end of all of my expectations. In other words, I'm using Mockery in this case to verify the arguments and the number of calls.

I create the mock like this:

``` php
$mock = \Mockery::mock('Elf\External\Services\GeneralReportQueryBuilder', [])->makePartial();
```

As you see, I'm passing an empty array as the second argument to force the constructor of this class to be executed. It would be better if I could say:

``` php
$mock = \Mockery::mock('Elf\External\Services\GeneralReportQueryBuilder')->shouldExecuteConstructor()->makePartial();
```

What I want is for the constructor of the partially mocked class to be executed.

**Comment by robertbasic** [comment]
If understood the conversation correctly, what @parhamdoustdar wants can already be achieved with `m::mock('Foo', [])->makePartial()` so there's nothing to do here really?

**Comment by padraic** [comment]
@robertbasic It can, but an empty array can be a bit obtuse. Supporting something like \Mockery::CALL_CONSTRUCTOR would be nice and explicit so I'll let it rest as a feature request for now.

**Comment by robertbasic** [comment]
Even if this is a valid feature request, I'm going to close this issue as noone has worked on it, or expressed interest in the feature for more than 2 years.

If you still want this to happen, please reopen this issue along with a pull request that adds this feature.

Thank you!
