### ISSUE TITLE
The repository is corrupted

### ISSUE THREAD

**Issue by galaxy4public** [mockery/mockery#389]
There is one commit made in May 2009 that introduced a corrupted tree object into the repository.  This makes it impossible to attach this repository to projects with strict rules on the repository consistence (i.e. which have transfer.fsckObjects set to true) via 'git subtree'.

The issue can be seen in the following session log (I just merely cloned this repository into a fresh directory, since policies of our repository do not allow broken object to enter the repository).  The first command checks the cloned repository for consistency errors, then I locate the commit that introduced the broken tree object, and finally I do a diff to see that commit (and the file it has altered):

```
$ git fsck --full
Checking object directories: 100% (256/256), done.
warning in tree e5ba5b4a01d4e5d8013b53ca17dde9fbade0c29b: contains zero-padded file modes
Checking objects: 100% (4844/4844), done.
$ git log --pretty=format:'%T %h %s' | fgrep e5ba5b4a01d4e5d8013b53ca17dde9fbade0c29b
e5ba5b4a01d4e5d8013b53ca17dde9fbade0c29b 2b901e4 Linked to blog post on Mockery alpha release.
$ git diff 2b901e4~1 2b901e4
diff --git a/README b/README
index fb1c99b..89d8c5e 100644
--- a/README
+++ b/README
@@ -93,3 +93,6 @@ There was 1 error:
 1) testAddWithFailingMock(AdditionTest)
 Mockery_ExpectationException: method add called incorrect number of times;
 expected call 2 times but received 1
+
+A vastly more detailed introduction including brief API documentation is available on my blog:
+http://blog.astrumfutura.com/archives/392-The-Mockery-An-Independent-Mock-Object-and-Stub-Framework-for-PHP5.html
\ No newline at end of file
$
```

Now, when you do "git subtree" it looks like the following:

```
$ git subtree pull --prefix vendor/mockery/mockery vendor/mockery/mockery master
warning: no common commits
remote: Counting objects: 4556, done.
remote: Compressing objects: 100% (2060/2060), done.
error: object e5ba5b4a01d4e5d8013b53ca17dde9fbade0c29b:contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
```

There is no easy fix for this bug (it was introduced on GitHub in 2009) and the only way I know of is to do git fast-export followed by git fast-import (since this procedure will recreate proper objects).

This bug is to make people aware that pulling from this repository "infects" their repositories with the broken objects too.

P.S. Personally, I had to clone the repository and fix the issue in my copy, then use my copy as upstream for our project.  But it's really painful to do further updates since each time I need to get updates I need to jump through hoops to achieve it :(.

**Comment by padraic** [comment]
@davedevelopment I'd say, let's make a concerted effort to clear the PRs (insofar as we can) and then do it. Still catching up on issues/PRs that are open so let me know.

**Comment by Idrinth** [comment]
Is it currently still planned to fix the issue?

**Comment by davedevelopment** [comment]
@Idrinth to be honest I had forgotten about it...

I'd like to assess the impact fixing would have, my understanding of git is that everything would just be fine?

**Comment by Idrinth** [comment]
@davedevelopment to my knowledge commit-hashes will change, so PRs should be handled first, merging anything build on the corrupted tree will be (next to) impossible after the force-push of the cleaned tree because of that.

Other than that there shouldn't be any issues for this project as far as I'm aware.

**Comment by davedevelopment** [comment]
And how about people who reference those commit hashes, particularly in `composer.lock` files etc?

**Comment by robertbasic** [comment]
@davedevelopment should we care about that now that we have a tagged stable release?

**Comment by davedevelopment** [comment]
@robertbasic I'd rather not break peoples builds. Forcing them to upgrade *now*, because they can no longer grab the version of mockery they've built on seems harsh.

**Comment by galaxy4public** [comment]
It is amazing that you continued to spread the infection for all these years, I guess it was not one of your priorities. Luckily, we moved on and no longer depend on this project, but it makes me sad that it really takes so long to right the "wrongs" :(

**Comment by Idrinth** [comment]
would have been easier to fix earlier, agreed @galaxy4public .

@davedevelopment installing a repository that requires a none-existing hash will break the install with a runtime error.
Assuming that mockery is only used in require-dev, it does not affect any none-dev installations tho.

**Comment by davedevelopment** [comment]
@galaxy4public I would admit it's not been one of my priorities and until a few days ago, you are the only person to have raised the issue. 

We're not the only ones to have this problem:

https://github.com/github/hub/issues/1404
https://github.com/sinatra/sinatra/issues/1305

My personal vote would be against rewriting the history, so maybe we look to move to a new repository for Mockery 2.0?

**Comment by davedevelopment** [comment]
Closing this, until a solution is found that doesn't involve a rewrite.
