### ISSUE TITLE
Mocking finfo under HHVM fails with mockery

### ISSUE THREAD

**Issue by heiglandreas** [mockery/mockery#393]
When using `Mockery::mock('\finfo');` hhvm fails with the following message: 

```
Fatal error: Default value for parameter options with a class type hint can only be NULL in /home/travis/build/heiglandreas/hhvmtest/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(16) : eval()'d code on line 704
```

Mocking the same one with phpunits mocking-framework everything works fine. 

A minimum example to reproduce can be found at https://github.com/heiglandreas/hhvmtest and the results can be found at https://travis-ci.org/heiglandreas/hhvmtest

The test does nothing else than to call `Mockery::mock('\finfo'):`.

I'll be working around that by using phpunits mocking-framework, but that's not really a solution....

**Comment by padraic** [comment]
I added https://github.com/facebook/hhvm/pull/4841/files

This should hopefully bring any issues to the hhvm team's attention where fixes needed on their end. On ours, I'll see if this produces anything and look through the failures when I can this week.

**Comment by robertbasic** [comment]
Given that we plan to drop hhvm support in the future with version 2 (see #835), I think this issue can be closed, as I doubt anyone will put in effort to add new support for hhvm stuff.

If this is something you'd like fixed/implemented in Mockery, please open a new issue with an accompanying pull request.

Thank you!
