### ISSUE TITLE
shouldNotHaveReceived does not increment expectation count.

### ISSUE THREAD

**Issue by Bilge** [mockery/mockery#440]
Writing a `shouldNotHaveReceived('method')` expectation on a mock object does not increment the `mockery_getExpectationCount` counter.

**Comment by aik099** [comment]
I guess we need to test result change of `mockery_getExpectationCount()` method as part of each test.

**Comment by robertbasic** [comment]
#563 was merged, so closing this issue for now.

If this is still an issue for you, please open a new ticket!

Thanks!
