### ISSUE TITLE
State of the documentation

### ISSUE THREAD

**Issue by robertbasic** [mockery/mockery#442]
Given that we have now a couple of tickets labelled `Towards 1.0.0` I thought to ask about the state of the documentation.

What new features were added that need docs? I see the spy stuff is new (to me) https://github.com/padraic/mockery/blob/master/tests/Mockery/SpyTest.php

What are still some undocumented parts of the code?

Hidden features that would fit nice into cookbook entries?

Add more known gotchas?

Do the docs need reorganizing? I know it's been done relatively recently, but was it completed, are most of the users happy with the new docs?

Would be nice to know the state of the docs from a "new user" point of view, I'm using mockery for... 3-4 years now, I kind of don't use the docs any more.

**Comment by robertbasic** [comment]
These are some good issues to move over here https://github.com/padraic/mockery-docs/issues

**Comment by padraic** [comment]
We can get a list going somewhere under the new label perhaps...

**Comment by davedevelopment** [comment]
Top of my head....

Some pages don't have code samples, we should probably put some in even for the simplest things, e.g. http://docs.mockery.io/en/latest/reference/public_properties.html

I think some of the headings could be clearer.

**Comment by godinaa** [comment]
I recommend reordering the way in which examples are presented. Right now it reads as example 1 code, example 1 explanation, example 2 code, example 2 explanation, etc. Rather than describing the code above it, it should describe what it's about to show you.

I though this was a conventional technical writing practice, but it may just be a personal preference.

**Comment by knugen** [comment]
I am of the exact same opinion as @aarongodin. It annoyed me enough to dig this old issue up :)

I would personally prefer it if the order was flipped, but if the maintainers for any reason want to stick to this ordering it would help if each example/explanation pair were visually grouped together.

If a decision is made on this I wouldn't mind helping out with the PR.

**Comment by davedevelopment** [comment]
Regarding the order, I think I would prefer 

> explanation
> code
> further explanation

Regarding the whole of this issue, I'm currently considering rewriting the docs from scratch. Some of the pages we have cover things that aren't completely necessary, some are convoluted etc.

I started this morning, trying to get a feel for how I might write them. Still not settled on an outline or anything like that, but people are welcome to take a look at https://github.com/davedevelopment/mockery/tree/new-docs.

**Comment by knugen** [comment]
I think that would be a very good structure. Thumbs up!

**Comment by robertbasic** [comment]
Uhhh... I guess this is still waiting for me.

**Comment by padraic** [comment]
Suggestion: Hire Steven Erikson?

**Comment by robertbasic** [comment]
Document PHP gotcha from #609.

**Comment by davedevelopment** [comment]
@robertbasic Do you want to push your new docs branch to the main repo, then I can push a few little things as they come up?

**Comment by robertbasic** [comment]
@davedevelopment sure. I'll open a pull request as well, so I can get early feedback.

**Comment by robertbasic** [comment]
@davedevelopment pr https://github.com/mockery/mockery/pull/731and branch https://github.com/mockery/mockery/tree/documentation/issue442

**Comment by robertbasic** [comment]
#388 should be a cookbook entry.

**Comment by robertbasic** [comment]
#453 as well.

**Comment by robertbasic** [comment]
#344 should be documented.

**Comment by robertbasic** [comment]
#317 is another one.

**Comment by robertbasic** [comment]
Document changes from #735

**Comment by robertbasic** [comment]
The PR for this got merged so I'm closing this issue.
