### ISSUE TITLE
Be able to create Mocks with definited class constants

### ISSUE THREAD

**Issue by dennisdegreef** [mockery/mockery#443]
I would like to be able to generate mocks which contains class constants.

I have a fork/branch which provides this behaviour as in, it generates the class with constants, defined in a pre-given array. 

The thing is, where would the best place be to pass these? I was thinking of creating something like `Mockery::mockWithConstantDefinition(array('FOO' => 'Bar'), 'SomeClass');`
, but this seems to be somewhat of a codesmell. Got any feedback?

https://github.com/padraic/mockery/compare/master...dennisdegreef:addClassConstantsToMocks

**Comment by aik099** [comment]
Mocks extend existing classes, so they would have all these constants as well. What you're describing might only be useful, when:
* you're creating mock for non-existing class
* you want to add more constants to the mock

**Comment by aik099** [comment]
We also have `namedMock` method (to accompany `mock`) method. Having another method that also supports constants would be too much I think.

**Comment by dennisdegreef** [comment]
This is the usecase I have: https://gist.github.com/dennisdegreef/fc99d4488be93d6d6c37

class Foo is a tightly coupled legacy class extended by _A LOT_ of classes, and I want to create tests for all children by mocking the base class, so after that, I can refactor Foo away (or more loosely coupled).

I must say, I only have some basic experience with Mockery, so I might be missing something which can help me with the same problem.

**Comment by aik099** [comment]
In your example you're mocking `Foo` class and you're that `$foo::ONE` doesn't work?

**Comment by dennisdegreef** [comment]
Yes, the implementation in the Foo_Bar class is using self::ONE somewhere, and since it's parent is a mock, it breaks.

**Comment by davedevelopment** [comment]
I think you'd be better not worrying about the constants. If I understand your use cases, you probably want partial mock the SUT:

``` php
class LegacyFoo 
{
    public function doSomeLegacyStuff() {}
}

class NewFoo extends LegacyFoo
{
    public function doSomethingNew()
    {
         // stuff
        $result = $this->doSomeLegacyStuff();
        // stuff
}

/** @test */
public function it_does_stuff()
{
    $sut = Mockery::mock("NewFoo")->makePartial();
    $sut->shouldReceive("doSomeLegacyStuff")->andReturn(123);

    $sut->doSomethingNew();
}
```

It's not an ideal practice, but should work.

**Comment by peixinchen** [comment]
I have a same problem but the scenario is a little different from @dennisdegreef , and this is my usecase that I had simplified:

https://gist.github.com/peixinchen/f0db56f1e0a82c8c81fe5cc45e0bff8a

**Comment by robertbasic** [comment]
For @dennisdegreef's problem, the easiest way is to do what @davedevelopment suggests. That's how I usually handle scenarios like that as well.

As for @peixinchen using a `namedMock` and a stub will do:

``` php
class FetcherStub
{
    const SUCCESS = 0;
    const FAILURE = 1;
}

// Controller to tesing.
class GatewayController
{
    public function index($request)
    {
        $data = Fetcher::fetch();

        if ($data['status'] === Fetcher::SUCCESS) {
            echo "OK" . PHP_EOL;
        } else {
            echo "NOT OK" . PHP_EOL;
        }
    }
}

\Mockery::namedMock('Fetcher', 'FetcherStub')
    ->shouldReceive('fetch')
    ->andReturn(['status' => 1]);

$c = new GatewayController();
$c->index([]);
```

What this does is that it creates a mock named `Fetcher`, based on the `FetcherStub` class.

I'll create cookbook entries for both of these cases, so it's going to be, hopefully, easier in the future.

As now both support issues raised are answered, albeit it took some time, I'm going to close this issue.

If you still have an issue with something, please open a new issue.

Thank you!
