### ISSUE TITLE
Public property is set on wrong instance when using "instance mock"

### ISSUE THREAD

**Issue by jangh** [mockery/mockery#451]
When trying to set a public property on an instance mock the property is set on the wrong instance.

Expected output:
instance!

Actual output:
mock!

``` php
<?php

require_once __DIR__.'/vendor/autoload.php';

$mock = \Mockery::mock('overload:');
$mock
    ->shouldReceive('foo')
    ->set('bar', true)
;

$instance = new $mock();
$instance->foo();

echo isset($instance->bar) ? "instance!\n" : '';
echo isset($mock->bar) ? "mock!\n" : '';
```

**Comment by robertbasic** [comment]
Bug confirmed, I have a failing test case in my old hard dep repo, on a separate branch: https://github.com/robertbasic/mockery-hard-dependency/tree/mockery-issue-451
