### ISSUE TITLE
Mocks from hardcoded dependities lacks of interface implementations

### ISSUE THREAD

**Issue by kamileczek** [mockery/mockery#452]
In case when I want to mock hardcoded dependities i always use overlod option.

Mockery::mock('overload:someClass');

Problem occurs when SUT has in code something like that:

if (!someClass instanceof SomeInterface) {
            throw new \RuntimeException('Cannot use supplied class');
}

It's always ends in throwing exception because "overloaded" mock do not implements that interface. Why Mockery didn't fetch interfaces from overloaded class and append it to mock to keep class identical to overloaded one?

**Comment by davedevelopment** [comment]
Probably because that's a lot of hardwork for a minimal use case. Mockery would have to do the job of the autoloader and workout which file should have that class definition in, read it and parse it to find what interfaces/types it might have. 

It might be passable to use a named mock, though I can't be sure.

``` php
<?php

require "vendor/autoload.php";

interface MyInterface {}

$mock = Mockery::namedMock("MyClass", "MyInterface");

var_dump(get_class($mock)); // MyClass
var_dump($mock instanceof MyInterface); // true
```

**Comment by chappy84** [comment]
Unfortunately the mock returned from namedMock doesn't take on the methods of the class being mocked, meaning this won't work in all circumstances.

**Comment by robertbasic** [comment]
@kamileczek is this still an issue for you? Can this issue be closed?

**Comment by robertbasic** [comment]
No response for a very long time, so closing this issue. Please open a new one, with a detailed explanation of your issue if this is still something you have a problem with. Thank you!
