### ISSUE TITLE
Mocking methods, that are handled via "__call" method

### ISSUE THREAD

**Issue by aik099** [mockery/mockery#461]
I have a class with `__call` method defined, that catches calls to all `get*` method. I need to mock single method in that class and I'm using partial mock this way:

``` php
class MockMe {

    protected $properties = array();

    public function __constuct()
    {
        $this->otherMethod();
    }

    public function __call($method, array $args)
    {
        if ( substr($method, 0, 3) === 'get' ) {
            return $this->properties[substr($method, 3)];
        }
    }

    public function otherMethod()
    {
    }

    public function doWork()
    {
        return $this->getMagicSetting() * 5;
    }

}

$mock = m::mock('MockMe[methodName]', array('constructor-arg'));
$mock->doWork();
```

Because Mockery doesn't know these magic method names it can't mock them in advance it throws an exception whenever `doWork` method is called.

Then I've tried to do this:

``` php
$mock->shouldReceive('getMagicSetting')-> passthru();
```

That however resulted in Fatal Error about maximal nesting level reached.

Also the method call in constructor totally breaks it because constructor is called before I'm able to call `->makePartial()` on the mock.

Any idea?

**Comment by aik099** [comment]
I've also tried to use custom mock configuration builder and backlist `otherMethod` upfront:
```php
$mock_configuration_builder = new MockConfigurationBuilder();
$mock_configuration_builder->addBlackListedMethod('setDriver');

// then pass this builder during mock construction
```
but that gave me same Fatal Error about nesting level.

**Comment by davedevelopment** [comment]
Not sure it's possible, I'd probably try and avoid it if possible.

**Comment by aik099** [comment]
Avoid which of what I've tried exactly?

**Comment by davedevelopment** [comment]
Avoid using mockery and test doubles altogether. I appreciate that's not all that useful.

**Comment by aik099** [comment]
But doesn't this sounds more like a bug, that passthu expectation can't be put on methods, that are handled by `__call` method of mocked class? Theoretically Mockery should be forwarding the `__call` method calls to mocked class instead of doing infinite recursion like it happens currently.

**Comment by davedevelopment** [comment]
Honestly, I don't know. This is such a complicated use case, I'm not sure if it's something we'd even want to support. I think I'd need to see the actual example, as the example you've given would just make me want to do:

```
$mock = m::mock('MockMe[getMagicSetting]', array('constructor-arg'), ['getMagicSetting' => 2])
```

**Comment by aik099** [comment]
What 3rd argument does?

The real example:

* branch: https://github.com/aik099/phpunit-mink/tree/42-refactor-browserconfigurationfactory-createapiclient
* this is what triggers (indirectly) the call that fails: https://github.com/aik099/phpunit-mink/blob/42-refactor-browserconfigurationfactory-createapiclient/tests/aik099/PHPUnit/BrowserConfiguration/ApiBrowserConfigurationTestCase.php#L329
* see trace below to know how `getSessionStrategy` is called

Just run unit tests (the `phpunit` command) to see, that `BrowserStackBrowserConfigurationTest::testTestEndedEvent` and `SauceLabsBrowserConfigurationTest::testTestEndedEvent` would fail with following exception:

```
Method Mockery_3_aik099_PHPUnit_BrowserConfiguration_BrowserStackBrowserConfiguration::getSessionStrategy() does not exist on this mock object
 .../library/aik099/PHPUnit/BrowserConfiguration/BrowserConfiguration.php:440
 .../library/aik099/PHPUnit/BrowserConfiguration/BrowserConfiguration.php:440
 .../library/aik099/PHPUnit/BrowserConfiguration/BrowserConfiguration.php:522
 .../library/aik099/PHPUnit/BrowserConfiguration/ApiBrowserConfiguration.php:209
 .../vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164
 .../vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:53
 .../tests/aik099/PHPUnit/BrowserConfiguration/ApiBrowserConfigurationTestCase.php:332
```
This happens because there is no `getSessionStrategy` method and `__call` method will be called to get it's response. The method wasn't detected during partial mock building because `getMethods` call of ReflectionClass wasn't returning it.

**Comment by aik099** [comment]
My 1st experiment: https://github.com/aik099/phpunit-mink/blob/42-refactor-browserconfigurationfactory-createapiclient/tests/aik099/PHPUnit/BrowserConfiguration/ApiBrowserConfigurationTestCase.php#L304
My 2nd experiment: https://github.com/aik099/phpunit-mink/blob/42-refactor-browserconfigurationfactory-createapiclient/tests/aik099/PHPUnit/BrowserConfiguration/BrowserConfigurationTest.php#L636-L655

**Comment by davedevelopment** [comment]
The third argument is a shortcut for stubbing method calls, essentially:

``` php
$mock->shouldReceive("getMagicSetting")->andReturn(2);
```

I aren't going to have time to dig through those tests right now, but I'll see if I can take a look at some point.

**Comment by aik099** [comment]
In fact that 3rd parameter helped. This way I was able to create an expectation before it was used from constructor and all is fine now. Thanks.

**Comment by robertbasic** [comment]
Looks like @davedevelopment's suggestion helped, so I'm going to close this issue.

Please reopen if this is still an issue for you.
