### ISSUE TITLE
Spies undocumented

### ISSUE THREAD

**Issue by Bilge** [mockery/mockery#463]
`Mockery::spy` is currently undocumented. It may be suitable to extract portions of [Dave's blog article on spies](http://davedevelopment.co.uk/2014/10/09/mockery-spies.html).

**Comment by countless-integers** [comment]
:+1:  , and thanks for the link @Bilge

**Comment by robertbasic** [comment]
@davedevelopment do I have your permission to use bits and pieces and parts from your blog post https://davedevelopment.co.uk/2014/10/09/mockery-spies.html in documenting spies?

**Comment by Bilge** [comment]
I can't speak for @davedevelopment but I recall creating this ticket specifically because, whilst conversing with him, he recommended doing that very thing. I do not think for a moment he would hold it against you.

**Comment by robertbasic** [comment]
@Bilge I know, but I still want to follow some kind of a protocol :)

**Comment by davedevelopment** [comment]
👍

**Comment by robertbasic** [comment]
This got documented and is now on master, so I'm closing this issue.
