### ISSUE TITLE
A real method is called when setup with shouldReceive and have parameters

### ISSUE THREAD

**Issue by jatubio** [mockery/mockery#484]
Hi, this is a strange behaviour:

I'm using mockery on my PHPUnit tests on a Laravel 5.1 web app.

I have one custom class Mail that receive Illuminate\Mail\Mailer in his constructor.

I want to test that my class Mail, call to Mailer->send() method with some parameters.

This code works perfectly:

```
$mailer = m::mock(Mailer::class)->makePartial();

$mailer->shouldReceive('send');

$custommailer = m::mock(
            Mail::class,
            [$mailer]
        )->makePartial();

// Put new mocked $custommailer on laravel IOC container.
$this->mockCustomMailer($custommailer);
```

When my code send one email, mail->send() is called and test pass.

But, if i change this line: 

```
$mailer->shouldReceive('send');
```

By this:

```
        $mailer->shouldReceive('send')->with(m::type('string'),
            m::subset(['urlUnSubscribe', 'urlUpdate']),
            m::on(function ($value) {
                return is_callable($value);
            }));
```

Real `mail->send()` method is called and i get one error because have not given any object on mocked Mail constructor (concretely a `Swift_Mailer instance`).

My question is: ¿It's is a bug or it's intended? I undertand that 'shouldReceive()' real methods aren't called never.

**Comment by jatubio** [comment]
After some trial and error, it seems that if number or value of expeted parameters given on shouldReceive is not matched by called method, Mockery is calling real method. Can be?

**Comment by davedevelopment** [comment]
@jatubio that's correct, `makePartial` is and alias to `shouldDeferMissing`, as in, should defer any calls we can't handle to the parent.

**Comment by jatubio** [comment]
@davedevelopment thank you for confirm this.

And, by __can't handle__ we can understand also __parameters don't match with shouldReceive signature__?

I would add that information to the documentation. Do you think that this is well explained?

https://github.com/padraic/mockery/compare/master...jatubio:patch-2
https://github.com/padraic/mockery/compare/master...jatubio:patch-1

**Comment by davedevelopment** [comment]
Yeah. When you're telling mockery `shouldReceive`, you're telling it what to expect. If it then gets something it's not expecting, it defers it to the parent. I personally don't think it needs further explanation in the docs, but I've been pretty immersed in this stuff for some time :)

**Comment by jatubio** [comment]
I'm using mockery for the first time two days ago. And I've never been tested until two months ago.

I use shouldReceive and when it gets something it's not expecting, it throw one exception: Good!
I need mock only some methods of one class. I look at mockery docs and I discover `makePartial()`, good! I start using them taken i will get the same behavior for 'mocked' methods. But not... It was hard for me to understand what happened.

Think on this like a note for dummies ;)

**Comment by robertbasic** [comment]
@jatubio is this still an issue for you? Can this be closed?

**Comment by jatubio** [comment]
@robertbasic, i'm not using mockery in this moment and can't test if is this still an issue.

I close the issue.

Best Regards

**Comment by robertbasic** [comment]
@jatubio thanks for getting back to us, and sorry it took us such a long time to get around your issue!
