### ISSUE TITLE
Problem with child class increasing visibility of method

### ISSUE THREAD

**Issue by will1471** [mockery/mockery#497]
I've encountered a problem mocking a class that increases the visibility of a method, declared in the parent as protected and in the child as public.

There is a test case highlighting the issue here: https://github.com/padraic/mockery/commit/52797e059a913695b3ca564542c76a38ed6b772b

Using the allow mocking protected methods flag allows the test to run as expected, but the method is not protected and this should not be required.

I believe the issue comes from using the methods prototype in Mock::mockery_getMethods() which causes the parent classes visibility to be used instead of the childs.

**Comment by janedbal** [comment]
I've run into this issue too. Another related problem is that Mockery allows you to call that method without any warning (that it actually doesn't exist on the mock object).

```php
class Base {
    protected function method() {}
}

class Child extends Base {
    public function method() {}
}

$child = Mockery::mock(Child::class);
// $child->shouldReceive('method'); // when uncommented, fails as mentioned by will1471

$child->method(); // works when line above is commented out
```

Also, when you set disable mocking non-existent methods, the error from Mockery is very confusing (it is mentioned as non-existent method).

**Comment by robertbasic** [comment]
Closing this issue as #565 was merged.

Please reopen if this is still an issue for you.
