### ISSUE TITLE
BadMethodCallException with message "Method ... getFields() does not exist on this mock object"

### ISSUE THREAD

**Issue by FelikZ** [mockery/mockery#498]
``` php
$foo = Mockery::mock('Model\Foo');
$foo->match_search_url = null;
```

Error:

```
BadMethodCallException with message "Method Mockery_0_Model_Foo::getFields() does not exist on this mock object"
```

How to fix that and why it works at [here](https://github.com/padraic/mockery/blob/3aee65d0a6a9b5e3e8b95a4a4b7830257e7ed608/tests/Mockery/ExpectationTest.php#L82) for `$this->mock->bar = null;` ??

**UPD:**
- Reproduced on php 5.4 and 5.6
- cmdline to launch: `pho -b test/spec/bootstrap.php -r spec test/spec/path/to/TestSpec.php`

**UPD2:**
- Reproduced only if Model\Foo is existing class

**UPD3:**
- Caused by Model\Foo's base class magic method `__set` that is using `getFields` method

**Comment by davedevelopment** [comment]
Is `Model\Foo` extending a base class, that uses `__set`, which in turn calls something called `getFields`?

**Comment by FelikZ** [comment]
@davedevelopment yes! It has exactly this behaviour. How to deal with it?
Thanks for a response!

**Comment by robertbasic** [comment]
@FelikZ sorry for no reply in such a long time. Is this still an issue for you?

**Comment by robertbasic** [comment]
@FelikZ Using the `passthru` method of Mockery should help you.

You'd use it in a similar way to this:

``` php
<?php

require_once 'vendor/autoload.php';

class Foo
{
    public function getFields()
    {
        echo "Original getFields called" . PHP_EOL;
    }

    public function __set($prop, $value)
    {
        $fields = $this->getFields();
        // do something here ...
    }
}

class Bar extends Foo
{
}

$mock = \Mockery::mock('Bar');
$mock->shouldReceive('getFields')->passthru();
$mock->property = null;
```

What it does is that it tells Mockery if the mock object receives any calls to the `getFields` method, it should pass it through (passthru) to the original method.

Hope this helps. I'm going to close this issue now, but feel free to reopen it if this does not help you.

Thanks!
