### ISSUE TITLE
PHP 7: Mocking classes with typed __isset/__call/__callStatic results in an error

### ISSUE THREAD

**Issue by Majkl578** [mockery/mockery#499]
``` php
class Test {
    function __isset(string $foo) {}
}

Mockery::mock(Test::class);
```

leads to:

```
Warning: Declaration of Mockery_0_Test::__isset($name) should be compatible with Test::__isset(string $foo)
```

Same applies to return typehints:

``` php
class Test {
    function __isset($foo) : bool {}
}

Mockery::mock(Test::class);
```

leads to:

```
Fatal error: Declaration of Mockery_0_Test::__isset($name) must be compatible with Test::__isset($foo): bool
```

**Comment by michaelmoussa** [comment]
@Majkl578 this appears to have been fixed by 971dcdf. You can use this in your project by adding `"mockery/mockery": "dev-master#971dcdfdc2239b3d516672139f4368c19f6c2060 as 0.9.5"` in your hosts file and running `composer update mockery/mockery` until a new release is done.

@davedevelopment would you mind tagging a new release with this? It's been a while and some folks are already working on applications designed for PHP 7.

**Comment by Majkl578** [comment]
I think I used dev-master at the time when I reported this issue. But I can check again.

**Comment by Majkl578** [comment]
Still broken in ee88cd0.

**Comment by 5outh** [comment]
What is the status of this? Running into the issues mentioned above regarding type-hinted methods as well.

**Comment by TiagoMaiaL** [comment]
Guess it wasn't solved neither is being resolved.

**Comment by davedevelopment** [comment]
I'll see if I can set some time aside later today, can't make promises though. If anyone else fancies a crack, I think the way to do it would be to add a `Mockery\Generator\StringManipulation\Pass\Pass`, that adds the type hints in.

**Comment by TiagoMaiaL** [comment]
I can actually take some time to solve this. I'll take some time to solve this.

**Comment by davedevelopment** [comment]
@TiagoMaiaL :+1: thank you! Mockery's code generation is pretty hacky as it just manipulates strings, so regexes are your friend. We do string manipulation mostly because it is fast.

**Comment by TiagoMaiaL** [comment]
Nice, I'll certainly take this into account.

**Comment by robertbasic** [comment]
Closing as #585 was merged.

Please reopen if this is still an issue for you.

**Comment by evsign** [comment]
Still an issue. Signature like this is not pass.
```
public function __call(string $method, array $arguments) : RequestBuilder;
```
Work only `public function __call($method, array $arguments);`

`"mockery/mockery": "^0.9.9"`
