### ISSUE TITLE
The first expectation is matched, rather than the most specific

### ISSUE THREAD

**Issue by KimPrince** [mockery/mockery#507]
In the code below I am configuring expectations for when the get() method is called on a mock ZF2 service locator.  As a general rule, if the argument to the get() method starts with Mapper\ regex pattern, I return a mocked mapper interface (Core\iMapper\Mapper).  If, however, the argument is Mapper\User, I return a $userMapper.

The argument validation for Mapper\User is more specific than the regex matcher, so I think it should match in preference to the general Mapper matcher.  This is not how it works, however.  I can only get it to match the literal Mapper\User by configuration this expectation prior to the regex one.

```
  $this->serviceLocator = m::mock('Zend\ServiceManager\ServiceLocatorInterface')

        // generally mock calls to get a mapper
        ->shouldReceive('get')
        ->with(matchesPattern('/^Mapper\\\\/'))
        ->andReturn(m::mock('Core\iMapper\Mapper'))
        ->getMock()

        // specifically mock calls to the user mapper
        ->shouldReceive('get')
        ->with('Mapper\User')
        ->andReturn($userMapper)
        ->getMock();
```

**Comment by davedevelopment** [comment]
Yep, we don't have that as a facility, I'm not really sure if it's something I'd want to add, I can't see myself using it. However, if someone out there would like to give it a crack, I'd be happy to give some general direction.

**Comment by aik099** [comment]
Yes, the earlier created expectation has more weight in expectation comparison.

Maybe Prophecy-like expectation weight system can be introduced in which exact match has more weight compared to partial match regardless of expectation defining order.

**Comment by davedevelopment** [comment]
It just seems like swings and roundabouts for me, I'm sure there are some more complicated cases, but I'd just set the expectations up in the order of most specific -> to least specific.

**Comment by aik099** [comment]
That may not be possible if mock is configured from several places and each place only sets expectations needed to it and isn't aware that expectation with higher weight might already exist.

Maybe for use case described originally the best would be to reorder expectations.

**Comment by davedevelopment** [comment]
Aye, I just don't see those cases very often and therefore I'm reluctant to add a large amount of effort in to making it possible.

**Comment by aik099** [comment]
Agreed.

**Comment by downsider** [comment]
I can see why weighting expectations would be difficult, but I have a use case that might be easier to implement. Would it be possible to order expectations _with_ argument matching above those that do not?

For example, in the following code the second expectation will never match, even though it is obviously more specific.

    // this will always take precedence
    $mock->shouldReceive("testMethod")->andReturn("any argument");
    
    // testMethod will never return "specific argument", due to the existence of the first expectation
    $mock->shouldReceive("testMethod")->withArgs("argument")->andReturn("specific argument");

**Comment by davedevelopment** [comment]
It's definitely possible, but I think if we're going to add one rule, we should really consider a full set. I'm interested to see a complete example of the need for this if anyone can post some code.

**Comment by tflori** [comment]
For me it is important too. Why: It's getting too complicated. The result: logic in tests.

Example: I have to mock views functions like start and finish (they open output buffers)
```php
$di->set('view', function() {
  $view = \Mockery::mock(new View());
  $view->shouldReceive('start');
  return $view;
}, true);
```

Not all the tests expecting a call - so it's any times. But this expectation never fullfills:
```php
$view $this->di->get('view');
$view->shouldReceive('start')->once();
```

Of course the other one matches. For me it's clear that it has to be turned to first in -> last out - the last expectation I entered should be checked first. Because in my setUp I mock in general first then getting more specific in a test.

**Comment by davedevelopment** [comment]
@tflori for the generalities in `setup`, you can use `byDefault`, this should work for you:

```
$di->set('view', function() {
  $view = \Mockery::mock(new View());
  $view->shouldReceive('start')->byDefault();
  return $view;
}, true);
```

**Comment by tflori** [comment]
@davedevelopment thanks, for me this is maybe working. I will try. meanwhile I updated my branch and now it's green and tested: #566

**Comment by robertbasic** [comment]
As no one provided a full set of example use cases for this feature request for over a year, per @davedevelopment's request, I'm closing this feature request.

Please reopen if this is still something you would like to be added to Mockery, but do provide as much examples as possible. Thanks!
