### ISSUE TITLE
Feature request: a way to capture arguments

### ISSUE THREAD

**Issue by marcaube** [mockery/mockery#508]
As requested by @davedevelopment on twitter, here's a feature request for a method to capture arguments, just like [Phake::capture()](http://phake.readthedocs.org/en/2.1/method-parameter-matchers.html#parameter-capturing).

I had a situation recently where this would have been useful. I was writing a class to implement our `EventDispatcherInterface` using `league/event`. With this library, listeners can be of type `callable`or `League\Event\ListenerInterface`. To make it compatible with our `ListenerInterface`, our dispatcher wraps the listeners in an anonymous function.

``` php
final class LeagueDispatcher implements EventDispatcherInterface
{
    // ...

    public function addListener($eventName, ListenerInterface $listener)
    {
        // wrap the listener in a callable, to make it compatible with League\Event\Emitter
        $leagueListener = function ($event, $payload) use ($listener) {
            return $listener->handle($event->getName(), $payload);
        };

        $this->emitter->addListener($eventName, $leagueListener);
    }
}
```

In my unit tests, I'd like to make sure this `handle()` method is called on the listener with the proper arguments. But the only (obvious) way to do it would be to capture the second argument of the `addListener` expectation.

``` php
class LeagueDispatcherTest extends Mockery\Adapter\Phpunit\MockeryTestCase
{
    public function testCanRegisterAnEventListener()
    {
        $emitter = m::mock('League\Event\EmitterInterface');

        // If Mockery could capture the callable argument like Phake can, we could execute it and set
        // expectations on the listener mock to make sure the handle() method is called and get 100% coverage.
        $emitter->shouldReceive('addListener')->once()->with('foo.bar', m::type('callable'));

        $listener = m::mock('Acme\EventDispatcher\ListenerInterface');

        $dispatcher = new \Acme\EventDispatcher\LeagueDispatcher($emitter);

        $dispatcher->addListener('foo.bar', $listener);
    }
}
```

**Comment by davedevelopment** [comment]
@marcaube thank you for adding this!

Just so you know, the way to do it now is to use `andReturnUsing` or `Mockery::on`, but neither are as a nice as Phake's option.

I don't use `Mockery::on` very often, but I believe you use it like this:

``` php
$emitter->shouldReceive('addListener')->once()->with('foo.bar', m::on(function ($callable) {
    $callable(new Event(), new Payload()); // I don't know the correct types, but you get the idea
});
```

That is, on receiving the second argument to "EmitterInterface::addListener", run it through this anonymous function, which in turn just runs the callable that was sent.

**Comment by marcaube** [comment]
Thanks for the workaround, I couldn't figure out how to do it on my own.

**Comment by aik099** [comment]
Wow. I never knew, that `m::on` even exists. It allows to define a matcher in real time or just transforms incoming argument without any kind of validation?

**Comment by davedevelopment** [comment]
@aik099 it's there for complicated matchers I believe

**Comment by robertbasic** [comment]
For what it's worth, Mockery::on has a cookbook entry: http://docs.mockery.io/en/latest/cookbook/mockery_on.html

**Comment by robertbasic** [comment]
@marcaube is the `\Mockery::on` sufficient for what you initially wanted to do? Just trying to see if we need some additional functionality here or we got it covered with `on`? Thanks!

**Comment by marcaube** [comment]
@robertbasic I think `on` did the trick at the time, but it's been > 2 years and 2 jobs ago 😉

**Comment by robertbasic** [comment]
@marcaube fair enough, thanks for taking the time to reply! :)

Given that the feature is in there, I'm going to close this issue. If someone still wants to see this done/improved in Mockery, feel free to reopen the ticket. You'll get bonus karma if you provide a pull request as well :)

**Comment by jasonmccreary** [comment]
Took a stab at making this a bit more expressive with `Mockery::capture()` in https://github.com/mockery/mockery/pull/1020
