### ISSUE TITLE
Wrong argument type when using namespace in namedMock

### ISSUE THREAD

**Issue by GreenManSK** [mockery/mockery#525]
When I use namespace in name of mock object, all arguments with typehint, get that namespace prepend before them. Even when using absolute namespace.

For example:

``` php
namespace NmSpace {
    class Boo { 
    }
}

namespace {
    abstract class Foo {
        function boo(\NmSpace\Boo $boo) {
        }
    }
    $mock = Mockery::namedMock("RandomSpace\RandomName", Foo::class);
    $boo = new NmSpace\Boo();
    $mock->boo($boo);
}
```

Returned error:
`Catchable fatal error: Argument 1 passed to RandomSpace\RandomName::boo() must be an instance of RandomSpace\NmSpace\Boo, instance of NmSpace\Boo given`

**Comment by robertbasic** [comment]
While this issue is present on 0.9.x tags, it is not present on current master, or on the 1.0.0-alpha tag.

After doing some git bisect, the issue was fixed with merging the PR #558 

Closing as it is fixed.
