### ISSUE TITLE
Feature: expect subset of method parameters

### ISSUE THREAD

**Issue by Bilge** [mockery/mockery#531]
Currently all or no method parameters must be expected. It should be possible to expect a subset of parameters. For example, if I am only interested in the first parameter I should be able to specify how the first matches but then be able to indicate to Mockery in some way that any additional parameters are unimportant, whether they're present or not.

**Comment by aik099** [comment]
You can specify `m::any()` as 2nd parameter to allow matching for any 2nd+ argument values.

**Comment by Bilge** [comment]
@aik099 I'm afraid that's simply not the case. `\Mockery::any()` will match exactly one argument in the position it appears in, only. That is, `->with(123, \Mockery::any())` is not the same as `->with(123, \Mockery::any(), \Mockery::any())`: the former will match exactly two arguments and the latter will match exactly three.

**Comment by davedevelopment** [comment]
I use `andReturnUsing` to do this kind of thing, which is clunky, but I'm not really too sure what might be better.

**Comment by Bilge** [comment]
I believe the only two potential options would be 

* a matcher that specifies the rest of the arguments are irrelevant, or
* a method that will only check the arguments specified and ignore the rest.

**Comment by aik099** [comment]
> a matcher that specifies the rest of the arguments are irrelevant, or

I vote for this one. This how it was implemented in https://github.com/phpspec/prophecy :

* `AnyValueToken` or `Argument::any()` - matches any argument
* `AnyValuesToken` or `Argument::cetera()` - matches any arguments to the rest of the signature

**Comment by davedevelopment** [comment]
And are we happy with `cetera`? I don't mind it, wondering if we could use `\Mockery::variadic()`?

**Comment by Bilge** [comment]
I haven't used Prophecy but I admire it's inventiveness with respect to naming and the syntax of its API. That said, I don't think we should be lifting hip names like *cetera* straight from it because that's not Mockery's style. If we like that name, and it's certainly pretty good, then I think we should use the full name *etcetera* and/or the popular abbreviation, *etc*.

I'm sorry to say, but *variadic* is a poor choice because the matcher does not only apply to variadic functions and is more likely to be misleading.

**Comment by Bilge** [comment]
I liked this issue better when it wasn't dead.

**Comment by Bilge** [comment]
@davedevelopment @robertbasic Any further thoughts on this?

**Comment by robertbasic** [comment]
@Bilge this isn't something I would personally use, but I'd accept a PR for it, if it provides a nice implementation.

**Comment by robertbasic** [comment]
This is now implemented with #860, closing.
