### ISSUE TITLE
Mocked object not having mocked method despite explicitly setting expectation

### ISSUE THREAD

**Issue by CyberiaResurrection** [mockery/mockery#532]
I've got this test case (Laravel 5.1.28, PHPUnit 4.8.21, Mockery 0.9.3) that is blowing up rather (for me) mysteriously.

``` php
    public function testGetLastReconciledBalanceOnePreviousRec()
    {
        $foo = \Mockery::mock('App\AccountsController');
        $bar = new Reconciliation();
        $bar->close_balance = 109.15;
        $foo->shouldReceive('reconciliations->get')->withNoArgs()->andReturn([$bar]);
        $foo->shouldReceive('getLastReconciledBalance')->passthru();

        $result = $foo->getLastReconciledBalance(1);  // Wha?
        $this->assertEquals(109.15,$result);
    }

```

There's no setup or teardown methods in the test class.  Pain persists whether I run entire test suite, test class or just that test in question.  It also doesn't seem to be sensitive to the order in which expectations are set up.

AccountsController does have an actual getLastReconciledBalance() method, which calls reconciliations()->get() (which is why I've mocked that as well).

Resulting error is (and what has me confused - other test classes are using Mockery without any problems):

```
ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'App\AccountsController' does not have a method 'getLastReconciledBalance'

/var/www/html/BCS/vendor/mockery/mockery/library/Mockery/Expectation.php:177
/var/www/html/BCS/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:107
/var/www/html/BCS/tests/unit/controllers/admin/AccountsControllerReconciliationTest.php:42
/var/www/html/BCS/tests/unit/controllers/admin/AccountsControllerReconciliationTest.php:42
/home/alex/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:148
/home/alex/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:100

```

What have I missed or am doing wrong?

**Comment by rquadling** [comment]
Does ``$foo = \Mockery::mock('App\AccountsController')->makePartial();`` help?

**Comment by davedevelopment** [comment]
No idea! Can you post some or all of the `App\AccountsController` class?

**Comment by rquadling** [comment]
``passthru()`` requires ``makePartial()``

**Comment by robertbasic** [comment]
@CyberiaResurrection is this still an issue for you? Can you provide more about that `App\AccountsController` as @davedevelopment asked?

**Comment by CyberiaResurrection** [comment]
Sorry this fell through the cracks, can't remember what I did but that did sort it out.

**Comment by trip-somers** [comment]
For anyone else who finds this, I was having the same problem when my mock looked like this:

```
        $mock = Mockery::mock(MyClass::class)->makePartial()
            ->shouldReceive('myMethod')
            ->with($myData)
            ->once()
            ->andReturn($myResponse);
```

When I switched it to this, the error was gone.

```
        $mock = Mockery::mock(MyClass::class)->makePartial();
        $mock->shouldReceive('myMethod')
            ->with($myData)
            ->once()
            ->andReturn($myResponse);
```

This doesn't match the OP's issue, but the error was the same.

LESSON: Pay attention to return values of your chained methods.
