### ISSUE TITLE
Mysterious error

### ISSUE THREAD

**Issue by fedeisas** [mockery/mockery#548]
Hi there! I'm having this error when running my full suite with `paratest` on Jenkins.

``` php
PHP Fatal error:  Call to a member function __call() on null in Mockery/Loader/EvalLoader.php(16) : eval()'d code on line 370
```

I can't even begin to track where this is happening (large codebase, 1000+ tests).

Is there anyway to have a backtrace of this?

I'm thinking that this is a problem when replacing instances on our DI container with mocked ones, and they get reused on the next test.

**Comment by davedevelopment** [comment]
Put this line in your test bootstrap code, it should help you debug a little:

``` php
Mockery::setLoader(new Mockery\Loader\RequireLoader(sys_get_temp_dir()));

```

**Comment by fedeisas** [comment]
Thanks @davedevelopment! I found some broken tests, although still fails.

I found most errors are `shouldReceve(...)->with(...)` calls.
When the `with()` part is different, it kinda goes crazy.

I'm wondering what the best practice is for doing argument validation and avoiding this obscures failures.

Maybe starting the mock with a `shouldReceive()` without `with()`.

**Comment by robertbasic** [comment]
@fedesias is this still an issue for you?

**Comment by fedeisas** [comment]
@robertbasic yeah, I don't remember much, but I think I was doing something wrong with arguments validation. Thanks!

**Comment by vsjoshtait** [comment]
> 

Can you tell me how to go about this? I'm having a nightmare trying to debug what our specific error is.

**Comment by ghostwriter** [comment]
@vsjoshtait, you can add that line inside the PHPUnit setup method in your test.

```php
public function setUp(): void
{
    $dumpPath = dirname(__FILE__).'/MockeryDump';
    Mockery::setLoader(new Mockery\Loader\RequireLoader($dumpPath));

    parent::setUp();
}
```

**Comment by Disservin** [comment]
I ran into this error after mocking a static method call to a class which was aliased
Unit Test 1, had something like this
```php
m::mock('alias:' . MyClass::class)->shouldReceive('foo')->andReturn(1);
```

Unit Test 2, didn't have this but was instead depending on the native (my) implemention of `foo` and not the mocked one. 

If I understand https://docs.mockery.io/en/latest/reference/public_static_properties.html
correctly it doesn't seem like it is really intended to undo this behaviour...
