### ISSUE TITLE
Semi automatically generate mocks.

### ISSUE THREAD

**Issue by rquadling** [mockery/mockery#560]
Hi.

Just starting out with mocking, so please be patient.

Is it possible to generate a mock of a class from the current usage for a test case?

Say, for example, you need to talk to a database, various calls to the database layers are made (quoting, querying, hydrating, etc.). It would be useful to be able to generate the mock from the actual data, such I can rerun the test, using the mock as many times as I need.

Am I just being lazy? Or is there something I can do that will essentially snapshot the request/response for a single class as it pertains to the current test?

**Comment by davedevelopment** [comment]
There is some [object recording](http://docs.mockery.io/en/latest/reference/object_recording.html), but I don't think it's quite what you are asking for and to be honest, it's not something I'd ever use or care to maintain, it's just been there forever.

As for are you being lazy, it's more a question of what are you expecting to get out of the tests that you end up with? You might get some tests that fail if someone changes the implementation, but generally you want the tests to fail if someone changes the behaviour.

**Comment by robertbasic** [comment]
I'd vote for this issue to be closed, as I don't think this is something that will happen, if I'm understanding @davedevelopment correctly :)

**Comment by robertbasic** [comment]
I'll leave this open for a while, to try and get more feedback about the feature request.

**Comment by davedevelopment** [comment]
I'll note that I removed the object recording feature.

**Comment by robertbasic** [comment]
@davedevelopment fwiw, you already added a note for that in the changelog: https://github.com/mockery/mockery/commit/6884d0f3f7e725a3b9a8b80978543eaecd50ff66

**Comment by rquadling** [comment]
I'm happy for the issue to be closed.
