### ISSUE TITLE
Mocking readonly properties

### ISSUE THREAD

**Issue by mindplay-dk** [mockery/mockery#575]
Is it possible to mock read-only properties?

```
        /** @var MockInterface|PDOStatement $mock_handle */
        $mock_handle = Mockery::mock(PDOStatement::class);

        $mock_handle->queryString = "SELECT 1"; // ker-blowie! :-(
```

In this example, I get a `PDOException` with the message "queryString is read only", suggesting that it may not possible to set a read-only property of a mock object at all?

Of course, read-only properties are not (presently) a "thing" in userland code, but there are read-only properties in various classes implemented by extensions.

Any idea how to work around this?

**Comment by davedevelopment** [comment]
No idea at all! I think you may have found a limit to mockery's capabilities with that one.

**Comment by mindplay-dk** [comment]
Yeah, I experimented with this - it's not possible, a class extension cannot hide that property by redeclaring it.

Man, this makes me want to write several new PSRs for php...

**Comment by TiagoMaiaL** [comment]
What do you guys think of making this issue a feature request? Depending on how many people needing something like this, it could go further and be implemented.

**Comment by mindplay-dk** [comment]
@TiagoMaiaL I think you misunderstand - it's a limitation of php.

```php
class X extends PDOStatement {
    public $queryString;
}

$x = new X();

$x->queryString = 'SELECT 1'; // => PDOException: General error: property queryString is read only
```

It's quite impossible :-)

**Comment by TiagoMaiaL** [comment]
What you say is true. But we can still achieve a feature like this with magic getters, we could even use inheritance just to increase the visibility of a property, the same is true for methods. The last has it's cons, as it wouldn't be possible to change a class at runtime.

**Comment by mindplay-dk** [comment]
> But we can still achieve a feature like this with magic getters

Getters and setters are not get invoked before it throws the readonly exception.

**Comment by TiagoMaiaL** [comment]
> Getters and setters are not get invoked before it throws the readonly exception.

The following code works in php 5.4 (the lowest version supported) and newer versions:

```PHP
<?php

class AClass
{
    private $privateVariable;
    protected $protectedVariable;
    public $publicVariable = '=X';
    
    public function __get($name) 
    {
        echo '=D';
    }
}

$a = new AClass;
$a->privateVariable;
$a->protectedVariable;
echo $a->publicVariable;
// =D=D=X

```

**Comment by mindplay-dk** [comment]
> The following code works

What does this have to do with PDO?

```php
<?php

class MockStatement extends PDOStatement
{
    public function __set($name, $value)
    {}
    
    public function __get($name)
    {}
}

$sth = new MockStatement();

$sth->queryString = "SELECT 1";

// => PDOException: SQLSTATE[HY000]: General error: property queryString is read only
```

`PDOStatement::$queryString` is a readonly-property, something the language itself does not support - it was implemented that was internally, and as you can see, `__set()` does not get invoked before it throws the readonly-exception.

The only way you could do this, would be with something like runkit, and maybe not even then - that, or disable the PDO extension and mock the whole thing; but then you would probably have other tests that you can't carry out, e.g. integration tests.

Even if that were possible, it's beyond the scope of Mockery, and would probably need to be supported by e.g. php-unit - e.g. it would need to create/modify a `php.ini` file and launch a new php interpreter for tests that require specific settings, e.g. with some extensions disabled and mocked.

**Comment by TiagoMaiaL** [comment]
> PDOStatement::$queryString is a readonly-property, something the language itself does not support - it was implemented that was internally

Now I've understood your point, wasn't getting it straight :confused:. This is indeed quite impossible.

**Comment by robertbasic** [comment]
@davedevelopment this issue can be closed I believe!

**Comment by robertbasic** [comment]
Closing as general agreement is that this is not possible to do, due to PHP limitations.

**Comment by mindplay-dk** [comment]
I did ask internals about it back then, and they were like, meh.

**Comment by mindplay-dk** [comment]
Years later, I found a way to mock `PDOStatement` in PHP 8.1 and up.

Just add this:

```php
class MockPDOStatement extends PDOStatement
{
    public function __construct(public string $queryString)
    {}
}
```

Then mock the extended class:

```php
/** @var MockInterface|MockPDOStatement $mock_handle */
$mock_handle = Mockery::mock(MockPDOStatement::class, ["SELECT :foo"]);
```

Accessing `queryString` on that object now works. 👍

It's sort of a roundabout way to do it, and I still wonder why Mockery itself can't do this - but I've got a passing test with a `PDOStatement` mock, so yeah.
