### ISSUE TITLE
Option to use custom objectToArray implementation

### ISSUE THREAD

**Issue by MartinMystikJonas** [mockery/mockery#603]
Some of our object have public properties accessible only when object is in correct state. If object is in wrong state attempt to read this property raises excetion (magic __get).

This is problem when Mockery tries to convert these objects to array in for example Unexpected calls messages.

We would like to have option to set custom implemenation of objectToArray via configuration.

**Comment by davedevelopment** [comment]
I think my preference would be to have a global toggle that disables that deep inspection for output.

**Comment by MartinMystikJonas** [comment]
It's more than year since I proposed this change. Any change in opinion on this? I can prepare PR with this improvement if it will be accepted as good solution.

**Comment by MartinMystikJonas** [comment]
Solution proposed in PR #766 

@davedevelopment This solution allow you to disable deep inspection of some objects - just set empty formatter

**Comment by ghostwriter** [comment]
Resolved #766
