### ISSUE TITLE
ShouldNotHaveReceived with arguments

### ISSUE THREAD

**Issue by tpavlek** [mockery/mockery#604]
Currently when you use `$mock->shouldNotHaveReceived('method')` that's the end of the deal. I'd like to be able to chain expectations to that as with any other method in mockery.

For example, in my use case, I want to assert that a method was called with `foo` called again with `bar`, but I want to _make sure_ it was **not** called with `baz`.

Unless I'm missing something it doesn't look like it's possible to do that with a spy currently?

**Comment by davedevelopment** [comment]
I've no major objections to adding this in.

**Comment by TiagoMaiaL** [comment]
I could start working on this, I just want to make sure if this is something somebody is already doing or intended to do. If not, I can make a PR soon.

**Comment by robertbasic** [comment]
@TiagoMaiaL are you still working on this? @tpavlek is this still a feature you need?

**Comment by tpavlek** [comment]
I've worked around it in the interim, but it's definitely a feature I'd appreciate.

**Comment by robertbasic** [comment]
Hm it is possible to do with `shouldNotHaveReceived('foo', ['bar']);` but not with `shouldNotHaveReceived('foo')->with('bar');`

**Comment by davedevelopment** [comment]
I think I misunderstood the initial request, I thought you just wanted to change the return types of the `shouldNotHaveReceived` method so you could do

``` php
$spy
    ->shouldNotHaveReceived('method')
    ->shouldHaveReceived('foo')->with('baz');
```

As @robertbasic pointed out, you can add a second argument to the `shouldNotHaveReceived`, or the alternative is to use the higher order message format. 

``` php
$spy->shouldNotHaveReceived()->method('bar');
```

The problem is, Mockery can't know when you have finished specifying a the expectations.

``` php
$spy->shouldNotHaveReceived('method')->with('bar');
//                                  ^ Mockery has to check if it has received a call to method here. 
//                                    It doesn't know it is about to get a more specific requirement so it has no choice but to throw an exception.

```

**Comment by robertbasic** [comment]
@davedevelopment @tpavlek then I'll turn this into a documentation issue and document this, if that's OK with you?

**Comment by davedevelopment** [comment]
Fine by me :+1:
