### ISSUE TITLE
mockPartial has no effect, constructor always called

### ISSUE THREAD

**Issue by Fuzzyma** [mockery/mockery#616]
Hey team,
Albeit I prefer Mockery over phpunits mocks I have several problems with Mockery.
I dont know if I just did not understand it correctly or my code is plain wrong...

I create a mock width:

``` php
\Mockery::mock(MyClass::class)->makePartial()
    ->shouldReceive('someMethod')
    ->andReturn(0)
```

I expect, that this mock does behave like the original class with the exception that someMethod is mocked and returns 0.

However: It does not work. All methods return null instead of only the specified one.

I have to do it the following way to make it work:

``` php
\Mockery::mock(MyClass::class.'[someMethod]')
    ->shouldReceive('someMethod')
    ->andReturn(0)
```

So what I am doing wrong?

Furtermore:
I get the error, that the construction of a mock failed because mockery didnt pass the right amount of arguments to the constructor. I thought, that Mockery wont call the constructor if I do not pass any arguments. I reall need something like `disableOriginalConstructor` here...

**Comment by davedevelopment** [comment]
Can you post an example of the class you are mocking? Preferably an executable script with the behaviour in question, thanks!

**Comment by Fuzzyma** [comment]
I cant deliver you a working script.
The class in question was from Symfony and composer since I wanted to test commands from composer.
The think the code was code was:

```php
// use Symfony\Component\Console\Command\Command;
$command = \Mockery::mock(Command::class)
            ->makePartial()
            ->shouldReceive('run')
            ->andReturn(0)
            ->getMock();
```

I just realized while reviewing this, that I did a mistake on that error. I will check this again.
However the second problem remains:

```php
$repoManager = \Mockery::mock(RepositoryManager::class')->makePartial()
    ->shouldReceive('getLocalRepository')
    ->andReturn($localRepo)
    ->getMock();
```

In the given Code the consructor was called even when I did not apply any arguments. That ofc failed because `RepositoryManager` needs some arguments to be constructed.

I cant say more because I moved on using unpleasant PHPUnit Mocks.
All I have are some outcommented Mockery Mocks

**Comment by quetzyg** [comment]
Hi there,

I bumped into this issue, while trying to find a solution to my own problem.

If I use the `makePartial()` method
```php
        $essence = Mockery::mock('\Impensavel\Essence\SOAP', array(
            $elements,
            'http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL',
            $namespaces,
        ))
        ->makePartial();
```
I'll get the following error
```Fatal error: Call to a member function close() on null in /home/vagrant/GH/essence/src/XML.php on line 118```

If I use the traditional partial mock
```php
$essence = Mockery::mock('\Impensavel\Essence\SOAP[makeCall]', array(
            $elements,
            'http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL',
            $namespaces,
        ));
```
it just works.

This is the [class](https://github.com/impensavel/essence/blob/develop/src/SOAP.php) I'm mocking.

Any pointers to what the problem may be are welcome :)

**Comment by davedevelopment** [comment]
@quetzyg does the parent class `xml` do some work in the constructor? That's the only thing I can think of, something not working in the `parent::__construct` call.

**Comment by davedevelopment** [comment]
@quetzyg scratch that, will look myself, thought it was a link to a gist....

**Comment by davedevelopment** [comment]
Hmmm, I don't get any errors

``` php
<?php

require_once "vendor/autoload.php";

$essence = Mockery::mock('\Impensavel\Essence\SOAP', array(
    [],
    'http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL',
    []
))
->makePartial();

var_dump($essence instanceof \Impensavel\Essence\Soap);             // bool(true)                       
unset($essence);


``` php

**Comment by quetzyg** [comment]
@davedevelopment, yes the `XML` class constructor does handle a few things.

Try using these values:
```php
$elements = array(
    '/soap:Envelope/soap:Body/m:ListOfCountryNamesByCodeResponse/m:ListOfCountryNamesByCodeResult/m:tCountryCodeAndName' => array(
        'map'     => array(
            'code' => 'string(m:sISOCode)',
            'name' => 'string(m:sName)',
        ),
        'handler' => function ($element, array $properties, &$data) {
            var_dump($properties);
        },
    ),
);

// Web Service Definition Language
$wsdl = 'http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL';

// XML namespace
$namespaces = array(
    'm' => 'http://www.oorsprong.org/websamples.countryinfo',
);
```

instead of the empty arrays.

**Comment by davedevelopment** [comment]
@quetzyg 

With those values I get:

```
PHP Fatal error:  Uncaught BadMethodCallException: Method Mockery_0_Impensavel_Essence_SOAP::register() does not exist on this mock object in /home/davem/src/essence/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(16) : eval()'d code:709
Stack trace:
```

That's not unexpected to me, `XML::__construct` attempts to call the `register` method, which at this time has been mocked by mockery, but doesn't have any expectations set for it, nor is the mock a partial yet. I don't think there's any way around this.

**Comment by quetzyg** [comment]
If I use the `makePartial()`, shouldn't I get a class that's pretty much original to what I would have on a normal instantiation?

And the mocked methods would only replace the original ones after?

Why would the `register()`, which belongs to a grandparent (`AbstractEssence` -> `XML` -> `SOAP`) be mocked?

**Comment by davedevelopment** [comment]
The call to `makePartial` comes at what I call runtime. The call to `Mockery::mock` creates and instantiates a mock object, at which point it is a full mockery mock, so all methods (attained via reflection, so methods all the way up the class hierachy) have been replaced with mockery code. When you call `makePartial`, that same mockery code is executed, but it knows to defer the call to the original code. 

The `Mockery::mock("Class[foo]")` is a compile time partial, so you are telling Mockery which methods to replace as it builds the mock.

**Comment by quetzyg** [comment]
I see... 

Well, I'll do things differently, then.

Thanks for your help, @davedevelopment.

**Comment by robertbasic** [comment]
Can this issue now be closed @quetzyg, @davedevelopment?

**Comment by quetzyg** [comment]
Yeah, sure.
