### ISSUE TITLE
Cannot partially mock static method

### ISSUE THREAD

**Issue by rchrd2** [mockery/mockery#620]
I would like to only mock one public static method while keeping the rest of the methods unchanged. The documentation shows how to do this with `$mock->shouldDeferMissing();`, but this isn't working when using `alias:` to load a static class. Is this a known issue or known unsupported feature? Thank you.

Example:

```
<?

use \Mockery as m;

spl_autoload_register(function ($class_name) {
  if ($class_name === 'Foo') {
    class Foo {
      public static function doSomethingExpensive() {
        return "Foo::doSomethingExpensive was CALLED";
      }

      public static function testMe() {
        return array(
          "result" => Foo::doSomethingExpensive(),
        );
      }
    }
  }
});



class PartialStaticMockTest extends \PHPUnit_Framework_TestCase {
  public function testFooStatic() {
    $mock = m::mock('alias:\Foo');
    $mock->shouldDeferMissing();

    // Mock doSomethingExpensive, but we'll call testMe
    $mockedResult = "Foo::doSomethingExpensive was MOCKED";
    $mock->shouldReceive('doSomethingExpensive')
          ->once()
          ->andReturn($mockedResult);

    $val = Foo::testMe();
    $this->assertEquals($mockedResult, $val['result']);
  }

  public function tearDown()
  {
    m::close();
  }
}

```

Result:

```
There was 1 error:

1) PartialStaticMockTest::testFooStatic
BadMethodCallException: Static method Foo::testMe() does not exist on this mock object
```

**Comment by davedevelopment** [comment]
When using `alias`, mockery doesn't load the underlying class at all, it replaces it entirely. We don't go to any efforts examine the file that would have been loaded and create handlers for all of the methods for the class. 

I don't have any intention of adding this kind of behaviour to Mockery, though I wouldn't turn it away as a contribution. I rarely have the need to double static methods and would rather test anything using them through alternative means.

As an alternative, you could use one of the other test double systems available to PHP, particularly [aspect-mock](https://github.com/Codeception/AspectMock), which I think would load your Foo class (if it was in an actual file), adding point cuts to allow the kind of stubbing requires.

**Comment by rchrd2** [comment]
Thank you for confirming this. I just tried `aspect-mock`. It was tricky getting it configured correctly, but once it was setup, it works!

**Comment by robertbasic** [comment]
@rchrd2, @davedevelopment can this issue now be closed if there's another way to do it?

**Comment by robertbasic** [comment]
Closing as @rchrd2 said he got it working using aspect-mock.

Please reopen if this is still an issue.

**Comment by rchrd2** [comment]
Yes. Aspect Mock has continued to work for mocking static methods. Thanks.

**Comment by PowerPan** [comment]
Hey @davedevelopment i have a lot of use cases where i need this feature. 
using Aspect Mock additional is not a cool idea i think.

I think there are a lot of people outside, who are looking for this feature

Please fix this , thx ;)

**Comment by davedevelopment** [comment]
Hi @PowerPan, I honestly don't have the kind of time to implement a feature like this, the way other projects do it is by using the stream wrappers to intercept the autoloading, and rewriting the classes on the fly, it sounds quite complicated.
