### ISSUE TITLE
Mocking multiple interfaces

### ISSUE THREAD

**Issue by FatBoyXPC** [mockery/mockery#628]
Trying this:

```
$mock = m::mock('Fatoyxpc\Cellphpone\Test\TestGateway, Fatboyxpc\Cellphpone\GatewayInterface');
```

Gives this error:

```
1) Fatboyxpc\Cellphpone\Test\GatewayFactoryTest::testCreate
Mockery\Exception: Class name follows the format for defining multiple interfaces, however one or more of the interfaces do not exist or are not included, or the base class (which you may omit from the mock definition) does not exist
```

The `TestGateway` object does not exist, but the `GatewayInterface` does. More importantly, if I don't include the `GatewayInterface` then it works just fine. 

Ultimately I want to do something like this:

```
$mock = m::mock('Fatoyxpc\Cellphpone\Test\TestGateway, Fatboyxpc\Cellphpone\GatewayInterface');

// This method will great a Fatboyxpc\Cellphpone\Test\TestGateway object
$gateway = $this->factory->create('Test');

$this->assertInstanceOf('Fatboyxpc\Cellphpone\Test\Gateways\TestGateway', $gateway);
$this->assertInstanceOf('Fatboyxpc\Cellphpone\GatewayInterface', $gateway);
```

**Comment by davedevelopment** [comment]
I'm not even sure why that error (and checking) exists to be honest. See what you think of #629, I think that should fix the problem and make mockery work how I would prefer it.

**Comment by FatBoyXPC** [comment]
While I like the change to allow defining mock interfaces that don't exist yet, I'm actually concerned here for the fact that `Fatboyxpc\Cellphpone\GatewayInterface` *does* exist and mockery thinks it doesn't. I can't recalll, but I do believe I tried just `GatewayInterface` without a namespace prefixed to it, and along with a `use Fatboypxpc\Cellphpone\GatewayInterface` in the off chance mockery was looking at the test classes use definitions (I'm fairly new to testing so I'm not sure what is and is not possible).

**Comment by davedevelopment** [comment]
@FatBoyXPC I think that's an oversight of that error checking. The message is kind of saying that you don't need to declare a "made up" class at all if you are supplying interfaces, but there are cases (evidently) where you do need to supply a class name.

**Comment by FatBoyXPC** [comment]
So, (not so) strangely enough, I've changed my tests in a way to where I don't even need to run this test anymore. I'll try to describe what I was doing.

I had a class that looked something like this:

```
class GatewayFactory
{
    public function create($gatewayStr, $parameters = [])
    {
        // This class would determine if $gateway was a fully qualified class name or not,
        // and return a FQCN string
        $gatewayStr = $this->getClassName($gatewayStr);

        if (!class_exists($gatewaStry) {
            throw new RuntimeException("Class '$gatewayStr' not found");
        }

        $gateway = new $gatewayStr();

        if (!empty($parameters)) {
            $gateway->initialize($parameters);
        }

        return $gateway;
    }
}
```

The test I posted in the OP was making sure that:
1. The `create()` returns the specific Gateway object according to the string provided
2. The returned Gateway object implements `GatewayInterface`
3. And importantly: that the Gateway's `initialize()` method gets called

What I ended up doing was creating a method `createGateway($fqcn)` which accepts a FQCN string, and has the logic to check if it exists and return it or throw the runtime exception.

Doing this allowed me to mock the method and return the mocked class and such.

Later, I ended up making `createGateway()` protected/private. I was still able to mock it, but I've been reading opinions on how protected/private methods should not be tested. What are your thoughts on how to handle this? I had to mock the `createGateway()` method to make sure it returned what I wanted it to, or am I just testing it incorrectly? Mocking it means it doesn't receive adequate coverage.

**Comment by davedevelopment** [comment]
I think I'd need a full example to make a proper judgement, but either way, It's a bit horses for courses. People will talk about you shouldn't mock protected methods, but it would be fine if you extracted the exact same code out to another object to be injected in etc. If you are confident in your coverage, I wouldn't sweat it.

**Comment by FatBoyXPC** [comment]
Yeah, ultimately I'm able to test that the method works/doesn't work by making sure that RuntimeException bubbles up to the method I'm calling it from, so it's all good!

**Comment by FatBoyXPC** [comment]
Sorry, didn't mean to close this. There's still that open PR which is totally relevant to this!

**Comment by robertbasic** [comment]
@FatBoyXPC @davedevelopment given that the related PR got merged, can this issue now be closed?

**Comment by robertbasic** [comment]
Closing as #629 was merged.

Please reopen if this is still an issue.

**Comment by FatBoyXPC** [comment]
The only reason I left it open was due to the PR. Since my code was updated to where this wasn't an issue for me, and the PR got closed, sounds like closing this was the right call to me :stuck_out_tongue:
