### ISSUE TITLE
Mockery\Expectation->matchArgs fails on nightly

### ISSUE THREAD

**Issue by raphaelstolt** [mockery/mockery#648]
Might be due to doing a `count` on an element that's not an array or object that implements Countable. Stumbled over it via [this](https://travis-ci.org/jonathantorres/construct/jobs/180472473) Travis CI build.

**Comment by davedevelopment** [comment]
Not had a look yet, but could be related to #646

**Comment by robertbasic** [comment]
@raphaelstolt is this still an issue? I don't see anything on the linked travis build, the job log is empty?

**Comment by raphaelstolt** [comment]
In current Travis CI builds this seems to be no more an issue. Closing the issue.
