### ISSUE TITLE
Nullable return types get TypeError on null

### ISSUE THREAD

**Issue by camuthig** [mockery/mockery#654]
7.1 nullable return types are throwing a `TypeError` if the mock attempts to return null for the function. It looks like when the mocks are created, they are not taking into account the new `allowsNull` function on the `ReflectionType` class. 

I already have a fix for my team on this so will be PRing it shortly.

**Comment by davedevelopment** [comment]
Closed by #655

**Comment by robertbasic** [comment]
@camuthig @davedevelopment can this issue now be closed then?

**Comment by robertbasic** [comment]
Closing issue as #655 was merged.

Please reopen if this is still an issue.
