### ISSUE TITLE
mockery close() does not close the mock object

### ISSUE THREAD

**Issue by sasmitung** [mockery/mockery#657]
I have 3 tests which use the same mockery object (the mockery object is set in the setUp). If I run the test individually, each of them will pass. But when I run the tests all together, only the first expectation will succeeded. The 2nd and 3rd will wont count the mockery method call.

    public function test_onCreated (){
        $obj = new Object();
        $this->eventHandler->shouldReceive('onCreated')->once();
        Event::fire('created', $obj );
    }
    
    public function test_onUpdated (){
        $obj = new Object();
        $this->eventHandler->shouldReceive('onUpdated')->once();
        Event::fire('updated', $obj );
    }
    
    public function test_onCompanyDeleted (){
        $obj = new Object();
        $this->eventHandler->shouldReceive('onDeleted')->once();
        Event::fire('deleted', $obj );
    }
    
    private $appLogger;
    private $eventHandler;
    
    public function setUp() {
        parent::setUp();
        $this->appLogger = new AppLogger();
        $mock = Mockery::mock('EventHandler['
                . 'onCreated,'
                . 'onUpdated,'
                . 'onDeleted]', [$this->appLogger]);
        $this->eventHandler = $mock;
        $this->app->instance('EventHandler', $this->eventHandler);
    }
    
    public function tearDown() {
        Mockery::close();
        parent::tearDown();
    }

If I put this line `Mockery::getContainer()->mockery_close();` in the tearDown, all of the test pass.
Did I miss something? Why can't I have only one mockery object in the setUp for all of my test method? Should not a new mockery object created every time a test run (due to the setUp and teardown)?

**Comment by sasmitung** [comment]
The problem is that the ioc will only set the first eventHandler bind to the app.  

When the test_onCreated runs, the app will call the first eventHandler to handle the event (duh)
However, when the test_onUpdated runs, the app will still call the first eventHandler to handle the event, but asserts the expectation from the 2nd created eventHandler, which is why the expectation on the 2nd eventHandler is never fulfilled.

Thus, a static eventHandler mock (and one time bind the instance to the app) will do the job. 

    private static $eventHandler;
    
    public function setUp() {
        parent::setUp();
        if(is_null(self::$eventHandler)){
            self::$eventHandler = Mockery::mock('EventHandler['
                . 'onDeleted,'
                . 'onUpdated,'
                . 'onCreated]');
            $this->app->instance('EventHandler', self::$eventHandler);
        }
    }

**Comment by sasmitung** [comment]
this also happens if I run several test files together. Say, first test file has a mockery of EventHandler, then the expectation will be carried on to the next test file which also has a mockery of EventHandler.

**Comment by davedevelopment** [comment]
I'm not sure about this, it's a little ambiguous without knowing the internals of `Event` and `EventHandler`, although I assume it's Laravel? 

Trying to recreate it based on the usage seems to work for me.

``` php
<?php // test.php

require "vendor/autoload.php";

class AppLogger {}
class Object {}

class EventHandler {
    function __construct($logger) {}
	function onUpdated($subject) {}
	function onDeleted($subject) {}
	function onCreated($subject) {} 
}

class Event {
	static $handler;

    static function fire($event, $subject) {
        $method = "on".ucfirst($event);
		static::$handler->$method($subject);
	}
}

class TestTest extends PHPUnit_Framework_TestCase
{
	public function setUp() {
		parent::setUp();
		$this->appLogger = new AppLogger();
		$mock = Mockery::mock('EventHandler['
				. 'onCreated,'
				. 'onUpdated,'
				. 'onDeleted]', [$this->appLogger]);
		$this->eventHandler = $mock;
		Event::$handler = $this->eventHandler;
	}

	public function tearDown() {
		Mockery::close();
		parent::tearDown();
	}
	public function test_onCreated (){
		$obj = new Object();
		$this->eventHandler->shouldReceive('onCreated')->once();
		Event::fire('created', $obj );
	}

	public function test_onUpdated (){
		$obj = new Object();
		$this->eventHandler->shouldReceive('onUpdated')->once();
		Event::fire('updated', $obj );
	}

	public function test_onCompanyDeleted (){
		$obj = new Object();
		$this->eventHandler->shouldReceive('onDeleted')->once();
		Event::fire('deleted', $obj );
	}
}

```

**Comment by sasmitung** [comment]
@davedevelopment  Yes, the framework is Laravel.

the Applogger only writes in the log file.
the object/subject extends the Ardent.

the onUpdate etc more or less are like this:
````
function onUpdated($subject) {
    $data = [$subject->data];
    $this->appLogger->log(Event:firing(), $data);
}
````

another case, but similar problem: I have a mock of a Facade, 
````
File::shouldReceive('deleteDirectory')->once()->andThrow('Exception');
File::makePartial();
````
the test would pass if I run the test individually. But if I run it as a test suite, then the first test which contains this mock will pass, but the following (which also contains this mock) will fail. The exception is that the mock is called more than once. The mock object seems also to continue living to the other test file, until it can throw its exception.

It's like sometimes it works sometime it is not :( did I make mistake/missing something somewhere?

**Comment by davedevelopment** [comment]
> It's like sometimes it works sometime it is not :( did I make mistake/missing something somewhere?

There must be something somewhere. Are you able to package up a minimal reproduction in to a tarball and send it to me? Email is in my bio https://github.com/davedevelopment

**Comment by sasmitung** [comment]
I tried to make the minimal reproduction version, and then all works as expected :'D
okay, I'll take a look again @davedevelopment

**Comment by robertbasic** [comment]
@sasmitung can this issue now be closed? Thanks!

**Comment by ctrlaltdylan** [comment]
Just want to bump this for the same mysterious behavior in Codeception. Also want to mention that I included `Mockery::close();` in the `_after` method.

**Comment by robertbasic** [comment]
@ctrlaltdylan please open a new ticket with as much detail as possible, thanks!
