### ISSUE TITLE
Allow closure spies

### ISSUE THREAD

**Issue by tflori** [mockery/mockery#711]
Currently I write something like this when I want to test that a closure gets executed:

```php
class SomethingTest extends TestCase 
{
  public function testSomething()
  {
    $spy = [
      'callCount' => 0,
      'args' => []
    ];
    
    aFunction(function () use (&$spy) {
      $spy['callCount']++;
      $spy['args'][] = func_get_args();
    });

    self::assertSame(1, $spy['callCount']);
    self::assertSame(['what', 'ever'], $spy['args'][0]);
  }
}
```

dependent from what I want to test of course. I'm wondering that there is no spy. In jasmine for example your write:

```js
describe('something', function() {
  it('calls the callback', function() {
    var spy = jasmine.createSpy('callback');
    
    aFunction(spy);

    expect(spy).toHaveBeenCalledWith('what', 'ever');
  });
});
```

Sounds some bit more easy, readable and understandable.

Ok, thats not your problem - phpunit is differnt. But you could provide a spy. I just saw that there is a method `Mockery::spy()` but when I see it correct is again to create a Spy for an Interface. I want to spy a closure. Ok spy is taken and I guess you don't want to change the current behavior for spy.

My suggestion:

```php
class SomethingTest extends TestCase 
{
  public function testSomething()
  {
    $spy = \Mockery::createSpy('callback');
    
    aFunction($spy);

    $spy->shouldHaveBeenCalled()->with('what', 'ever')->once();
  }
}
```

**Comment by davedevelopment** [comment]
I'd be open to providing something like this. We could code up something specific, or we could utilise the existing code and effectively do something like:

```
class CallableSpy {
    public function __invoke() {}
    public function shouldHaveBeenCalled() {
        return $this->shouldHaveReceived("__invoke");
    }
}

$mock = Mockery::spy(CallableSpy::class)->makePartial();
$mock(123);
$mock->shouldHaveBeenCalled()->with(123);
```

My preferred syntax would be something like 

```
Mockery::spy(function() {});
```

I think it's fairly clear that it's a spy for a callable, and we could also further it to make it partial spy etc.

```
Mockery::spy(function($number) { return $number+1; });
```

**Comment by tflori** [comment]
yes, thats good for me too.

**Comment by davedevelopment** [comment]
@tflori see #712, let me know your thoughts on there.

**Comment by robertbasic** [comment]
Closing as #712 got merged.
