### ISSUE TITLE
Deprecate makePartial() as it proxies to shouldDeferMissing()

### ISSUE THREAD

**Issue by joshbrw** [mockery/mockery#713]
Does it make sense to have both `Mock::makePartial()` and `Mock::deferMissing()`? `makePartial()` simply proxies to `shouldDeferMissing()` so may it be worth deprecating one?

**Comment by davedevelopment** [comment]
Hey @joshbrw, I think we should deprecate one, but I'm loath to break BC on such a simple library. I wouldn't want to raise `E_USER_DEPRECATED` in library that's specifically made for testing, but I guess we could use `@deprecated` in the docblocks.

I think I'd sway towards deprecating `shouldDeferMissing`, it's a better description of what it does under the hood, but `makePartial` gives more understanding from an API perspective. In the same way, `makeSpy` or something similar would probably be a good one to proxy to `shouldIgnoreMissing`, and deprecate the direct call.

**Comment by joshbrw** [comment]
Hey @davedevelopment yeah I completely agree about breaking backwards compatibility. I'd agree with deprecating via docblock and then potentially raising `E_USER_DEPRECATED` after a suitable length of time (no idea what that length of time would be). I'd also agree with keeping `makePartial()` as it is a better description, it's also the method mentioned in the documentation.

**Comment by robertbasic** [comment]
Done with #839
