### ISSUE TITLE
nullable function returns 0 when using andReturnNull()

### ISSUE THREAD

**Issue by sota1235** [mockery/mockery#726]
When mocking nullable function and specify to return `null`, it will return `0`.
Like this.

## Test target file

```php
<?php
declare(strict_types);

class Hoge
{
    public function count(): ?int
    {
        //
    }
}
```

And test file.

```php
<?php
declare(strict_types=1);

use Mockery as m;

class HogeTest extends \PHPUnit_Framework_TestCase
{
    public funcion testCount()
    {
        $mockHoge = m::mock(Hoge::class);
        $mockHoge->shouldReceive('count')->andReturnNull(); // It will be not null, but 0
    }
}
```

Is there any problem in my code? Or is it bug?
Thank you :)

## Environment

- mockery/mockery 0.9.9
- PHP 7.1.0

Maybe this issue is related to #654

**Comment by davedevelopment** [comment]
Looks like a bug in `0.9.x`, `master` gives me null:

``` php
<?php
declare(strict_types=1);

require_once 'vendor/autoload.php';

Mockery::setLoader(new Mockery\Loader\RequireLoader(sys_get_temp_dir()));
Mockery::globalHelpers();

class Hoge
{
    public function count(): ?int
    {
        //
    }
}

$mockHoge = mock(Hoge::class);
$mockHoge->shouldReceive('count')->andReturnNull();
var_dump($mockHoge->count()); // NULL
```

**Comment by sota1235** [comment]
Oh, it seems to look. I will try it!

**Comment by jimenezmaximiliano** [comment]
@sota1235 Replace it with ->andReturn(null) and it works

**Comment by michaelcullum** [comment]
This is a more significant bug when type hinting things like DateTimeInterface as then it will try to implement the interface which cannot be implemented in userland.

Example

```
function fooBar(): ?DateTimeInterface
{
    return;
}

$blah->shouldRecieve('fooBar')->andReturnNull();
```

Resulting error:
`Method Mockery_8_Class::fooBar() does not exist on this mock object`

**Comment by robertbasic** [comment]
Using Mockery v1, this works as expected:

``` php
<?php declare(strict_types=1);

class Foo
{
    public function bar(): ?DateTimeInterface
    {
        return new DateTime('now');
    }
}

$foo = \Mockery::mock(Foo::class);
$foo->shouldReceive('bar')->andReturnNull();

var_dump($foo->bar());
```

gives an output of:

```
robert@odin ~/projects/mockery[master*]$ php adhoc-tests/issue726.php 
/home/robert/projects/mockery/adhoc-tests/issue726.php:16:
NULL
```

Given that [Mockery v1 was tagged](https://github.com/mockery/mockery/releases/tag/1.0) last week, I'm going to close this issue as it relates to 0.9.x.

Please upgrade to Mockery v1 at your earliest convenience.

If you still have problems with this after the upgrade, please open a detailed issue about it.

Thanks!
