### ISSUE TITLE
PHPUnit 6 support

### ISSUE THREAD

**Issue by padraic** [mockery/mockery#728]
Hey @davedevelopment, are there any blockers to this other than renaming test classes/ exception methods where appropriate in the tests? I see a few conflicts over on Humbug repos, I'd like to resolve. So happy to do a PR over the weekend.

**Comment by davedevelopment** [comment]
No blockers I am aware of, fire away. I think we fixed one thing in #691 (and then reverted slightly in #708).

**Comment by davedevelopment** [comment]
#708 says we're dropping support for PHPUnit <5.4, I'd like to try and keep compatibility with everything after that if we can.

**Comment by padraic** [comment]
I'm assuming 5.4 is 5.6?

**Comment by padraic** [comment]
Next question - how tied are we to supporting the TestListener post PHPUnit 5? The problem that I see is that it's method signature for endTest() is effectively dead after 5.7 so we can't cross-support it without building a new one. It would be easier to skip the tests for it in 6.0+.

**Comment by davedevelopment** [comment]
I meant PHPUnit 5.4, I was told that they added `\PHPUnit\Framework\TestCase` in that release, so we've extended that one in the `MockeryTestCase` class.

I consider the listener as deprecated really, it's been turned in to some sort of fail safe for now. There is a PR to convert it to PHPUnit 6 (#695), but I was hoping to support both going forward, looks like that wont happen. Happy to see the tests skipped for the listener for now.

**Comment by padraic** [comment]
I can try lowering it in Travis (well, try it here first!)- currently that's set to 5.7.

**Comment by davedevelopment** [comment]
It depends which way you are looking at it though and it's hard to test! To me `require-dev` tells us the PHPUnit version that is required to run our test suite, not the PHPUnit version that Mockery attempts to be compatible with, if that makes sense?

**Comment by padraic** [comment]
Ahh, understood. That is tricky to check. Running our own tests under 5.4 would at least pick out any class name misses (e.g. if the forward compatibility shim is less developed back then). At least, that's been the main problem moving require-dev to 6.1, and usually in the places where we do directly use phpunit classes.

**Comment by ascii-soup** [comment]
Any movement on this?

**Comment by davedevelopment** [comment]
I'm a bit lost on where we are with it to be honest, will see if I can review this week.

**Comment by jasonetwork** [comment]
Any updates on getting Mockery compatible with the latest version of PHPUnit?

**Comment by dbudwin** [comment]
I would also like to see movement on this.  I get a lot of failed test using PHPUnit 6.2 that passed in 5.* due to the error "This test did not perform any assertions."  I'm aware that I can use a command line argument to disable this, but I'd prefer it to work with Mockey as expected.  A lot of my tests, the test is that a function gets called as expected using `shouldReceive()` without a traditional `assert` statement.

**Comment by davedevelopment** [comment]
@dbudwin unfortunately PHPUnit made changes that prevent us from doing this with the listener (see #376), so you will have to either extend the [MockeryTestCase](https://github.com/mockery/mockery/blob/master/library/Mockery/Adapter/Phpunit/MockeryTestCase.php) or `use` the [MockeryPHPUnitIntegration](https://github.com/mockery/mockery/blob/master/library/Mockery/Adapter/Phpunit/MockeryPHPUnitIntegration.php). The Base class and the trait are fully compatible with PHPUnit 6 as far as I am aware, Mockery's own tests use the base class and at least one of the travis runs [uses PHPUnit 6.2.2](https://travis-ci.org/mockery/mockery/jobs/245799149).

**Comment by jasonetwork** [comment]
Extending the MockeryTestCase or using the MocheryPHPUnitIntegration trait still causes unexpected/unwanted results. When performing a PHPUnit test, any failed expectations are displayed as "errors" instead of "failures" in the results.

**Comment by dbudwin** [comment]
@davedevelopment Using that trait appears to have solved the trick! 👍 

@jasonetwork I do not have any further errors or unexpected results, but I will be mindful in the future if I see anything unexpected.

**Comment by davedevelopment** [comment]
@jasonetwork sure, I'd be happy to see that fixed.
