### ISSUE TITLE
[Question] Hidden Mockery expectation exceptions when production code catching Exception

### ISSUE THREAD

**Issue by kathiedart** [mockery/mockery#730]
Hi,

I get a lot of hidden errors when production code catches the bare Exception class (as I don't know what it might be) because it also includes any errors Mockery might give me.

Is there a way (purely on the test side) to see these, and not get them caught by my production error handler?

Can Mockery give me errors instead of exceptions? What would be the best way to go about this aside from just not catching Exception?

Cheers

**Comment by robertbasic** [comment]
Hi @kathiedart!

Mind providing some small examples that replicate the issue you're encountering?

Thanks!

**Comment by robertbasic** [comment]
I think #613 is the same issue, and as @davedevelopment stated there, the application should deal with the exceptions in a better way.

**Comment by kathiedart** [comment]
Thanks for reading. It is indeed the same - catching Exception in #613 causes for instance any expected but un-mocked method exceptions to be caught by the application handler.
