### ISSUE TITLE
Fix read the docs configuration

### ISSUE THREAD

**Issue by robertbasic** [mockery/mockery#741]
Whoever has control over read the docs configuration should probably update it so it points to the new repository, as well as turn off PDF generation, because the builds keep failing with:

```
Error
No TeX files were found
```

**Comment by davedevelopment** [comment]
Ah, only just seen your tweet and then this....

**Comment by davedevelopment** [comment]
Fixed in 128608f262b44360f7e3e86e6eae73f448398711
