### ISSUE TITLE
Which version is the latest (0.9.9 or 1.0.0-alpha1)?

### ISSUE THREAD

**Issue by GuyPaddock** [mockery/mockery#753]
It seems like 0.9.9 and 0.9.8 both came out AFTER 1.0.0-alpha1, and the branches for these versions diverged after 0.9.4.

So... which version is actually the latest? Any reason to use 0.9.9 instead of 1.0.0-alpha1?

**Comment by davedevelopment** [comment]
Hello. 1.0.0-alpha1 is the latest. Occasionally people want fixes back porting to the 0.9 branch and if they are happy to send a PR in, I usually merge and tag a 0.9 release for them, hence the recent tags on that branch.
