### ISSUE TITLE
Multiple demeter chains on multiple objects

### ISSUE THREAD

**Issue by mjpvandenberg** [mockery/mockery#768]
There is a problem when defining multiple demeter chains on multiple mocks. Mockery will not recognize the second expectation of the second mock. Here's a basic unit test.

```php
public function testDemeterChains()
{
    $mock1 = Mockery::mock('object')->shouldIgnoreMissing();
    $mock2 = Mockery::mock('object')->shouldIgnoreMissing();

    $mock1->shouldReceive('getElement->getFirst')->andReturn(1);
    $mock1->shouldReceive('getElement->getSecond')->andReturn(2);
    $mock2->shouldReceive('getElement->getFirst')->andReturn(3);
    $mock2->shouldReceive('getElement->getSecond')->andReturn(4);

    $this->assertEquals(1, $mock1->getElement()->getFirst());
    $this->assertEquals(2, $mock1->getElement()->getSecond());
    $this->assertEquals(3, $mock2->getElement()->getFirst());
    $this->assertEquals(4, $mock2->getElement()->getSecond());
}
```

The last assertion will throw an exception: `Method Mockery_1__demeter_getElement::getSecond() does not exist on this mock object`. I'm using Mockery 0.9.9.

**Comment by davedevelopment** [comment]
Thanks for the detailed report, I have no idea why that might be off the top of my head.

**Comment by macdabby** [comment]
I can confirm I'm getting the same on the current master branch:

        $mock = Mockery::mock('Package\Model1');
        $mock->shouldReceive('select->some->data')->andReturn(1);
        $mock->shouldReceive('select->some->other->data')->andReturn(2);
        $mock = Mockery::mock('overload:Package\Model2');
        $mock->shouldReceive('select->some->data')->andReturn(3);
        $mock->shouldReceive('select->some->other->data')->andReturn(4);

        $out1 = Model1::select()->some()->data();
        $out2 = Model1::select()->some()->other()->data();
        $out3 = Model2::select()->some()->data();
        $out4 = Model2::select()->some()->other()->data();

    Method Mockery_1__demeter_some::other() does not exist on this mock object

**Comment by macdabby** [comment]
I'm not entirely sure how this works, but it almost looks as if the second shouldReceive() call is adding the new chain to the first mock object. It would make sense that some data is bleeding through since these are static methods and likely static vars, but it seems that these are recreated in some eval() process that should isolate them.

**Comment by robertbasic** [comment]
It's not about the order of calls, but the order of setting up expectations.

This breaks:

``` php
<?php

require_once 'vendor/autoload.php';

$mock1 = Mockery::mock('object')->shouldIgnoreMissing();
$mock2 = Mockery::mock('object')->shouldIgnoreMissing();

$mock1->shouldReceive('getElement->getFirst')->andReturn(1);
$mock1->shouldReceive('getElement->getSecond')->andReturn(2);
$mock2->shouldReceive('getElement->getFirst')->andReturn(3);
$mock2->shouldReceive('getElement->getSecond')->andReturn(4);

$mock2->getElement()->getSecond();
```

This doesn't:
``` php
<?php

require_once 'vendor/autoload.php';

$mock1 = Mockery::mock('object')->shouldIgnoreMissing();
$mock2 = Mockery::mock('object')->shouldIgnoreMissing();

$mock1->shouldReceive('getElement->getFirst')->andReturn(1);
$mock1->shouldReceive('getElement->getSecond')->andReturn(2);
$mock2->shouldReceive('getElement->getSecond')->andReturn(4);
$mock2->shouldReceive('getElement->getFirst')->andReturn(3);

$mock2->getElement()->getSecond();
```

Investigating further.

**Comment by robertbasic** [comment]
When creating a mock for the `getSecond` demeter mock, this branch gets hit https://github.com/mockery/mockery/blob/b3749e485d200cb95c5778193b0aa70c2c8e8003/library/Mockery/Container.php#L441 which ends up making Mockery not see the correct mock object here https://github.com/mockery/mockery/blob/b3749e485d200cb95c5778193b0aa70c2c8e8003/library/Mockery/Container.php#L258 and then the expectation for `getSecond` ends up being set on the incorrect mock object.

**Comment by macdabby** [comment]
Based on that, it looks like the original mock is the name of the class so those are not confused. Then a second mock Mockery_0__demeter_getFirst is created and recognized as storage for both because it's the same name. If that's where it's getting confused, the naming scheme for those demeter mocks should include the name of the original class that was mocked, or maybe a sha1 hash of the full class path?

**Comment by macdabby** [comment]
This fixes the problem :)

**Comment by mjpvandenberg** [comment]
This is still/again a problem in v1.2.0
