### ISSUE TITLE
Cannot mock interface with method name: catch

### ISSUE THREAD

**Issue by dnaber-de** [mockery/mockery#770]
I'm using Mockery 0.9.9 with PHP 7.0.21 and want to mock the following interface:

```php

interface Catcher {

    public function catch( \Throwable $e );
}
```
Mocking this interface with Mockery like so:
```php
$catcher = \Mockery::mock( Catcher::class );
```
Throws an error:
```
Fatal error: Class Mockery_0_Catcher contains 1 abstract method
and must therefore be declared abstract or implement the remaining
methods (Catcher::catch) in .../vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(16) :
eval()'d code on line 25
```

For what I see, the generated code that is evaluated doesn't contain the method `catch`. The problem does not depend on the actual interface name and it's only about that specific method name. Also, there's no issue with _classes_ that contains a method `catch`.

**Comment by lougreenwood** [comment]
I believe that I'm battling the same issue right now, however my interface name is different:

**Interface:**
```
<?php 

namespace Theme\Models\Factories;

interface IFactory
{

	/**
	 * Creates a new instance of the factory's object.
	 * @param  string $params Params used to initialise the new object.
	 * @return object         Returns a new object instance of the class.
	 */
	public function new( array $params );

}
```

**Mock**
```
        $some_factory = Mockery::mock( Factories\IFactory::class )();
        $some_factory
                ->shouldReceive('new')
                    ->with( Mockery::any() )
                    ->andReturn( $mock_lookup_request )                    
                ->shouldReceive('new')
                    ->with( hasEntry('registration_id', '666') )
                    ->andReturn( $mock_lookup_request_error );
```

```
FATAL ERROR. TESTS NOT FINISHED.
Class Mockery_2_Theme_Models_Factories_IFactory contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Theme\Models\Factories\IFactory::new)
in vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(16) : eval()'d code:25
```

**Comment by lougreenwood** [comment]
That was quick - seems that I was able to fix my issue by using a 'Generated Partial Test Double':

http://docs.mockery.io/en/latest/reference/creating_test_doubles.html#generated-partial-test-doubles

Mock code now looks like:
```
        $some_factory = Mockery::mock( Factories\IFactory::class.'[new]' );
        $some_factory
                ->shouldReceive('new')
                    ->with( Mockery::any() )
                    ->andReturn( $mock_lookup_request )                    
                ->shouldReceive('new')
                    ->with( hasEntry('registration_id', '666') )
                    ->andReturn( $mock_lookup_request_error );
```

@dnaber-de - maybe this will help you... 👍

**Comment by dnaber-de** [comment]
Yes, that's a functional work around. However I think it should be possible without that as both `catch` and `new` are valid method names (at least in PHP 7).

**Comment by davedevelopment** [comment]
Working in master:

``` php
<?php
declare(strict_types=1);

require_once 'vendor/autoload.php';

Mockery::setLoader(new Mockery\Loader\RequireLoader(sys_get_temp_dir()));
Mockery::globalHelpers();

interface Catcher {
    public function catch(\Throwable $e );
}

$catcher = \Mockery::mock( Catcher::class );
var_dump(phpversion()); // string(6) "7.0.12"
var_dump(get_class($catcher)); // string(17) "Mockery_0_Catcher")
```

It looks like a3ceb90a was the beginning of this work, but there may have been others since. I'll be happy to accept the feature backported to the the 0.9 branch, but I would recommend moving to the master branch, or 1.0.0-alpha if you want a tagged release.

**Comment by dnaber-de** [comment]
For when is the 1.0.0 release planned? I mean a backport to the 0.9 branch won't make much sense if 1.0.0 will be released next week. :wink:

**Comment by davedevelopment** [comment]
Now that's a question....

Definitely not next week. I've been slack on this, so I'll go out on a limb and say we'll shoot for October 1st for Mockery 1.0.
