### ISSUE TITLE
[0.9.4][bug] Expectation::verify() should return boolean

### ISSUE THREAD

**Issue by Cyrille37** [mockery/mockery#776]
Hi,

The method `Expectation::verify()` should return a boolean, but return nothing.

Cheers.

**Comment by GrahamCampbell** [comment]
What about the latest version>

**Comment by Cyrille37** [comment]
version 0.9.4 is the one required by Laravel 5.4, so used by many people :-)

**Comment by GrahamCampbell** [comment]
Laravel 5.4 does not require 0.9.4?

**Comment by Cyrille37** [comment]
Yes, my report is about v0.9.4

**Comment by GrahamCampbell** [comment]
Ok, my point is that bug reports for old versions are invalid. Please upgrade to the latest 0.9.x.

**Comment by robertbasic** [comment]
Closing this issue as [Mockery 1 was tagged](https://github.com/mockery/mockery/releases/tag/1.0) last week.

Please upgrade to Mockery 1 at your earliest convenience.

If you still have the same problem on v1, please open a new issue detailing your problem.

Thank you!
