### ISSUE TITLE
Release an intermediate version

### ISSUE THREAD

**Issue by sebastiaanluca** [mockery/mockery#787]
Would it be possible to release an intermediate 0.9.10 or 1.0.1-alpha1 version that includes the latest changes and fixes from master? The latest version dates from the end of February, so it's been a while already.

Asking because I'm currently running into https://github.com/mockery/mockery/pull/718 on PHP 7.2 (which is to be released quite soon too) and I can't depend on master for a production/stable package.

Thank you.

**Comment by davedevelopment** [comment]
Hi there, I'm planning on releasing 1.0 around the start of October.

**Comment by sebastiaanluca** [comment]
Perfect, thanks!
