### ISSUE TITLE
unable to mock PHP 7.1 nullable arguments

### ISSUE THREAD

**Issue by kgkg** [mockery/mockery#790]
I have method in class Player:
`public function setEquipData(?array $rawItemsList): Player`

when I use in test:
`$player = \Mockery::mock('Player')->makePartial();`

I get error:

> Declaration of Mockery_0_Player::setEquipData(array $rawItemsList): Player should be compatible with Player::setEquipData(?array $rawItemsList): Player
>  C:\usr\htdocs\game\vendor\mockery\mockery\library\Mockery\Loader\EvalLoader.php:16
>  C:\usr\htdocs\game\vendor\mockery\mockery\library\Mockery\Container.php:219
>  C:\usr\htdocs\game\vendor\mockery\mockery\library\Mockery.php:79

Of course if I change definition to: 
`public function setEquipData(array $rawItemsList = null): Player`
everything is ok.

**Comment by robertbasic** [comment]
@kgkg what version of mockery are you using? This should be possible on latest master already.

**Comment by kgkg** [comment]
@robertbasic I use mockery/mockery 0.9.9 
in composer.json I have included "mockery/mockery": "*" and composer update doesn't find any new version.

**Comment by kgkg** [comment]
Also I discovered that:
public function setEquipData(?array $rawItemsList = null) -> works
public function setEquipData(?array $rawItemsList) -> doesn't work

**Comment by robertbasic** [comment]
@kgkg try requiring it as `"mockery/mockery": "dev-master"` as we don't have a stable 1.x version yet. We should have one though, soon!

**Comment by kgkg** [comment]
After updating to dev-master it works like a charm. 
Thanks alot for help and for creating this great library :)

**Comment by robertbasic** [comment]
@kgkg you're welcome! I'll close this issue then.
