### ISSUE TITLE
Clean up PHPUnit integration documentation

### ISSUE THREAD

**Issue by robertbasic** [mockery/mockery#792]
As we now have a PR for 1.0.0 (#791), I think it's due time for me to clear up the PHPUnit integration documentation https://github.com/mockery/mockery/blob/87fc5f641657833f7c96f14ed3067effe94a0824/docs/reference/phpunit_integration.rst

Main thing to clean and clear up is which way of integration works for PHPUnit >= 6, and which for PHPUnit < 6.

**Comment by robertbasic** [comment]
I guess we dropped support for phpunit 5.x in the test listener https://github.com/mockery/mockery/pull/786

**Comment by robertbasic** [comment]
@davedevelopment for PHPUnit 6, even when using the listener, we still need to manually call `\Mockery::close()` in `tearDown` or use Mockery's trait? What's the point of the listener then?

I'm thinking noting in the docs that the listener is deprecated and shouldn't be used at all, and to urge users to upgrade by using the trait/extending the mockery base class.

**Comment by robertbasic** [comment]
Ping @davedevelopment

**Comment by davedevelopment** [comment]
Sorry, missed the notifications...

Yes, you need to manually call `Mockery::close`, as `TestListener::endTest` is too late for Mockery to do anything about adding to the expectation count and apparently shouldn't be done in a listener anyway. The TestListener is there now purely as a fail safe, so if they forget to call `Mockery::close`, it should throw up. I don't plan on using it.
