### ISSUE TITLE
Clean up the readme

### ISSUE THREAD

**Issue by robertbasic** [mockery/mockery#796]
In #793 the reporter said that our readme states that the new ``allows/expects`` way of setting expectations is the recommended way. I tend to disagree with this and it should be noted that this is only one way of creating expectations and that the "old" way is still here and working.

I also think that mentioning the new way will lead to a lot of confusion with the existing users as they'll now see in the readme only allows/expects examples and might think that the shouldReceive is gone in 1.0.0., and that for upgrading they'd have to change all the calls.

I have no problem with calling the new way the recommended way, but I'd like that to happen when we're certain that it is... as versatile, as the old way is (see #748).

**Comment by davedevelopment** [comment]
:+1:
