### ISSUE TITLE
allowMockingMethodsUnnecessarily method is not working

### ISSUE THREAD

**Issue by hhovakimyan** [mockery/mockery#804]
I am new to Mockery and when I came out on documentation page about Mockery global configuration, I read about **allowMockingMethodsUnnecessarily** function, which purpose is to notice/don't notice about not fulfilled expectations.  I added it to a part in my code which is included everywhere, but I saw no changes applied. 
My code for setting Mockery global configuration:
`\Mockery::getConfiguration()->allowMockingMethodsUnnecessarily(false);`

My unit test part which is not telling me about mistake
` $myClassMock = \Mockery::mock('alias:' . MyClass::class);`
`$myClassMock->shouldReceive('isValueValid')->once()->andReturn(true);`
`$myClassMock->shouldReceive('createErrorMessage');`

The code part unit test is written for.

> 
        $validationErrors = [];
        $isValid = MyClass::isValueValid(
            'Valid value',
            [
                new NotEmpty(),
            ],
            $validationErrors
        );

        if (!$isValid) {
            $message = MyClass::createErrorMessage($validationErrors)
             
           var_dump($message);
        }

>         

From this code part you can guess that, the units must complain about 
`$myClassMock->shouldReceive('createErrorMessage');`
Because `createErrorMessage` is never called. But I get nothing.

When I put change this line like `$myClassMock->shouldReceive('createErrorMessage')->once()`, unit test fails, but it is independent of value which is passed to `allowMockingMethodsUnnecessarily` function.

My question is, am I missing something when specifying global configuration or do I have some misunderstanding of the purpose of this config?

And also one little note: When I looked up in code I saw that `_allowMockingMethodsUnnecessarily` property and `mockingMethodsUnnecessarilyAllowed` method of `\Mockery\Configuration` class are never used from outside.

**Comment by davedevelopment** [comment]
Welp, I've not even seen that configuration item before. Commit dates back to 2010 and I'm unaware of it ever being used. 

I'm very sorry for our documentation having wasted your time.

**Comment by robertbasic** [comment]
@davedevelopment remove from documentation and throw a deprecation notice in code? Or just remove it from code as well?

**Comment by davedevelopment** [comment]
@robertbasic remove from docs and deprecation notice I think, what about you?

**Comment by robertbasic** [comment]
@davedevelopment the same. Will send a PR this week (if someone doesn't beat me to it!)
