### ISSUE TITLE
Methods are not hinted properly in 1.0

### ISSUE THREAD

**Issue by neomerx** [mockery/mockery#810]
Such methods as `with`, `withNoArgs`, `withAnyArgs`, `times` and etc are not hinted properly (as it used to be in 0.9.x)

![image](https://user-images.githubusercontent.com/10420662/32800303-012a2788-c98b-11e7-8057-a856de9530a1.png)

I believe they should be declared in `\Mockery\ExpectationInterface`

**Comment by downsider** [comment]
👍 

Is there anyone looking at this?

**Comment by robertbasic** [comment]
Should be done with #821
