### ISSUE TITLE
Overloading of named mocks

### ISSUE THREAD

**Issue by agxmeister** [mockery/mockery#822]
While covering the legacy code by tests I am faced with following challange: I have a hardcoded dependance on class and usage of constants of this class in the method I need to cover. It looks like the following:

```
public static function getTransport()
{
	if ((new Config())->get(Config::OPTION_ALLOW_RSYNC)) {
		...
	}
	...
}
```

I can workaround hardcoded dependance using "overload" feature like described here (http://docs.mockery.io/en/latest/cookbook/mocking_hard_dependencies.html?highlight=overload):

```
$configMock = \Mockery::mock('overload:Config');
$configMock->allows('get')->andReturn('expected');
```

Constants also could be workarounded using "namedMock" feature like described here (http://docs.mockery.io/en/latest/cookbook/class_constants.html?highlight=constant):

`$mock = \Mockery::namedMock('Config', 'ConfigStub');`

But how I can combine these two features together? In other words, how I can create a named mock and ensure that each newly created object of mocked class will support allowed methods?

**Comment by robertbasic** [comment]
This is now possible since #829 with a map of constants to mock.

**Comment by smitit173** [comment]
@robertbasic this is not possible if the constant is an array. It takes the array as a string. Is there any workaround for this?
