### ISSUE TITLE
Feature Request: expand class names based on namespace aliases

### ISSUE THREAD

**Issue by mvriel** [mockery/mockery#84]
What I'd like is if Mockery was able to expand a non-FCQN (Fully Qualified Class Name) into a FCQN using the T_USE statements in the current namespace.

Sometimes I can have rather long namespaces, which in turn could clutter my mock instantiation, example:

``` php
<?php
m::mock('My\Name\Space\Is\Really\Long\Because\I\Like\To\Be\Specific', array('getId' => 'foo'));
```

What I'd like is this:

``` php
<?php
use My\Name\Space\Is\Really\Long\Because\I\Like\To\Be\Specific;

m::mock('Specific', array('getId' => 'foo'));
```

To be able to do this I reckon that you'd need to statically reflect the calling class. I do not know of any method to retrieve a list of namespace aliases other than that

**Comment by robertbasic** [comment]
Given that we have `Foo::class` in PHP now, since 5.5, and minimum supported version by Mockery is 5.6, I'm going to close this feature request as a won't fix.
