### ISSUE TITLE
Mockery is not compatible with phpunit 7.0

### ISSUE THREAD

**Issue by LastDragon-ru** [mockery/mockery#850]
> The `PHPUnit\Framework\BaseTestListener` class has been removed, it was deprecated since PHPUnit 6.4. Please use the `PHPUnit\Framework\TestListenerDefaultImplementation instead`.

**Comment by patkoscsaba** [comment]
If you need Mockery to work with PHP 7 and you don't want to wait. I hacked it. It's a very simple change. 5 minutes of work.
Change TestListener class like this:
class TestListener implements \PHPUnit\Framework\TestListener
{
	use \PHPUnit\Framework\TestListenerDefaultImplementation;
    /**
     * endTest is called after each test and checks if \Mockery::close() has
     * been called, and will let the test fail if it hasn't.
     *
     * @param Test  $test
     * @param float $time
     */
    public function endTest(Test $test, float $time) : void
    { ... }
...}

**Comment by barryvdh** [comment]
I submitted a PR in #880

**Comment by prisis** [comment]
Submitted a pr #903, added new listener for all supported phpunit version :)
