### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by robertmain** [mockery/mockery#855]
Having problems right now writing my tests and understanding the error output produced by mockery. 

Would be cool to have some API docs as well as the cookbook type docs available at docs.mockery.io with information about what params each method accepts, what it returns etc. etc.

Willing to help with this if help is needed or there are already efforts underway to do something like this...

**Comment by robertbasic** [comment]
I would accept a PR starting this.

**Comment by robertmain** [comment]
Cool, see #857
