### ISSUE TITLE
Cannot mock interfaces that define method allows() or expects()

### ISSUE THREAD

**Issue by aedart** [mockery/mockery#861]
It is not possible to mock an interface that defines the method `allows` or `expects`. This is a bit frustrating.
More accurate, when attempting to mock Laravel's Auth Access `Gate` interface, the code results in a fatal error.

```php
use Illuminate\Contracts\Auth\Access\Gate;
use \Mockery as m;

class AccessGateMockTest extends UnitTestCase
{
    /**
     * @test
     */
    public function canMockAccessGate()
    {
        $mock = m::mock(Gate::class);
    }
}
```

Is there any way that you can mock an interface that defines such methods?

**Comment by robertbasic** [comment]
@davedevelopment did the `AvoidMethodClashPass` pass work for this? https://github.com/mockery/mockery/pull/799/files#diff-63e97660b6c69b74161042f637c1094d could we add that back?

**Comment by aedart** [comment]
I guess that could work. Haven't tried it yet, but appears valid enough.

**Comment by davedevelopment** [comment]
It did work, but it meant that `allows` and `expects` couldn't go in to the `MockInterface`. I know it's a bit frustrating, but mockery's ease of use comes from limitations like this. 

IMO if we want that pass back in, what we may have to do is have 

``` php
interface MockInterface extends LegacyMockInterface
```

Where LegacyMockInterface contains everything except the new methods. I'd then have that pass remove the new `allows` and `expects` methods as well as swap out MockInterface for LegacyMockInterface. Does that make sense?

**Comment by aedart** [comment]
Hmmm... Well, on one hand, I would like the issue resolved, but wouldn't like for you mates to "destroy" features, because of it. What about new names, such as `mockAllows` and `mockExpects` (_I know, it's very corny_)? Anyone that then still falls into this issue would be much more limited, rather than "allows" and "expects", which I could imagine is far more used than either of us know about.

Alternatively, each mock could be added a single gateway or proxy method, which then could expose all mockery's api. That should prevent 99.9% of all naming collisions. Yet that too would require major refactoring...

Honestly, I'm not the most qualified to answer this. Perhaps you / we should involve a few other opinions.

**Comment by okneloper** [comment]
Just to confirm, this was introduced in v1.0, so guys experiencing issues can stay on v0.9 for the time being.

**Comment by sebastiaanluca** [comment]
Any updates? Still an issue for me.

**Comment by davedevelopment** [comment]
@sebastiaanluca yes, see the PR the is mentioned above, any feedback appreciated.
