### ISSUE TITLE
Mocking an object that extends an abstract with private constructor

### ISSUE THREAD

**Issue by panosru** [mockery/mockery#863]
Hello,

could anyone help me with the following?

```php
require_once 'vendor/autoload.php';

/**
 * Interface FooInterface
 */
interface IFoo
{
    /**
     * @return int
     */
    public function value(): int;

    /**
     * @return string
     */
    public function bar(): string;
}

/**
 * Class FooAbstract
 */
abstract class FooAbstract implements IFoo
{
    /**
     * @var int
     */
    private $id;

    /**
     * FooAbstract constructor.
     * @param int $id
     */
    final private function __construct(int $id)
    {
        $this->id = $id;
    }

    /**
     * @return FooAbstract
     */
    final public static function create(): self
    {
        return new static(self::generateId());
    }

    /**
     * @return int
     */
    final public function value(): int
    {
        return $this->id;
    }

    /**
     * @return int
     */
    private static function generateId(): int
    {
        return rand();
    }

    /**
     * @param IFoo $foo
     * @return bool
     */
    final public function equals(IFoo $foo) : bool
    {
        return (get_class($foo) === static::class)
            && ($foo->value() === $this->value())
            && ($foo->bar() === $this->bar());
    }
}

/**
 * Class MyFirstFoo
 */
final class MyFirstFoo extends FooAbstract
{
    /**
     * @return string
     */
    public function bar(): string
    {
        return 'Bar A';
    }
}

final class MySecondFoo extends FooAbstract
{
    /**
     * @return string
     */
    public function bar(): string
    {
        return 'Bar A';
    }
}

/**
 * Class FooBarTest
 */
class FooBarTest extends \PHPUnit\Framework\TestCase
{
    /** @var MyFirstFoo */
    private $var1;

    /** @var MyFirstFoo */
    private $var2;

    /** @var MySecondFoo */
    private $var3;

    public function setUp()
    {
        $this->var1 = MyFirstFoo::create();
        $this->var2 = MyFirstFoo::create();
        $this->var3 = MySecondFoo::create();
    }

    public function tearDown()
    {
        Mockery::close();
    }

    public function testVar1EqualsVar1()
    {
        $this->assertTrue($this->var1->equals($this->var1));
    }

    public function testVar1EqualsVar2()
    {
        $this->assertFalse($this->var1->equals($this->var2));
    }

    public function testVar1EqualsVar3()
    {
        $this->assertFalse($this->var1->equals($this->var3));
    }

    public function testFooAbstract()
    {
        /** @var FooAbstract $mock */
        $mock = Mockery::namedMock('MyThirdFoo', FooAbstract::class)
            //->makePartial()
            ->shouldReceive('bar')
            ->andReturn('Bar B')
            ->getMock();

        //$this->assertEquals('Bar B', $mock->bar());
        $this->assertTrue($mock->equals($mock));
    }
}
```

Running `phpunit test.php` on the above file I receive:

```bash
$ phpunit test.php
PHPUnit 7.0.2 by Sebastian Bergmann and contributors.

...E                                                                4 / 4 (100%)

Time: 318 ms, Memory: 4.00MB

There was 1 error:

1) FooBarTest::testFooAbstract
TypeError: Return value of FooAbstract::value() must be of the type integer, null returned

~/testing/test.php:58
~/testing/test.php:76
~/testing/test.php:153
~/testing/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:508
~/testing/vendor/phpunit/phpunit/src/TextUI/Command.php:205
~/testing/vendor/phpunit/phpunit/src/TextUI/Command.php:153

ERRORS!
Tests: 4, Assertions: 3, Errors: 1.
```

How can I mock an object that extends from FooAbstract and instantiated with FooAbstract::create() method and have a bar() method?

Thanks!

**Comment by robertbasic** [comment]
From looking at the code, the problem seems to be that the `id` is never set when mocking so the `value` method always returns `null`. Given this set up, I'm not sure this would be even possible to mock.

**Comment by panosru** [comment]
@radeksimko yes sorry, I wasn't very descriptive on my issue, this is exactly what I would like to mock.

The use case is, as I use DDD architecture and all that comes with it like CQRS, ES etc. etc.. the above scenario is a common scenario for Aggregates and Entities where I want to create an object and automatically receive a UUID for that.

So, on the actual code above, we have an `IFoo` interface and a `FooAbstract` abstract class. The `FooAbstract` abstract class provide some functionality in order to take upon it some automation for objects that inherit `FooAbstract`.  The main thing is that the `__construct` method is *private* in order to avoid the creation of the object via `new` keyword, and instead use static method `create` in order to receive that same object but with a generated id. While we could argue upon why not generating the id via the `__construct` method, so we could have something like the following:

```php
/**
 * Class FooAbstract
 */
abstract class FooAbstract implements IFoo
{
    /**
     * @var int
     */
    private $id;

    /**
     * FooAbstract constructor.
     * @param int $id
     */
    final private function __construct(int $id)
    {
        $this->id = self::generateId();
    }

    /**
     * @return int
     */
    final public function value(): int
    {
        return $this->id;
    }

    /**
     * @return int
     */
    private static function generateId(): int
    {
        return rand();
    }

    /**
     * @param IFoo $foo
     * @return bool
     */
    final public function equals(IFoo $foo) : bool
    {
        return (get_class($foo) === static::class)
            && ($foo->value() === $this->value())
            && ($foo->bar() === $this->bar());
    }
}
```

but as I said, the example I provided, was just to demonstrate the issue, and the issue reflects a use case that when you want to create a new object, then it should receive a new *uuid (id)*, but there is a case, where you want to instantiate an object via a provided *uuid (id)*, then it should not generate a new *uuid (id)* on the `__construct` method.

Imagine the following *(not working code)*:

```php
/**
 * Interface FooInterface
 */
interface IFoo
{
    /**
     * @return int
     */
    public function value(): int;

    /**
     * @param string $id
     * @return IFoo
     */
    public static function from(string $id): IFoo;
}

/**
 * Class FooAbstract
 */
abstract class FooAbstract implements IFoo
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $bar;

    /**
     * FooAbstract constructor.
     * @param int $id
     * @param string $bar
     */
    final private function __construct(int $id, string $bar)
    {
        $this->id = $id;
        $this->bar = $bar;
    }

    /**
     * @return FooAbstract
     * @param string $bar
     */
    final public static function create(string $bar): self
    {
        return new static(self::generateId(), $bar);
    }

    /**
     * @return int
     */
    final public function value(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    final public function getBar(): string
    {
        return $this->bar;
    }

    protected static function createFrom(string $id, IRepository $repositoryInstance)
    {
        // We take the provided $id and ask our injected repository
        // to search for that id and bring us the value of
        // bar related to that id
        return new self($id, $repositoryInstance->findOne($id)->get('bar'));
    }

    /**
     * @param IFoo $foo
     * @return bool
     */
    final public function equals(IFoo $foo) : bool
    {
        return (get_class($foo) === static::class)
            && ($foo->value() === $this->value())
            && ($foo->bar() === $this->bar());
    }

    /**
     * @return int
     */
    private static function generateId(): int
    {
        return rand();
    }
}

/**
 * Class MyFirstFoo
 */
final class MyFirstFoo extends FooAbstract
{
    /**
     * @param string $id
     * @return IFoo
     */
    public static function from(string $id): IFoo
    {
        return self::createFrom($id, $repository_pulled_with_di);
    }
}


$foo = MyFirstFoo::create('My First bar');
$foo2 = MyFirstFoo::from(123456789);
```

So the key difference is that in that code, I implemented the `Repository` concept which is injected in the abstract `createFrom` method by `from` method of the concrete class. This allows us to either create an object of `IFoo` by passing directly the value of `$bar`, or instantiate an object of `IFoo` by id. 

Going back to my original example, which is much more simplified, if there is a way to mock the `FooAbstract` would be very neat, since so far in my test suite *(I use codeception)*, I have inside my `tests/_support/` folder, dummy classes like the `MyFirstFoo` in order to be able to run my tests, would be great to be able to get rid of those files and just mock them.

Hope this adds some `use case` to the issue.

thanks in advance!

**Comment by robertbasic** [comment]
I... honestly have no idea what do you want to mock here? This all seems really complicated and complex.

**Comment by panosru** [comment]
@robertbasic To put it simply, I want to create a mock object that extends `FooAbstract` abstract class and could behave like `MyFirstFoo` in order to the creation of dummy objects like `MyFirstFoo` inside my tests. Does that make sense? 

Currently inside my `tests/_support` folder I have files that contain dummy objects that I created in order to use them for testing purposes. As this does not bother me that much, would be best to be able to get rid of them though. 

So far I use Mockery to mock some simplier stuff, mostly external objects that belog outside of hexagonal architectural pattern (things like external services and etc).

**Comment by robertbasic** [comment]
Well, you can just do `$mock = \Mockery::mock(FooAbstract::class);` but that mock makes no sense because all your methods are final, you can't set expectations on any of those methods.

**Comment by panosru** [comment]
`$mock = \Mockery::mock(FooAbstract::class);` won't work since the scope of `__construct` is set to `private`...

**Comment by robertbasic** [comment]
I mean it works, but as soon as you call the `value` method it breaks with the error `Uncaught TypeError: Return value of FooAbstract::value() must be of the type integer, null returned`.

With your current setup as is, I don't think you can make this work at all.

**Comment by panosru** [comment]
basically I thought that something like this would work:

```php
$mock = Mockery::namedMock('MyThirdFoo', FooAbstract::class)
    ->makePartial()
    ->shouldReceive('from')
    ->andReturn() //What to do here in order to replicate `return self::createFrom($id, 'Bar A');` ?
    ->getMock();

$object = $mock::create('Something');
$object2 = $mock::from('83467535');
```

but is not, the `$mock::create('Something');` return's me the object I expect, but `$object2 = $mock::from('83467535');` is not, so I'm currently trying to figure that out.

**Comment by robertbasic** [comment]
You can use `andReturnSelf` there so it returns the mock itself, but again, it will fail on the call to the `value` method. Honestly, I'd suggest simplifying your approach on this entire FooAbstract thing.

**Comment by davedevelopment** [comment]
I don't think what you want to achieve is possible, not while `value` or your real life equivalent is final.

**Comment by panosru** [comment]
@robertbasic well, `andReturnSelf` would return `self`, as expected, but as you also mentioned, it won't solve the issue. The abstract, at least on the use case of *Entity* (in DDD world) and *AggregateRoot* the way that is implemented is already simple enough. The way I use the tests now is also simplified since inside my `tests/_support` directory I have testing objects *(in a way I have a testing mini-app)* to use them for testing purposes, at that point I believe I will stick to having dummy objects and use them for testing purposes as they are easier to handle rather than mocking them all, but mocking and spying them comes very handy to maximise the testing of the app.

@davedevelopment yeap, I ended up with the same answer, I guess closing that issue is a good idea also. I will leave it open for now and close it tomorrow.
