### ISSUE TITLE
setConstantsMap is persent in documentation but is not present in code

### ISSUE THREAD

**Issue by hhovakimyan** [mockery/mockery#866]
Hi, I was looking at the documentation for mocking class constants and found this solution
```
\Mockery()->getConfiguration->setConstantsMap([
    'Fetcher' => [
        'SUCCESS' => 'success',
        'FAILURE' => 'fail',
    ]
]);
```
on this page http://docs.mockery.io/en/latest/cookbook/class_constants.html
But I was confused when I didn't found `setConstantsMap` in package code. 
Using mockery version **1.0**

**Comment by robertbasic** [comment]
Sorry about the confusion, the `setConstantsMap` is not in a tagged version yet, it's available on `master`.

**Comment by davedevelopment** [comment]
You can see the "stable" documentation here http://docs.mockery.io/en/stable/cookbook/class_constants.html

**Comment by carltondickson** [comment]
This should work, have created a PR to update the docs
```
\Mockery::getConfiguration()->setConstantsMap([
    'Fetcher' => [
        'SUCCESS' => 'success',
        'FAILURE' => 'fail',
    ]
]);
```
