### ISSUE TITLE
Call counts broken if class is instantiated multiple times

### ISSUE THREAD

**Issue by rbalik** [mockery/mockery#882]
Hi, I've run into an issue where if my mock object is created multiple times in the calling code then call count expectations fail.

Here's an example:

```
class A
{
   public function testA($var)
   {
   }
}

class B
{
   public function testB($var)
   {
      $a1 = new A();
      $a2 = new A();
      $a1->testA(100);
   }
}
```

If I then create a mock like this the test fails because it says it was called zero times:

```
$aMock = Mockery::mock('overload:A');
$aMock->shouldReceive('testA')
  ->with(100)
  ->once();
```

**Comment by rbalik** [comment]
That test was a little simplified but here's a single file that reproduces the problem:

```
<?php
class A
{
   public function testA($var)
   {
   }
}

class B
{
   public function testB()
   {
      $a1 = new A();
      $a2 = new A();
      $a1->testA(100);
   }
}

class MockeryTest extends \Mockery\Adapter\Phpunit\MockeryTestCase
{
    public function testCount()
    {
        $aMock = Mockery::mock('A');
        $aMock->shouldReceive('testA')
            ->with(100)
            ->once();

        $b = new B();
        $b->testB();
    }
}
```

**Comment by rbalik** [comment]
Oh and this is with 1.1 and PHP 7.0

**Comment by undertext** [comment]
@rbalik Did you mean "Mockery::mock('overload:A');" in last example?
If yes then it's designed to work in this way.
From the [documentation](http://docs.mockery.io/en/latest/reference/creating_test_doubles.html#overloading) for overload:

> created new instances of that class will import any expectations set on the origin mock

So in your example `testA` method is expected to be called once on every instance.
Let me illustrate it with my example:

```php
 public function testOverload(){
    $m = mock('overload:MyNamespace\MyClass');
    $m->shouldReceive('do')
      ->with('job')
      ->once();

    $one = new MyNamespace\MyClass();
    $two = new MyNamespace\MyClass();
    $one->do('job');
    // If you uncomment next line test will pass.
    // $two->do('job');

  } 
```

The only hacky solution I see is something similar to proposed in #899 
And it will look like this: 
```php
 public function testOverload() {
    $m = mock('overload:MyNamespace\MyClass');
    $callsCount = 0;
    $m->shouldReceive('do')
      ->withArgs(function ($arg) use (&$callsCount) {
        $callsCount++;
        return $arg == 'job';
      });

    $one = new MyNamespace\MyClass();
    $two = new MyNamespace\MyClass();
    $one->do('job');

    $this->assertEquals($callsCount, 1);

  } 
```

**Comment by rbalik** [comment]
I see. That makes sense. Wish there was a built-in way to make that call count global though. Thanks for the workaround. We'll give that a try.

**Comment by robertbasic** [comment]
Closing this issue as an explanation and workaround was provided by @undertext, thank you!
