### ISSUE TITLE
Create "DO NOT EDIT" header

### ISSUE THREAD

**Issue by maja42** [mockery/mockery#896]
When generating go sources with mockery, I expect the generated source to contain the following comment:

// Code generated by mockery. DO NOT EDIT.

This is the standard way of marking generated files, as defined by https://github.com/golang/go/issues/13560.

Currently, the comment "// Code generated by mockery v1.0.0" is used, which is not standard-conform.

**Comment by robertbasic** [comment]
But... this is a PHP project, not a golang project.

**Comment by maja42** [comment]
Sorry! This was meant for https://github.com/vektra/mockery/
