### ISSUE TITLE
Mocking mysqli_result->num_rows

### ISSUE THREAD

**Issue by zwiebelspaetzle** [mockery/mockery#902]
How does one mock a property on a PHP extension class?  I'm trying to mock `mysqli_result->num_rows`.  

Using `$mock->num_rows = 1` gives the following error: `Error: Cannot write property`.  

Using `$mock->set('num_rows', 1)` gives: `Mockery\Exception\BadMethodCallException: Method Mockery_13_mysqli_result::set() does not exist on this mock object`

**Comment by davedevelopment** [comment]
Sadly I don't think Mockery can do that, not for an internal class that blocks assignment.
