### ISSUE TITLE
How to add interface to mock with "overload"?

### ISSUE THREAD

**Issue by baambaam** [mockery/mockery#906]
I want to test `TestingClass::first()` method. When i use `Mockery::mock('overload:'.CurrencyEnum::class);` I need to add `BaseCurrency` interface to this mock but i don't know how to do it.

error: `(..) must be an instance of \BaseCurrency, instance of \CurrencyEnum given`

    class CurrencyEnum implements BaseCurrency
    {
        /* methods */
    }

    class TestingClass
    {
        public function first(string $currencySymbol)
        {
            $abc = 'some_string';
    
            return $this->second($abc, new CurrencyEnum($currencySymbol));
        }
    
        private function second(string $abc, BaseCurrency $currency)
        {
            /* code */
        }
    }

**Comment by davedevelopment** [comment]
Try

``` php
$mock = Mockery::mock('overload:'.CurrencyEnum::class, BaseCurrency::class);
```
