### ISSUE TITLE
Expect call to magic methods

### ISSUE THREAD

**Issue by rlvillacarlos** [mockery/mockery#915]
I am wondering if there is a way to expect a call to the magic methods, __get and __set, when an inaccessible property is accessed/modified? Based on the documentation, mockery does not support mocking magic methods but I can get/set public properties in a mock. Now, what if I want to know if a property is accessed/modified once or several times? Is there a clean way to do this?

**Comment by davedevelopment** [comment]
@rlvillacarlos I don't think either of those is supported in any kind of clean way, I'd recommend handcrafting a fake in those circumstances.

**Comment by rlvillacarlos** [comment]
I actually do not see how I can handcraft a fake with properties I can expect. For example, I have an object of type `User` and has a property `name` that is not defined in the User class but instead it will trigger the `__get` method when accessed. If we can put expectation to the `__get` method with 'name' as argument, I can determine if the name property is accessed. If I then handcraft a fake, I can define the name property in the fake but as I understand it, I cannot put expectation to a non-method. So handcrafting a fake will not solve the issue., I think?

**Comment by davedevelopment** [comment]
@rlvillacarlos when I said hand crafted, I meant fully written by hand. Here's a basic example using an anonymous class:

``` php
class RealClass
{
    private $attrs = [];

    public function __get($attr)
    {
        return $this->attrs[$attr];
    }

    public function __set($attr, $value)
    {
        $this->attrs[$attr] = $value;

        return;
    }
}

$myFake = new class extends RealClass
{
    public $calls = [];

    public function __get($attr)
    {
        $this->calls[] = ['__get', func_get_args()];

        return parent::__get($attr);
    }

    public function __set($attr, $value)
    {
        $this->calls[] = ['__set', func_get_args()];

        return parent::__set($attr, $value);
    }
};

$myFake->dave = 123;
echo $myFake->dave; // 123
var_dump($myFake->calls);
```

That would spit out the equivalent of:

``` json
[
    [
        "__set",
        [
            "dave",
            123
        ]
    ],
    [
        "__get",
        [
            "dave"
        ]
    ]
]
```

You could then  assert on the contents of the `calls` attribute:

``` php
$myFake = new class extends RealClass
{
    // <snip>

    public function accessCount(string $attr): int
    {
        return count(array_filter($this->calls, function ($call) {
            return $call[0] == '__get';
        }));
    }
};

$myFake->dave = 123;
echo $myFake->dave; // 123
echo $myFake->dave; // 123
echo $myFake->dave; // 123
echo $myFake->dave; // 123
echo $myFake->dave; // 123

$this->assertEquals(5, $myFake->accessCount('dave'));

```

**Comment by rlvillacarlos** [comment]
I see your point now. Creating a method just to determine the number of times a property is accessed seems too much for what I need and I was kind of expecting that I can use functionalities already available in mockery instead of recreating it from scratch. I hope this feature will be considered on the next release. Anyway thanks.
