### ISSUE TITLE
Exception when mocking protected method and configured to not allow non-existent methods

### ISSUE THREAD

**Issue by dciancu** [mockery/mockery#934]
```php
<?php

require 'vendor/autoload.php';

class Stub
{
    protected function test()
    {
        //
    }
}

Mockery::getConfiguration()->allowMockingNonExistentMethods(false);

Mockery::mock(Stub::class)->shouldAllowMockingProtectedMethods()->shouldReceive('test');
# Fatal error: Uncaught Mockery\Exception: Mockery's configuration currently forbids
# mocking the method test as it does not exist on the class or object being mocked
```

**Comment by davedevelopment** [comment]
Could be a can of worms this one. If the `allowMockingNonExistentMethods` is set to `false`, I think we build up a list of methods they are allowed to mock when the mock is created, which will somehow need refreshing maybe if we the allow mocking protected methods?

**Comment by dciancu** [comment]
@davedevelopment I just looked at the code and it doesn't look complicated.

Basically, upon Mock init, if `allowMockingNonExistentMethods` is set to `false`, we build a list of methods that are public and not static, which is saved in `_mockery_mockableMethods`. This list is only written to from the `mockery_init` function and `shouldAllowMockingMethod` which adds the function to this list. So it should be safe to update the list with protected methods when `shouldAllowMockingProtectedMethods` and problem solved. Should I submit a PR?

**Comment by dciancu** [comment]
@davedevelopment Also may I ask why did you add the `!isStatic()` check?
https://github.com/mockery/mockery/blob/edfda1c7917df71213b330aa6666bdef068e5196/library/Mockery/Mock.php#L178
I can see you added this during the refactor in commit 70fa1f1.
Calling static methods directly on object (like `$this->staticFunc()`) is valid PHP 7 syntax.
This forbids us from setting expectations on static methods called object style `->` when we have `allowMockingNonExistentMethods` set to `false`.

**Comment by davedevelopment** [comment]
@dciancu Sorry for the delay, I've just merged the PR, thank you.

Regarding the `!$method->isStatic()`, I'm not 100% sure, but it's probably something more to do with the way Mockery has to deal with method calls than the way PHP allows you to call the methods if that makes sense? Perhaps try removing that check and see if it works?
