### ISSUE TITLE
Verify changing object as arguments of multiple function calls

### ISSUE THREAD

**Issue by SPie** [mockery/mockery#950]
I want to use a spy to verifying a method calls another method several times with an object that changes its state between those calls.
For example, the method could look like this:
```php
public function methodToTest()
{
    $objectToTest = (new ObjectToTest())
        ->setProperty(1);

    $this->otherMethod($objectToTest);
   
    $objectToTest->setProperty(2);

    $this->otherMethod($objectToTest);
}
```
I tried my tests like:
```php
$spy
    ->shouldHaveReceived('otherMethod')
    ->with(Mockery::on(function(ObjectToTest $argument) {
        return $argument->getProperty() == 1;
    })
    ->once();

$spy
    ->shouldHaveReceived('otherMethod')
    ->with(Mockery::on(function(ObjectToTest $argument) {
        return $argument->getProperty() == 2;
    })
    ->once();
```

Because PHP passes objects as references on function calls, I can't verify the different states of my object. With the second `$objectToTest->setProperty(2)` call, the object passed to the first `otherMethod()` now has the property value '2' too.
Is there a way to handle such situations and I missed it in the documentation, or is it a kind of "bug" because the method arguments are not cloned before passed to `Mockery\MethodCall`?

**Comment by davedevelopment** [comment]
Yeah, I don't think it's possible with spies. We could try something like cloning when recording, but I feel our mileage would vary significantly with respect to return on investment. 

Can you switch to mocking and specify the expectations upfront?

**Comment by SPie** [comment]
Mocking would work, but it might not work for every test scenario because it would fail the test before being able to assert other stuff.
I could open a PR for cloning the arguments before passing them to the `Mockery\MethodCall` object, but I'm not sure if this would be wanted behaviour because it could break tests using the current implementation.

**Comment by davedevelopment** [comment]
@SPie I think cloning them would open up a can of worms myself and would rather we worked around the edge cases like this with the features we have.

**Comment by SPie** [comment]
@davedevelopment Alright, that's what I thought.
Thank you anyway.
