### ISSUE TITLE
How to correctly use \Mockery\Container::mock to blacklist methods?

### ISSUE THREAD

**Issue by mfn** [mockery/mockery#954]
The builder has the method `\Mockery\Generator\MockConfigurationBuilder::addBlackListedMethods`.

The docs explain how to use the `\Mockery\Generator\MockConfigurationBuilder::addWhiteListedMethods` however with this syntax, from http://docs.mockery.io/en/latest/reference/partial_mocks.html 
> `$mock = \Mockery::mock('MyClass[foo,bar]');`

The `[foo,bar]` translates to `addWhiteListedMethods` on the builder.

What is the official/correct way to use the `addBlackListedMethods` with this syntax?

I was able to construct something which seems to work:
```php
            Mockery::mock(
                Foo::class,
                // Constructor args
                [
                    // …
                ],
                [
                    Mockery::BLOCKS => [
                        'methodNotToMock',
                    ],
                ]
            );
```
Is this good/correct?

I found this out by backtracing the sources and playing around. But nothing here is officially documented and the actual value of the constant (`Mockery_Forward_Blocks`) doesn't inspire confidence to me I'm on the right track 😄 

However reading through `\Mockery\Container::mock` this was the only way I could figure this out:
![image](https://user-images.githubusercontent.com/87493/53633859-ea579200-3c18-11e9-8927-307705c8840d.png)

Thanks

**Comment by davedevelopment** [comment]
Hi @mfn, if it were me, I'd use the builder. The `Mockery::mock` and `Mockery::spy` methods will accept a builder directly and build a mock from that:

``` php
<?php

require "vendor/autoload.php";

Mockery::setLoader(new Mockery\Loader\RequireLoader(sys_get_temp_dir()));

class Foo {
    function methodNotToMock(): int { return 123; }
    function methodToMock(): int { return 456; }
}

$mock = \Mockery::spy((new Mockery\Generator\MockConfigurationBuilder())
    ->addTarget(Foo::class)
    ->addBlackListedMethod('methodNotToMock')
);

var_dump($mock->methodNotToMock()); // int(123)
var_dump($mock->methodToMock()); // int(0)
```

**Comment by mfn** [comment]
@davedevelopment 
> The Mockery::mock and Mockery::spy methods will accept a builder directly and build a mock from that

Nice, was not aware of this! Definitely works and makes more sense 👍 

Although I've to admit, I do like the terse format of the `::mock` method:
> $mock = \Mockery::mock('MyClass[foo,bar]');

Would you be open to add support for adding blacklisted methods here too?

As a suggestion: we could use the `!` to exclude them:

```php
$mock = \Mockery::mock('MyClass[foo,!bar]');
```
- `foo` gets added to whitelist
- `bar` gets added to blacklist

I _think_ in practice it's rather going to be a list of blacklist methods though:
```php
$mock = \Mockery::mock('MyClass[!foo,!bar]');
```
