### ISSUE TITLE
Mockery 2.0 discussion

### ISSUE THREAD

**Issue by davedevelopment** [mockery/mockery#962]
Should there be a Mockery 2.0? 

As one of the maintainers, I have zero to little interest in maintaining Mockery's more complicated and esoteric features, such as [instance mocks](http://docs.mockery.io/en/latest/reference/instance_mocking.html), [demeter chains](http://docs.mockery.io/en/latest/reference/demeter_chains.html), [class constants](http://docs.mockery.io/en/latest/cookbook/class_constants.html) etc. 

I occasionally might use [partial mocks](http://docs.mockery.io/en/latest/reference/partial_mocks.html), but that's very rare.

What I do a lot of is basic stubbing and spying, with the occasional bit of mocking. My preference for Mockery 2.0, would be to cut back on all of the aforementioned features and concentrate on making the basics really good, but that would probably be a different library altogether, as it would significantly break BC with previous versions. It wouldn't just be a case of changing syntax, Mockery would no longer support the paradigms it previously supported, meaning tests would probably need to be completely rewritten.

There's also the question of whether mockery is needed anymore. PHPUnit's [built in doubles](https://phpunit.readthedocs.io/en/8.0/test-doubles.html) are a lot better now and they also shipped first class support for [prophecy](https://phpunit.readthedocs.io/en/8.0/test-doubles.html#prophecy), so some people will turn to that too. Mockery's more esoteric features are probably one of the few things that makes it stand out from PHPUnit Doubles and Prophecy, but the better you get at testing your code, they less likely you are to use them.

**Comment by mfn** [comment]
> There's also the question of whether mockery is needed anymore. PHPUnit's [built in doubles](https://phpunit.readthedocs.io/en/8.0/test-doubles.html) are a lot better now and they also shipped first class support for [prophecy](https://phpunit.readthedocs.io/en/8.0/test-doubles.html#prophecy)

There's a detail which made be prefer Mockery over the years: if you define a mock but don't add expectations, Mockery fails.

To me this is an invaluable default to me. PHPUnits built in behaviour simple returns `null` on such calls and you don't need to define expectations for calls. Leading to all sorts of hidden/missing things in your tests, even if you're super careful.

PS: never used prophecy, though

**Comment by cbernard73** [comment]
I can accomplish the same thing in either Mockery or the built-in doubles, but Mockery is, in my opinion, far more elegant.  Here's an example of using Mockery to mock a service that provides a fluent interface:

```
$mService = $this->mockery->mock(MyService::class);
$mService->shouldReceive('prospect->update')
            ->andReturn(['id => 2, 'organisation_id' => 3);

$mService->shouldReceive('prospect->delete')
    ->andThrow(ClientException::class);
```

And then the same using the built-in doubles:

```
$mService = $this->getMockBuilder(MyService::class)
            ->disableOriginalConstructor()
            ->setMethods(['prospect','update','delete'])
            ->getMock();
        
$mService->expects($this->any())
    ->method('prospect')
    ->will($this->returnSelf());

$mService->expects($this->any())
    ->method('delete')
    ->will($this->returnSelf());

$mService->expects($this->any())
    ->method('update')
    ->will($this->returnValue(['id' => 2, 'organisation_id' => 3]));

$mService->expects($this->any())
    ->method('delete')
    ->will($this->throwException(new ClientException));
```

I'm not sure if the added elegance is worth the effort in maintaining Mockery, but it will surely be missed.

**Comment by JasonTheAdams** [comment]
I've only been using Mockery for a couple weeks now on a project, and I will say I've been very pleased with how it works. I have used partials a few times and can see their value as worth preserving. I haven't had a use-case for a number of features you're describing, though, and can't even envision using them. I'd be in support of trimming down on features if that helps improve the maintainability of the project.

**Comment by MaxelF** [comment]
Is there any new information on this topic?
