### ISSUE TITLE
Aliased mock of class that returns an instance of itself

### ISSUE THREAD

**Issue by straube** [mockery/mockery#963]
There is a dependency in a project I'm currently working that uses static method calls to interact with an API. I'm struggling to test one particular use case and I feel like I'll find other like this during the development roadmap.

Using this class as an example:

```
namespace Name\Space;
class User
{
    public static function list(): User[]
    {
        // ...
    }
    public static function create(array $attrs): User
    {
        // ...
    }
}
```

In case I just want to assert a method returns a primitive type, such as an array:

```
Mockery::mock('alias:\Name\Space\User')
    ->shouldReceive('list')
    ->andReturn([]);
```

It works fine, primarily because I'm not testing the array contents.

However, I have to call the `create` method, which returns an instance of the class itself (`User`). If I do something like this:

```
$user = new \Name\Space\User();
Mockery::mock('alias:\Name\Space\User')
    ->shouldReceive('list')
    ->andReturn($user);
```

The alias, obviously, won't work because the class was already loaded through the autoloader (composer's, in this case).

Does anyone have a suggestion on how to workaround this?

**Comment by straube** [comment]
Answering to this question you could earn +100 rep on StackOverflow: https://stackoverflow.com/questions/55423839/how-to-mock-an-aliased-class-with-a-method-that-returns-an-instance-of-itself

😄

**Comment by robertbasic** [comment]
Have you tried using `andReturnUsing`? http://docs.mockery.io/en/latest/reference/expectations.html#declaring-return-value-expectations

**Comment by straube** [comment]
Hey @robertbasic. That worked, thanks!

I actually, ended up finding out that I could use `andReturnSelf`. I'm only returning the mock instance itself from `create` function.

Since the framework I'm using expects the returned object to implement a method called `toJson`, I did the following:

```
$data = [
    // The object attributes ...
];

$mock = Mockery::mock('alias:\Name\Space\User', '\Illuminate\Contracts\Support\Jsonable');
$mock->shouldReceive('toJson')->andReturn($data);
$mock->shouldReceive('create')->andReturnSelf();
```

Feel free to answer my question on SO to get some extra rep there.
