### ISSUE TITLE
shouldReceive for private methods

### ISSUE THREAD

**Issue by vsychov** [mockery/mockery#964]
Hi, mockery disallow to mock private methods, how I can test code like this (doAction):

```
class Foo
{
    public function doAction($type)
    {
        switch ($type) {
            case 'no':
                $this->reject();
                break;

            case 'yes':
                $this->confirm();
                break;
        }
    }

    private function reject()
    {
        return 'reject';
    }

    private function confirm()
    {
        return 'confirm';
    }
}
```

I try:
```
class Test extends TestCase
{
    public function test()
    {
        $foo = Mockery::mock(Foo::class)
            ->makePartial()
        ;

        $foo->shouldReceive('confirm')->once();
        $foo->doAction('yes');
    }

    public function tearDown()
    {
        Mockery::close();
    }
}
```

but got expected error, `InvalidArgumentException: confirm() cannot be mocked as it is a private method`, is only way make reject and confirm protected?

**Comment by IgorVodka** [comment]
Hello.

Mocking private methods is technically impossible. 
Also, you should not mock them, as their implementation is supposed to be hidden. Instead, find another way to test your class (relying on public methods), or move your logic into different classes and apply composition.
