### ISSUE TITLE
How To Mock Private Methods

### ISSUE THREAD

**Issue by vishalinfyom** [mockery/mockery#968]
So, lets say i have following code and i want to mock `privateFunction()`. is it possible ??

```
Class A 
{
     private function privateFunction($param)
     {
            // stuff goes here
     }

    $mock = $this->getMockBuilder(A::class)
            ->disableOriginalConstructor()
            ->setMethods(['privateFunction' => 'params'])
            ->getMock();

     $mock->expects($this->once())
            ->method('privateFunction')
            ->will($this->returnValue(23)) ;
}
```

i am getting following errors

`
Trying to configure method "getPHPDocType" which cannot be configured because it does not exist, has not been specified, is final, or is static`

**Comment by prisis** [comment]
No you can't mock private methods
