### ISSUE TITLE
Mocking public static properties?

### ISSUE THREAD

**Issue by Torniojaws** [mockery/mockery#971]
According to the documentation, it should be done like this:

    $mock->shouldReceive('method')->andSet('property', 'value');

But when I do:

    $serviceMock = Mockery::mock('alias:Service')->shouldIgnoreMissing();
    // This
    $serviceMock->shouldReceive('init')->andSet('sqlConn', 'foobar');
    // Or this
    $serviceMock::$sqlConn = 'foobar';

I still get:

    Error: Access to undeclared static property: Service::$sqlConn

When the code to be tested does:

    Service::init(true, false);
    Service::$sqlConn->query($sql);

What is the correct way to mock the ``$sqlConn->query()`` part with Mockery?

**Comment by davedevelopment** [comment]
I don't think andSet was designed to work with static methods, but either way there's not a lot we can do there without inspecting the original source for `Service` on disk, which is a bit beyond Mockery's remit.

**Comment by Torniojaws** [comment]
Here's how I solved it in an alternative way, though this requires you to implement all methods of **Service** that are called during the test using `shouldReceive()`.
```
public function testSomething(): void {
    Mockery::mock('overload:Service', 'ServiceStub')
        ->shouldReceive('query')
            ->once()
            ->andReturn(array('something'));
    // etc...
}

class ServiceStub {
    public static $sqlConn = new Mysqli(); // Or your own mock implementation of Mysqli()
}
```

**Comment by robertbasic** [comment]
Closing as, like Dave said,  `andSet` wasn't meant to be used with static properties, plus a different approach was provided.

Thanks @Torniojaws!
