### ISSUE TITLE
MockeryTestCase::mockeryTestSetUp/mockeryTestTearDown

### ISSUE THREAD

**Issue by sweiguny** [mockery/mockery#972]
Hello,

i have a TestCase-Class where I need to mock heavily.
So I found in [the docs](http://docs.mockery.io/en/latest/reference/phpunit_integration.html) the following sentence:

> Extending `MockeryTestCase` or using the `MockeryPHPUnitIntegration` trait is the recommended way of integrating Mockery with PHPUnit, since Mockery 1.0.0.

So I checked [`MockeryTestCase`](https://github.com/mockery/mockery/blob/master/library/Mockery/Adapter/Phpunit/MockeryTestCase.php)  and I it has two methods:

- mockeryTestSetUp()
- mockeryTestTearDown()

What are they for? Do they definitely replace `setUp()` and `tearDown()` of `\PHPUnit\Framework\TestCase`?

Do I need to use the Mockery methods instead of the PHPUnit methods?

IMHO, the doc doesn't tell you enough about it...

**Comment by robertbasic** [comment]
Hello,

no, you should use phpunit's `setUp` and `tearDown`.

What the `MockeryTestCase` does for you is basically just using the `MockeryPHPUnitIntegration` trait.

**Comment by sweiguny** [comment]
Okay, thank you.
