### ISSUE TITLE
`expects` does not throw exception for multiple called method

### ISSUE THREAD

**Issue by jasonmccreary** [mockery/mockery#975]
I am trying stub a method which is called multiple times. However, there is one invocation I care about specifically.

Unfortunately, it does not raise an exception when the method **is not** called specifically with `'bar'`, but is called generically.

Here is an example to demonstrate the issue:

```php
    /** @test */
    public function it_does_not_throw_expects_exception()
    {
        $mock = Mockery::mock();

        $mock->shouldReceive('foo')->byDefault();
        $mock->expects('foo')
            ->with('bar')
            ->andReturn('success');

        $this->assertNull($mock->foo());

        // should throw exception since no call to `foo('bar')`...
    }
```

I have read other related issues and tried changing to a `spy`, removing `byDefault`, varying the order, and combinations therein. The test passes all the same even when I never call `foo('bar')`.

I would _expect_ it to throw an exception.

It would seem this should be possible given the description of `byDefault` and the more specific _matcher_ of `foo` called with `'bar'`. Apologies if I am missing something simple, but I tried several combinations and read threw other issues.

**Comment by davedevelopment** [comment]
Hi @jasonmccreary, good to see you here, I've not had the need to use it, but I love what you're doing with Laravel Shift.

Are you calling `Mockery::close();` anywhere, or using the PHPUnit integrations? This works as expected for me:

``` php
<?php

require "vendor/autoload.php";

$mock = Mockery::mock();

$mock->shouldReceive('foo')->byDefault();
$mock->expects('foo')
    ->with('bar')
    ->andReturn('success');

var_dump($mock->foo()); // NULL

Mockery::close(); // throws Mockery\Exception\InvalidCountException: Method foo('bar') from 
                  // Mockery_0 should be called exactly 1 times but called 0 times....

```

**Comment by jasonmccreary** [comment]
Thanks.

Yes, that was exactly the simple thing I was missing. Geez, RTFM JMac! My bad. 🤦‍♂ Thanks for debugging it for me.
