### ISSUE TITLE
runInSeparateProcess annotation ignored when aliasing class?

### ISSUE THREAD

**Issue by dingo-d** [mockery/mockery#977]
I'm trying to mock a class containing bunch of static methods (non refactored helper class) in my test. I created a mock class, and in my test I have

```php
<?php

namespace My_Plugin\Tests\Integration\Src\Admin_Menus;

use My_Plugin\Admin_Menus\Credentials;

use My_Plugin\Tests\Fixtures\Mock_Helper;

/**
 * Class that tests the Admin menu.
 *
 * @runTestsInSeparateProcesses
 */
class Credentials_Menu_Integration_Test extends \WP_UnitTestCase {

  /**
   * Test suite setUp method
   */
  public function setUp() {
    parent::setUp();
  }

  /**
   * Test suite tearDown method
   */
  public function tearDown() {
    parent::tearDown();
    \Mockery::close();
  }

  /**
   * Test default template name
   * @runInSeparateProcess
   * @preserveGlobalState disabled
   */
  public function test_menu_render() {
    $helper_mock = \Mockery::mock( 'alias:My_Plugin\Old\Helpers\General_Helper' );

    $helper_mock->shouldReceive( 'get_access_token' )
              ->andReturn( Mock_Helper::get_access_token() );
    $helper_mock->shouldReceive('get_refresh_token')
              ->andReturn( Mock_Helper::get_refresh_token() );

    // $menu = new Credentials();
    // $menu->register();
    // $render = $menu->process_admin_menu( [] );

    // $this->assertInstanceOf( 'My_Plugin\Core\Service', $menu );
  }

}
```

But even though I added `@runInSeparateProcess` and `@preserveGlobalState disabled` annotations, I'm getting 

> Mockery\Exception\RuntimeException: Could not load mock My_Plugin\Old\Helpers\General_Helper, class already exists
>
> /vendor/mockery/mockery/library/Mockery/Container.php:220
> /vendor/mockery/mockery/library/Mockery.php:117

The `shouldReceive` parts are never executed and my test fails.

My environment:

| Unit   |    version 
|----------|:-------------:|
| MacOS   |    10.14.5   
| phpunit/phpunit |  7.5.11 |
| mockery/mockery  |    1.2.2   |

I'm running WordPress integration tests generated by wp cli [scaffold command](https://developer.wordpress.org/cli/commands/scaffold/plugin/). And I'm using composer classmap to autoload my tests and classes

**Comment by davedevelopment** [comment]
Can you try only running that one test? If another test has already used `My_Plugin\Old\Helpers\General_Helper`, it will already be loaded I think.

**Comment by dingo-d** [comment]
I tried it, and it passed, but the problem is that I've now refactored that class and no longer need the mock 😄 

I tried running it on older code but now I cannot reproduce it, so I'll close the issue (and refactor the code not to include static methods, they are evil 😄 )
