### ISSUE TITLE
passthru method throws an error on overload

### ISSUE THREAD

**Issue by mitsuru793** [mockery/mockery#978]
> In cases where we want to call the real method of the class that was mocked and return its result, the passthru() method tells the expectation to bypass a return queue:
> via: [Expectation Declarations — Mockery Docs 1.0-alpha documentation](http://docs.mockery.io/en/latest/reference/expectations.html?highlight=passthru)

I think that passthu is needed to call real method.
However, I can't use this method on overload mock.

Here is example. Please help me.
This test will fail.

Is this a bug of mockery?

I use the version 1.2.2 of mockery.

`src/User.php`
```php
<?php
declare(strict_types=1);

namespace Php;

final class User
{
    /** @var string */
    public $name;

    public function __construct(string $name)
    {
        $this->name = $name;
    }

    public static function findByName(string $name): self
    {
        return new User($name);
    }
}
```

`tests/MockeryTest.php`
```php
<?php
declare(strict_types=1);

namespace Php;

use Helper\TestBase;
use Mockery;

final class MockeryTest extends TestBase
{
    public function testOverloadPasstThrough()
    {
        $mock = Mockery::mock('overload:' . User::class);
        $mock
            ->shouldReceive('findByName')
            ->withArgs(['mike'])
            ->passthru();

        $user = User::findByName('mike');
        $this->assertEquals('mike', $user->name);
    }
}
```

This is an error log.

```
Testing started at 23:26 ...
/usr/local/Cellar/php/7.3.3/bin/php /Users/mitsuru/project/issue-php-mockery/vendor/phpunit/phpunit/phpunit --configuration /Users/mitsuru/project/issue-php-mockery/phpunit.xml --filter "/(::testOverloadPasstThrough)( .*)?$/" Php\MockeryTest /Users/mitsuru/project/issue-php-mockery/tests/MockeryTest.php --teamcity
PHPUnit 8.1.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.3
Configuration: /Users/mitsuru/project/issue-php-mockery/phpunit.xml


call_user_func_array() expects parameter 1 to be a valid callback, class 'stdClass' does not have a method 'findByName'
 /Users/mitsuru/project/issue-php-mockery/vendor/mockery/mockery/library/Mockery/Expectation.php:184
 /Users/mitsuru/project/issue-php-mockery/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:106
 /Users/mitsuru/project/issue-php-mockery/tests/MockeryTest.php:19
 


Time: 65 ms, Memory: 6.00 MB


ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

Process finished with exit code 2
```

**Comment by davedevelopment** [comment]
Unfortunately overloaded mocks don't load the original class, so they don't have a parent method to pass through to.

**Comment by mitsuru793** [comment]
@davedevelopment 

Thank you very much!
I see. I can't use passthru method on overload mock.

I'll close this issue.

**Comment by DWMcload** [comment]
@davedevelopment 

> Unfortunately overloaded mocks don't load the original class, so they don't have a parent method to pass through to.

I experienced the same issue. 
"All mock objects, with the exception of Proxied Partials, allows us to make any expectation call to the underlying real class method using the passthru() expectation call."
This is under this point: http://docs.mockery.io/en/latest/reference/partial_mocks.html#special-internal-cases in the documentation.
Can it be extended or fixed to tell, it will not work with overload? 

I come to overload because the class I have to mock is a service which gets loaded via a provider and the method called from the provided doesn't become mocked. Any ideas how to solve this because the overload-passtrhu not works?

**Comment by davedevelopment** [comment]
@DWMcload not that I know of, without using something like Codeception/AspectMock

**Comment by DWMcload** [comment]
@davedevelopment wow, that was a quick and fair answer, thanks for your time. 
I found the definitive answer here: https://github.com/mockery/mockery/issues/75
> The basis of Expectations are that are identified as a unique combination of method name and arguments. You can't define 2 sets of argument in a single Expectation since then it has no unique identity. It's one of the minor pitfalls of mock objects in that you need to sometimes be overly prescriptive setting up the mock. by @padraic
