### ISSUE TITLE
How to test passing $this to mocked method

### ISSUE THREAD

**Issue by JasonTheAdams** [mockery/mockery#979]
Greetings!

I'm testing a class which instantiates another class and then runs a method like this:
```php
$upgrader = new Upgrade;
$upgrader->runUpgrade($this);
```

Here's how the test setup looks:
```
// Set up mock upgrade
/** @var Mockery\MockInterface $upgrade */
$upgrade = $this->spy(VersionUpgrade::class);

$upgrade->allows()->getVersion()->andReturns($version);
$upgrade->allows()->runUpgrade();
```
But when I run the test it doesn't match what's being allowed, here. I'm sure the reason is because the actual use of the method includes a parameter.

What I'm not sure how to do is tell Mockery that a specific class instance should be passed to the method. I don't want to mock that as it's the class I'm testing.

I'm sure there's a way to do it, I just can't figure it out. Any pointers here would be greatly appreciated!

**Comment by robertbasic** [comment]
Is the `Upgrade` class being instantiated inside the `VersionUpgrade` class? If so, then that Mockery considers a "hard dependency", and it's described in the cookbook [how to do it](http://docs.mockery.io/en/latest/cookbook/mocking_hard_dependencies.html).

**Comment by JasonTheAdams** [comment]
Thanks for responding so quickly, @robertbasic!

So `VersionUpgrade` is an interface for the `Upgrade` class. The context here is that it's a Laravel artisan command being tested. The command class passes the instance of itself to the `upgrade::runUpgrade()` method to allow for further commands to be run within the upgrade.

Are you suggesting injecting `$this` into the upgrader constructor instead of passing it to the method? I could do that, if that's what you're suggesting.

Thanks!

**Comment by robertbasic** [comment]
Well, now I'm not so sure what I'm suggesting as I'm not familiar with Laravel :)

Could you provide more context by giving a more accurate, but still simplified version of the code you want to test, and the test code you have so far?

**Comment by JasonTheAdams** [comment]
I ended up going the constructor route and did some refactoring. I didn't quite figure out how to handle a method parameter as an instance, but I circumvented my need for it.

I'll close this, but if anyone is able to chime in as how to mock a method with a class parameter, that would be useful for the future.
