### ISSUE TITLE
PHP 7.4 tests failing with, use of ReflectionType::__toString deprecated

### ISSUE THREAD

**Issue by mmachatschek** [mockery/mockery#981]
I just tried to run a build of `laravel/framework`  on travis with the 7.4snapshot version of PHP which resulted into failing tests because mockery casts the `ReflectionType` class into a string. The `ReflectionType::__toString()` method is deprecated and lets the tests fail now.

The phpunit project already updated this code in https://github.com/sebastianbergmann/phpunit/commit/73ece9281b571e50ad948a4d38c87a2edf77f860

You can view the failing tests here: https://travis-ci.com/mmachatschek/framework/jobs/212025164

**Comment by MarcusSchwarz** [comment]
There is already a pr for this: #980

**Comment by GrahamCampbell** [comment]
Yeh, this issue can be closed. The PR does fix the issue. Mockery's own tests confirm this, and I've also tried it myself on a real test suite.

**Comment by mmachatschek** [comment]
Can confirm. [Build](https://travis-ci.com/mmachatschek/framework/jobs/213518584) didn't show any exceptions from mockery anymore with the branch from the PR
