### ISSUE TITLE
shouldReceive()->with() compares parameters as integers

### ISSUE THREAD

**Issue by buhala** [mockery/mockery#983]
when running

```
		$mockClient
			->shouldReceive('post')
			->once()
			->with(['json' => '+415']

```

even if the method recieves `00415`, it will still pass

**Comment by davedevelopment** [comment]
Yes, I think generally it uses the "loose" comparison. I'm not sure if we have anything to make it strict, other than using `->with(Mockery::on(function () { /* check value */ )...` etc

**Comment by robertbasic** [comment]
You should either use our [complex argument matching](http://docs.mockery.io/en/latest/cookbook/mockery_on.html) or use one of the [hamcrest matchers](https://github.com/hamcrest/hamcrest-php)

Closing this issue as this is a deliberate choice within Mockery.

Thanks!
