### ISSUE TITLE
makePartial() not doing anything

### ISSUE THREAD

**Issue by Torniojaws** [mockery/mockery#989]
Mockery version 1.2.2
PHPUnit 7.4.3

In the below case, it appears that `makePartial()` doesn't change anything. Is there some syntax error below?

Here's a minimalistic example where it happens:
```php
<?php
use PHPUnit\Framework\TestCase;

/**
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 */
class JustTestingTest extends TestCase {
	
	protected function setUp(): void {
		$this->external = new ExternalThing();
	}
	
	protected function tearDown(): void {
		Mockery::close();
	}

	public function testPartial(): void {
		Mockery::mock('Unrelated')->makePartial()
			->shouldReceive('getLocation')
			->andReturn('Mars');
		$actual = $this->external->getValue();
		$this->assertEquals('hello Mars', $actual); // Fails, as 'hello world' is still returned
	}

}

class ExternalThing {
	public function getValue(): string {
		return Unrelated::getGreeting().' '.Unrelated::getLocation();
	}
}

class Unrelated {
	public static function getGreeting(): string {
		return 'hello';
	}
	public static function getLocation(): string {
		return 'world';
	}
}
```
The error in phpunit:
```
1) JustTestingTest::testPartial
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'hello Mars'
+'hello world'
```

**Comment by davedevelopment** [comment]
`getGreeting` and `getLocation` are static methods, so would require a different type of Mock.

You would need to use `Mockery::alias(Unrelated::class)`, but there are some consequences to doing this, see http://docs.mockery.io/en/latest/reference/creating_test_doubles.html?highlight=alias#aliasing

**Comment by robertbasic** [comment]
Closing as `makePartial` is not intended to be used with static methods.

If we can help you in any other way, please let us know @Torniojaws, thanks!
