### ISSUE TITLE
andReturnArgument()

### ISSUE THREAD

**Issue by downsider** [mockery/mockery#992]
Hi

In my experience with mockery, a number of times I have found myself needing to return an argument that was passed to a mocked method. In such cases, I have done something like this:

```
$mock->shouldReceive("myMethod")->andReturnUsing(
    function($arg){
        return $arg;
    });
```

This feels really clunky and boilerplatey, but is something commonly required for mocks of classes that do normalisation or follow the decorator pattern.
 
Seeing as PHPUnit has had this functionality for a long time, I feel we should introduce it into Mockery too. I propose we add the following syntax to enable returning arguments

```
$mock->shouldReceive("myMethod")->andReturnArgument(2);
    // where "2" is the index of the argument to return
```

Do you think this is something that can be implemented?

**Comment by davedevelopment** [comment]
I don't see why not, fire away :+1:

**Comment by downsider** [comment]
Hi @davedevelopment I've submitted a PR for this. Could you have a look at the comment I raised please? I'm interested in your opinion on this point.

**Comment by robertbasic** [comment]
Closing as #1001 was merged.

Thank you @downsider!
